// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package feeratepg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const getActorUsername = `-- name: GetActorUsername :one
SELECT username FROM accounts WHERE id = $1
`

func (q *Queries) GetActorUsername(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getActorUsername, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const getCurrentFeeRate = `-- name: GetCurrentFeeRate :one
SELECT version, fee_rate_nano FROM api_fee_rates ORDER BY version DESC LIMIT 1
`

type GetCurrentFeeRateRow struct {
	Version     int64
	FeeRateNano money.Amount
}

func (q *Queries) GetCurrentFeeRate(ctx context.Context) (GetCurrentFeeRateRow, error) {
	row := q.db.QueryRow(ctx, getCurrentFeeRate)
	var i GetCurrentFeeRateRow
	err := row.Scan(&i.Version, &i.FeeRateNano)
	return i, err
}

const insertFeeRate = `-- name: InsertFeeRate :one
INSERT INTO api_fee_rates (fee_rate_nano, created_by) VALUES ($1, $2)
RETURNING version, created_at
`

type InsertFeeRateParams struct {
	FeeRateNano money.Amount
	CreatedBy   *string
}

type InsertFeeRateRow struct {
	Version   int64
	CreatedAt time.Time
}

func (q *Queries) InsertFeeRate(ctx context.Context, arg InsertFeeRateParams) (InsertFeeRateRow, error) {
	row := q.db.QueryRow(ctx, insertFeeRate, arg.FeeRateNano, arg.CreatedBy)
	var i InsertFeeRateRow
	err := row.Scan(&i.Version, &i.CreatedAt)
	return i, err
}

const listFeeRates = `-- name: ListFeeRates :many
SELECT rate.version, rate.fee_rate_nano, rate.created_at,
	COALESCE(rate.created_by::text, '')::text AS created_by_id,
	COALESCE(actor.username, '')::text AS created_by_username,
	COALESCE(audit.reason, '')::text AS reason
FROM api_fee_rates rate
LEFT JOIN accounts actor ON actor.id = rate.created_by
LEFT JOIN LATERAL (
	SELECT reason FROM audit_events
	WHERE target_type = $1 AND target_id = rate.version::text AND action = $2
	ORDER BY id LIMIT 1
) audit ON true
ORDER BY rate.version DESC
LIMIT $3::bigint
`

type ListFeeRatesParams struct {
	AuditTargetType string
	AuditAction     string
	RowLimit        int64
}

type ListFeeRatesRow struct {
	Version           int64
	FeeRateNano       money.Amount
	CreatedAt         time.Time
	CreatedByID       string
	CreatedByUsername string
	Reason            string
}

func (q *Queries) ListFeeRates(ctx context.Context, arg ListFeeRatesParams) ([]ListFeeRatesRow, error) {
	rows, err := q.db.Query(ctx, listFeeRates, arg.AuditTargetType, arg.AuditAction, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeeRatesRow
	for rows.Next() {
		var i ListFeeRatesRow
		if err := rows.Scan(
			&i.Version,
			&i.FeeRateNano,
			&i.CreatedAt,
			&i.CreatedByID,
			&i.CreatedByUsername,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFeeRates = `-- name: LockFeeRates :exec
LOCK TABLE api_fee_rates IN SHARE ROW EXCLUSIVE MODE
`

func (q *Queries) LockFeeRates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockFeeRates)
	return err
}
