// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package auditpg

import (
	"context"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (actor_account_id, action, target_type, target_id, reason, details)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditEventParams struct {
	ActorAccountID *string
	Action         string
	TargetType     string
	TargetID       string
	Reason         string
	Details        []byte
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ActorAccountID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.Details,
	)
	return err
}
