// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package observepg

import (
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

type Call struct {
	ID                    string
	AccountID             string
	ApiKeyID              *string
	ModelID               *string
	RequestedModel        string
	Format                string
	Stream                bool
	Tag                   *string
	ClientUserAgent       *string
	RoutingMode           *string
	RoutingSource         *string
	Outcome               string
	FinalChannelID        *string
	Attempts              []byte
	InputTokens           int64
	OutputTokens          int64
	CacheWriteTokens      int64
	CacheReadTokens       int64
	PriceSnapshot         []byte
	CostNano              money.Amount
	FeeNano               money.Amount
	TtftMs                *int32
	DurationMs            *int32
	OutputTokensPerSecond *float64
	InterTokenP50Ms       *int32
	InterTokenP95Ms       *int32
	ResponseBytes         *int64
	UpstreamResponseID    *string
	LedgerTxID            *string
	CreatedAt             time.Time
	CompletedAt           *time.Time
}
