// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package forumpg

import (
	"time"
)

type ForumAttachment struct {
	ID        string
	OwnerID   string
	TopicID   *string
	ReplyID   *string
	Name      string
	MediaType string
	Inline    bool
	Size      int64
	Data      []byte
	CreatedAt time.Time
}

type ForumBoard struct {
	ID          string
	Name        string
	Description string
	SortOrder   int32
	CreatedAt   time.Time
}

type ForumReply struct {
	ID        string
	TopicID   string
	AuthorID  string
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ForumTopic struct {
	ID        string
	Kind      string
	BoardID   *string
	AuthorID  string
	Title     string
	Body      string
	Status    *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
