// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package forumpg

import (
	"context"
	"time"
)

const bindAttachment = `-- name: BindAttachment :exec
UPDATE forum_attachments SET topic_id=$2,reply_id=$3 WHERE id=$1
`

type BindAttachmentParams struct {
	ID      string
	TopicID *string
	ReplyID *string
}

func (q *Queries) BindAttachment(ctx context.Context, arg BindAttachmentParams) error {
	_, err := q.db.Exec(ctx, bindAttachment, arg.ID, arg.TopicID, arg.ReplyID)
	return err
}

const cleanupAttachments = `-- name: CleanupAttachments :execrows
DELETE FROM forum_attachments WHERE topic_id IS NULL AND created_at < now()-interval '24 hours'
`

func (q *Queries) CleanupAttachments(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupAttachments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countReplies = `-- name: CountReplies :one
SELECT count(*) FROM forum_replies WHERE topic_id=$1
`

func (q *Queries) CountReplies(ctx context.Context, topicID string) (int64, error) {
	row := q.db.QueryRow(ctx, countReplies, topicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTopics = `-- name: CountTopics :one
SELECT count(*) FROM forum_topics t
WHERE t.kind=$1 AND (t.kind='discussion' OR t.author_id=$2 OR $3::boolean)
AND ($4::uuid IS NULL OR t.board_id=$4)
AND ($5::text='' OR strpos(lower(t.title || E'\n' || t.body),lower($5))>0)
`

type CountTopicsParams struct {
	Kind    string
	ActorID string
	IsAdmin bool
	BoardID *string
	Search  string
}

func (q *Queries) CountTopics(ctx context.Context, arg CountTopicsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTopics,
		arg.Kind,
		arg.ActorID,
		arg.IsAdmin,
		arg.BoardID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO forum_attachments(owner_id,name,media_type,inline,size,data) VALUES($1,$2,$3,$4,$5,$6)
RETURNING id,owner_id,topic_id,reply_id,name,media_type,inline,size,created_at
`

type CreateAttachmentParams struct {
	OwnerID   string
	Name      string
	MediaType string
	Inline    bool
	Size      int64
	Data      []byte
}

type CreateAttachmentRow struct {
	ID        string
	OwnerID   string
	TopicID   *string
	ReplyID   *string
	Name      string
	MediaType string
	Inline    bool
	Size      int64
	CreatedAt time.Time
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.OwnerID,
		arg.Name,
		arg.MediaType,
		arg.Inline,
		arg.Size,
		arg.Data,
	)
	var i CreateAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TopicID,
		&i.ReplyID,
		&i.Name,
		&i.MediaType,
		&i.Inline,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO forum_boards(name,description,sort_order) VALUES($1,$2,$3) RETURNING id, name, description, sort_order, created_at
`

type CreateBoardParams struct {
	Name        string
	Description string
	SortOrder   int32
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (ForumBoard, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Name, arg.Description, arg.SortOrder)
	var i ForumBoard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createReply = `-- name: CreateReply :one
INSERT INTO forum_replies(topic_id,author_id,body) VALUES($1,$2,$3) RETURNING id, topic_id, author_id, body, created_at, updated_at
`

type CreateReplyParams struct {
	TopicID  string
	AuthorID string
	Body     string
}

func (q *Queries) CreateReply(ctx context.Context, arg CreateReplyParams) (ForumReply, error) {
	row := q.db.QueryRow(ctx, createReply, arg.TopicID, arg.AuthorID, arg.Body)
	var i ForumReply
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO forum_topics(kind,board_id,author_id,title,body,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING id, kind, board_id, author_id, title, body, status, created_at, updated_at
`

type CreateTopicParams struct {
	Kind     string
	BoardID  *string
	AuthorID string
	Title    string
	Body     string
	Status   *string
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (ForumTopic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.Kind,
		arg.BoardID,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.Status,
	)
	var i ForumTopic
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.BoardID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :execrows
DELETE FROM forum_boards WHERE id=$1
`

func (q *Queries) DeleteBoard(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRemovedAttachments = `-- name: DeleteRemovedAttachments :exec
DELETE FROM forum_attachments WHERE topic_id=$1 AND reply_id IS NOT DISTINCT FROM $2::uuid AND NOT(id=ANY($3::uuid[]))
`

type DeleteRemovedAttachmentsParams struct {
	TopicID *string
	ReplyID *string
	KeepIds []string
}

func (q *Queries) DeleteRemovedAttachments(ctx context.Context, arg DeleteRemovedAttachmentsParams) error {
	_, err := q.db.Exec(ctx, deleteRemovedAttachments, arg.TopicID, arg.ReplyID, arg.KeepIds)
	return err
}

const deleteReply = `-- name: DeleteReply :exec
DELETE FROM forum_replies WHERE id=$1
`

func (q *Queries) DeleteReply(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteReply, id)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM forum_topics WHERE id=$1
`

func (q *Queries) DeleteTopic(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, owner_id, topic_id, reply_id, name, media_type, inline, size, data, created_at FROM forum_attachments WHERE id=$1
`

func (q *Queries) GetAttachment(ctx context.Context, id string) (ForumAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i ForumAttachment
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TopicID,
		&i.ReplyID,
		&i.Name,
		&i.MediaType,
		&i.Inline,
		&i.Size,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getReply = `-- name: GetReply :one
SELECT r.id, r.topic_id, r.author_id, r.body, r.created_at, r.updated_at,a.display_name FROM forum_replies r JOIN accounts a ON a.id=r.author_id WHERE r.id=$1
`

type GetReplyRow struct {
	ForumReply  ForumReply
	DisplayName string
}

func (q *Queries) GetReply(ctx context.Context, id string) (GetReplyRow, error) {
	row := q.db.QueryRow(ctx, getReply, id)
	var i GetReplyRow
	err := row.Scan(
		&i.ForumReply.ID,
		&i.ForumReply.TopicID,
		&i.ForumReply.AuthorID,
		&i.ForumReply.Body,
		&i.ForumReply.CreatedAt,
		&i.ForumReply.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const getTopic = `-- name: GetTopic :one
SELECT t.id, t.kind, t.board_id, t.author_id, t.title, t.body, t.status, t.created_at, t.updated_at, a.display_name, (SELECT count(*) FROM forum_replies r WHERE r.topic_id=t.id)::bigint AS reply_count
FROM forum_topics t JOIN accounts a ON a.id=t.author_id WHERE t.id=$1
`

type GetTopicRow struct {
	ForumTopic  ForumTopic
	DisplayName string
	ReplyCount  int64
}

func (q *Queries) GetTopic(ctx context.Context, id string) (GetTopicRow, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i GetTopicRow
	err := row.Scan(
		&i.ForumTopic.ID,
		&i.ForumTopic.Kind,
		&i.ForumTopic.BoardID,
		&i.ForumTopic.AuthorID,
		&i.ForumTopic.Title,
		&i.ForumTopic.Body,
		&i.ForumTopic.Status,
		&i.ForumTopic.CreatedAt,
		&i.ForumTopic.UpdatedAt,
		&i.DisplayName,
		&i.ReplyCount,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id,owner_id,topic_id,reply_id,name,media_type,inline,size,created_at FROM forum_attachments
WHERE topic_id=$1 AND reply_id IS NOT DISTINCT FROM $2::uuid ORDER BY created_at,id
`

type ListAttachmentsParams struct {
	TopicID *string
	ReplyID *string
}

type ListAttachmentsRow struct {
	ID        string
	OwnerID   string
	TopicID   *string
	ReplyID   *string
	Name      string
	MediaType string
	Inline    bool
	Size      int64
	CreatedAt time.Time
}

func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments, arg.TopicID, arg.ReplyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsRow
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.TopicID,
			&i.ReplyID,
			&i.Name,
			&i.MediaType,
			&i.Inline,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoards = `-- name: ListBoards :many
SELECT id, name, description, sort_order, created_at FROM forum_boards ORDER BY sort_order, name, id
`

func (q *Queries) ListBoards(ctx context.Context) ([]ForumBoard, error) {
	rows, err := q.db.Query(ctx, listBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForumBoard
	for rows.Next() {
		var i ForumBoard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT r.id, r.topic_id, r.author_id, r.body, r.created_at, r.updated_at,a.display_name FROM forum_replies r JOIN accounts a ON a.id=r.author_id
WHERE r.topic_id=$1 ORDER BY r.created_at,r.id LIMIT $3 OFFSET $2
`

type ListRepliesParams struct {
	TopicID    string
	PageOffset int32
	PageLimit  int32
}

type ListRepliesRow struct {
	ForumReply  ForumReply
	DisplayName string
}

func (q *Queries) ListReplies(ctx context.Context, arg ListRepliesParams) ([]ListRepliesRow, error) {
	rows, err := q.db.Query(ctx, listReplies, arg.TopicID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepliesRow
	for rows.Next() {
		var i ListRepliesRow
		if err := rows.Scan(
			&i.ForumReply.ID,
			&i.ForumReply.TopicID,
			&i.ForumReply.AuthorID,
			&i.ForumReply.Body,
			&i.ForumReply.CreatedAt,
			&i.ForumReply.UpdatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many
SELECT t.id, t.kind, t.board_id, t.author_id, t.title, t.body, t.status, t.created_at, t.updated_at, a.display_name, (SELECT count(*) FROM forum_replies r WHERE r.topic_id=t.id)::bigint AS reply_count
FROM forum_topics t JOIN accounts a ON a.id=t.author_id
WHERE t.kind=$1 AND (t.kind='discussion' OR t.author_id=$2 OR $3::boolean)
AND ($4::uuid IS NULL OR t.board_id=$4)
AND ($5::text='' OR strpos(lower(t.title || E'\n' || t.body),lower($5))>0)
ORDER BY t.created_at DESC,t.id DESC LIMIT $7 OFFSET $6
`

type ListTopicsParams struct {
	Kind       string
	ActorID    string
	IsAdmin    bool
	BoardID    *string
	Search     string
	PageOffset int32
	PageLimit  int32
}

type ListTopicsRow struct {
	ForumTopic  ForumTopic
	DisplayName string
	ReplyCount  int64
}

func (q *Queries) ListTopics(ctx context.Context, arg ListTopicsParams) ([]ListTopicsRow, error) {
	rows, err := q.db.Query(ctx, listTopics,
		arg.Kind,
		arg.ActorID,
		arg.IsAdmin,
		arg.BoardID,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopicsRow
	for rows.Next() {
		var i ListTopicsRow
		if err := rows.Scan(
			&i.ForumTopic.ID,
			&i.ForumTopic.Kind,
			&i.ForumTopic.BoardID,
			&i.ForumTopic.AuthorID,
			&i.ForumTopic.Title,
			&i.ForumTopic.Body,
			&i.ForumTopic.Status,
			&i.ForumTopic.CreatedAt,
			&i.ForumTopic.UpdatedAt,
			&i.DisplayName,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAttachment = `-- name: LockAttachment :one
SELECT id,owner_id,topic_id,reply_id,name,media_type,inline,size,created_at FROM forum_attachments WHERE id=$1 FOR UPDATE
`

type LockAttachmentRow struct {
	ID        string
	OwnerID   string
	TopicID   *string
	ReplyID   *string
	Name      string
	MediaType string
	Inline    bool
	Size      int64
	CreatedAt time.Time
}

func (q *Queries) LockAttachment(ctx context.Context, id string) (LockAttachmentRow, error) {
	row := q.db.QueryRow(ctx, lockAttachment, id)
	var i LockAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TopicID,
		&i.ReplyID,
		&i.Name,
		&i.MediaType,
		&i.Inline,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const lockOwner = `-- name: LockOwner :one
SELECT id FROM accounts WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockOwner, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const lockTopic = `-- name: LockTopic :one
SELECT id, kind, board_id, author_id, title, body, status, created_at, updated_at FROM forum_topics WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockTopic(ctx context.Context, id string) (ForumTopic, error) {
	row := q.db.QueryRow(ctx, lockTopic, id)
	var i ForumTopic
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.BoardID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE forum_boards SET name=$2,description=$3,sort_order=$4 WHERE id=$1 RETURNING id, name, description, sort_order, created_at
`

type UpdateBoardParams struct {
	ID          string
	Name        string
	Description string
	SortOrder   int32
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (ForumBoard, error) {
	row := q.db.QueryRow(ctx, updateBoard,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
	)
	var i ForumBoard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateReply = `-- name: UpdateReply :exec
UPDATE forum_replies SET body=$2,updated_at=now() WHERE id=$1
`

type UpdateReplyParams struct {
	ID   string
	Body string
}

func (q *Queries) UpdateReply(ctx context.Context, arg UpdateReplyParams) error {
	_, err := q.db.Exec(ctx, updateReply, arg.ID, arg.Body)
	return err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE forum_topics SET status=$2,updated_at=now() WHERE id=$1
`

type UpdateStatusParams struct {
	ID     string
	Status *string
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.Exec(ctx, updateStatus, arg.ID, arg.Status)
	return err
}

const updateTopic = `-- name: UpdateTopic :exec
UPDATE forum_topics SET title=$2,body=$3,updated_at=now() WHERE id=$1
`

type UpdateTopicParams struct {
	ID    string
	Title string
	Body  string
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) error {
	_, err := q.db.Exec(ctx, updateTopic, arg.ID, arg.Title, arg.Body)
	return err
}

const usedBytes = `-- name: UsedBytes :one
SELECT COALESCE(sum(size),0)::bigint FROM forum_attachments WHERE owner_id=$1
`

func (q *Queries) UsedBytes(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, usedBytes, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
