// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package opspg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const countDisputedTrades = `-- name: CountDisputedTrades :one
SELECT count(*)::bigint FROM c2c_trades WHERE status = 'disputed'
`

func (q *Queries) CountDisputedTrades(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDisputedTrades)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countHardViolations = `-- name: CountHardViolations :one
SELECT
	(SELECT count(*) FROM api_calls c LEFT JOIN api_call_settlements s ON s.call_id = c.id
		WHERE c.status = 'succeeded' AND s.call_id IS NULL)::bigint AS without_settlement,
	(SELECT count(*) FROM api_call_settlements s
		WHERE (s.kind = 'captured' AND NOT EXISTS (SELECT 1 FROM ledger_transactions t WHERE t.id = s.capture_transaction_id))
			OR (s.kind = 'self_usage' AND NOT EXISTS (SELECT 1 FROM ledger_transactions t WHERE t.id = s.self_transaction_id)))::bigint AS without_ledger_tx,
	(SELECT count(*) FROM c2c_orders WHERE total_nano <> available_nano + allocated_nano + settled_nano + closed_nano)::bigint AS quantity_violations,
	(SELECT count(*) FROM c2c_orders o JOIN ledger_holds h ON h.id = o.parent_hold_id
		WHERE o.status IN ('open', 'allocated')
			AND h.remaining_nano <> o.available_nano + o.allocated_nano)::bigint AS hold_violations
`

type CountHardViolationsRow struct {
	WithoutSettlement  int64
	WithoutLedgerTx    int64
	QuantityViolations int64
	HoldViolations     int64
}

// 硬异常的固定口径；OpsAnomalies 与巡检共用。
func (q *Queries) CountHardViolations(ctx context.Context) (CountHardViolationsRow, error) {
	row := q.db.QueryRow(ctx, countHardViolations)
	var i CountHardViolationsRow
	err := row.Scan(
		&i.WithoutSettlement,
		&i.WithoutLedgerTx,
		&i.QuantityViolations,
		&i.HoldViolations,
	)
	return i, err
}

const getAPIFunnel = `-- name: GetAPIFunnel :one
SELECT
	count(*) FILTER (WHERE status = 'rejected')::bigint AS rejected,
	count(*) FILTER (WHERE upstream_attempt_count > 0)::bigint AS reached,
	count(*) FILTER (WHERE status = 'succeeded')::bigint AS succeeded,
	count(*) FILTER (WHERE status = 'failed')::bigint AS failed,
	count(*) FILTER (WHERE status = 'incomplete')::bigint AS incomplete,
	count(*) FILTER (WHERE status = 'cancelled')::bigint AS cancelled,
	count(*) FILTER (WHERE upstream_attempt_count > 0 AND status IN ('succeeded', 'failed', 'incomplete', 'cancelled'))::bigint AS terminal
FROM api_calls WHERE created_at >= $1 AND created_at < $2
`

type GetAPIFunnelParams struct {
	FromAt time.Time
	ToAt   time.Time
}

type GetAPIFunnelRow struct {
	Rejected   int64
	Reached    int64
	Succeeded  int64
	Failed     int64
	Incomplete int64
	Cancelled  int64
	Terminal   int64
}

func (q *Queries) GetAPIFunnel(ctx context.Context, arg GetAPIFunnelParams) (GetAPIFunnelRow, error) {
	row := q.db.QueryRow(ctx, getAPIFunnel, arg.FromAt, arg.ToAt)
	var i GetAPIFunnelRow
	err := row.Scan(
		&i.Rejected,
		&i.Reached,
		&i.Succeeded,
		&i.Failed,
		&i.Incomplete,
		&i.Cancelled,
		&i.Terminal,
	)
	return i, err
}

const getAttemptStats = `-- name: GetAttemptStats :one
SELECT count(*)::bigint AS attempts,
	(count(*) FILTER (WHERE a.status = 'succeeded'))::bigint AS succeeded_attempts,
	COALESCE((avg(a.ttft_milliseconds) FILTER (WHERE a.status = 'succeeded' AND a.ttft_milliseconds IS NOT NULL))::text, '')::text AS avg_ttft,
	COALESCE((avg(a.tokens_per_second_nano) FILTER (WHERE a.status = 'succeeded' AND a.tokens_per_second_nano IS NOT NULL))::text, '')::text AS avg_tps
FROM api_call_attempts a
JOIN api_calls c ON c.id = a.call_id
WHERE c.created_at >= $1 AND c.created_at < $2
`

type GetAttemptStatsParams struct {
	FromAt time.Time
	ToAt   time.Time
}

type GetAttemptStatsRow struct {
	Attempts          int64
	SucceededAttempts int64
	AvgTtft           string
	AvgTps            string
}

func (q *Queries) GetAttemptStats(ctx context.Context, arg GetAttemptStatsParams) (GetAttemptStatsRow, error) {
	row := q.db.QueryRow(ctx, getAttemptStats, arg.FromAt, arg.ToAt)
	var i GetAttemptStatsRow
	err := row.Scan(
		&i.Attempts,
		&i.SucceededAttempts,
		&i.AvgTtft,
		&i.AvgTps,
	)
	return i, err
}

const getC2CQuote = `-- name: GetC2CQuote :one
WITH quote AS (
	SELECT
		(SELECT unit_price_fen FROM c2c_trades WHERE status = 'released_to_buyer' ORDER BY resolved_at DESC, id DESC LIMIT 1) AS last_price,
		(SELECT min(unit_price_fen) FROM c2c_orders WHERE status IN ('open', 'allocated') AND available_nano > 0) AS best_ask
)
SELECT COALESCE(last_price, 0)::bigint AS last_price, (last_price IS NOT NULL)::boolean AS has_last_price,
	COALESCE(best_ask, 0)::bigint AS best_ask, (best_ask IS NOT NULL)::boolean AS has_best_ask
FROM quote
`

type GetC2CQuoteRow struct {
	LastPrice    int64
	HasLastPrice bool
	BestAsk      int64
	HasBestAsk   bool
}

func (q *Queries) GetC2CQuote(ctx context.Context) (GetC2CQuoteRow, error) {
	row := q.db.QueryRow(ctx, getC2CQuote)
	var i GetC2CQuoteRow
	err := row.Scan(
		&i.LastPrice,
		&i.HasLastPrice,
		&i.BestAsk,
		&i.HasBestAsk,
	)
	return i, err
}

const getConcentration = `-- name: GetConcentration :one
WITH pos AS (
	SELECT posted_balance_nano FROM ledger_accounts WHERE kind = 'user' AND posted_balance_nano > 0
), totals AS (
	SELECT count(*) AS positive_count,
		COALESCE(sum(posted_balance_nano), 0)::numeric AS total,
		max(posted_balance_nano)::numeric AS top
	FROM pos
), top5 AS (
	SELECT COALESCE(sum(posted_balance_nano), 0)::numeric AS top_sum
	FROM (SELECT posted_balance_nano FROM pos ORDER BY posted_balance_nano DESC LIMIT 5) t
), hhi AS (
	SELECT sum((posted_balance_nano::numeric / NULLIF(totals.total, 0)) * (posted_balance_nano::numeric / NULLIF(totals.total, 0))) AS value
	FROM pos CROSS JOIN totals
)
SELECT totals.positive_count::bigint AS positive_count,
	totals.total::text AS total_positive,
	(CASE WHEN totals.total > 0 THEN round(totals.top / totals.total, 6)::text ELSE '' END)::text AS top1_share,
	(CASE WHEN totals.total > 0 THEN round(top5.top_sum / totals.total, 6)::text ELSE '' END)::text AS top5_share,
	(CASE WHEN totals.total > 0 THEN round(hhi.value, 6)::text ELSE '' END)::text AS hhi
FROM totals CROSS JOIN top5 CROSS JOIN hhi
`

type GetConcentrationRow struct {
	PositiveCount int64
	TotalPositive string
	Top1Share     string
	Top5Share     string
	Hhi           string
}

// sqlc 不支持标量子查询里的嵌套 CTE，故展开为同级 CTE；total = 0 时三个占比为 NULL。
func (q *Queries) GetConcentration(ctx context.Context) (GetConcentrationRow, error) {
	row := q.db.QueryRow(ctx, getConcentration)
	var i GetConcentrationRow
	err := row.Scan(
		&i.PositiveCount,
		&i.TotalPositive,
		&i.Top1Share,
		&i.Top5Share,
		&i.Hhi,
	)
	return i, err
}

const getConsumptionWindow = `-- name: GetConsumptionWindow :one
SELECT
	COALESCE(sum(s.provider_charge_nano) FILTER (WHERE s.kind = 'captured'), 0)::bigint AS captured_charge,
	COALESCE(sum(s.platform_fee_nano) FILTER (WHERE s.kind = 'captured'), 0)::bigint AS captured_fee,
	COALESCE(sum(s.provider_charge_nano) FILTER (WHERE s.kind = 'self_usage'), 0)::bigint AS self_charge
FROM api_call_settlements s
JOIN api_calls c ON c.id = s.call_id
WHERE c.created_at >= $1 AND c.created_at < $2
`

type GetConsumptionWindowParams struct {
	FromAt time.Time
	ToAt   time.Time
}

type GetConsumptionWindowRow struct {
	CapturedCharge int64
	CapturedFee    int64
	SelfCharge     int64
}

func (q *Queries) GetConsumptionWindow(ctx context.Context, arg GetConsumptionWindowParams) (GetConsumptionWindowRow, error) {
	row := q.db.QueryRow(ctx, getConsumptionWindow, arg.FromAt, arg.ToAt)
	var i GetConsumptionWindowRow
	err := row.Scan(&i.CapturedCharge, &i.CapturedFee, &i.SelfCharge)
	return i, err
}

const insertInspection = `-- name: InsertInspection :one
INSERT INTO ops_inspections (
	inspection_version, triggered_by,
	zero_sum_ok, projection_ok, call_settlement_ok, c2c_consistency_ok,
	zero_sum_difference_nano, posted_projection_difference_nano, asset_projection_difference_nano, authorization_projection_difference_nano,
	successful_calls_without_settlement, settlements_without_ledger_transaction,
	c2c_quantity_violations, c2c_hold_violations, notes
) VALUES (
	$1, $2,
	$3, $4, $5, $6,
	$7, $8, $9, $10,
	$11, $12,
	$13, $14, '{}'
)
RETURNING id::text AS id, inspection_version, triggered_by, zero_sum_ok, projection_ok, call_settlement_ok, c2c_consistency_ok,
	zero_sum_difference_nano::text AS zero_sum_difference, posted_projection_difference_nano::text AS posted_projection_difference,
	asset_projection_difference_nano::text AS asset_projection_difference, authorization_projection_difference_nano::text AS authorization_projection_difference,
	successful_calls_without_settlement, settlements_without_ledger_transaction, c2c_quantity_violations, c2c_hold_violations, checked_at
`

type InsertInspectionParams struct {
	InspectionVersion                     string
	TriggeredBy                           string
	ZeroSumOk                             bool
	ProjectionOk                          bool
	CallSettlementOk                      bool
	C2cConsistencyOk                      bool
	ZeroSumDifferenceNano                 money.Amount
	PostedProjectionDifferenceNano        money.Amount
	AssetProjectionDifferenceNano         money.Amount
	AuthorizationProjectionDifferenceNano money.Amount
	SuccessfulCallsWithoutSettlement      int64
	SettlementsWithoutLedgerTransaction   int64
	C2cQuantityViolations                 int64
	C2cHoldViolations                     int64
}

type InsertInspectionRow struct {
	ID                                  string
	InspectionVersion                   string
	TriggeredBy                         string
	ZeroSumOk                           bool
	ProjectionOk                        bool
	CallSettlementOk                    bool
	C2cConsistencyOk                    bool
	ZeroSumDifference                   string
	PostedProjectionDifference          string
	AssetProjectionDifference           string
	AuthorizationProjectionDifference   string
	SuccessfulCallsWithoutSettlement    int64
	SettlementsWithoutLedgerTransaction int64
	C2cQuantityViolations               int64
	C2cHoldViolations                   int64
	CheckedAt                           time.Time
}

func (q *Queries) InsertInspection(ctx context.Context, arg InsertInspectionParams) (InsertInspectionRow, error) {
	row := q.db.QueryRow(ctx, insertInspection,
		arg.InspectionVersion,
		arg.TriggeredBy,
		arg.ZeroSumOk,
		arg.ProjectionOk,
		arg.CallSettlementOk,
		arg.C2cConsistencyOk,
		arg.ZeroSumDifferenceNano,
		arg.PostedProjectionDifferenceNano,
		arg.AssetProjectionDifferenceNano,
		arg.AuthorizationProjectionDifferenceNano,
		arg.SuccessfulCallsWithoutSettlement,
		arg.SettlementsWithoutLedgerTransaction,
		arg.C2cQuantityViolations,
		arg.C2cHoldViolations,
	)
	var i InsertInspectionRow
	err := row.Scan(
		&i.ID,
		&i.InspectionVersion,
		&i.TriggeredBy,
		&i.ZeroSumOk,
		&i.ProjectionOk,
		&i.CallSettlementOk,
		&i.C2cConsistencyOk,
		&i.ZeroSumDifference,
		&i.PostedProjectionDifference,
		&i.AssetProjectionDifference,
		&i.AuthorizationProjectionDifference,
		&i.SuccessfulCallsWithoutSettlement,
		&i.SettlementsWithoutLedgerTransaction,
		&i.C2cQuantityViolations,
		&i.C2cHoldViolations,
		&i.CheckedAt,
	)
	return i, err
}

const listC2COrderStatusCounts = `-- name: ListC2COrderStatusCounts :many
SELECT status, count(*)::bigint AS count FROM c2c_orders GROUP BY status ORDER BY status
`

type ListC2COrderStatusCountsRow struct {
	Status string
	Count  int64
}

func (q *Queries) ListC2COrderStatusCounts(ctx context.Context) ([]ListC2COrderStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, listC2COrderStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListC2COrderStatusCountsRow
	for rows.Next() {
		var i ListC2COrderStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listC2CTradeStatusCounts = `-- name: ListC2CTradeStatusCounts :many
SELECT status, count(*)::bigint AS count FROM c2c_trades
WHERE created_at >= $1 AND created_at < $2 GROUP BY status ORDER BY status
`

type ListC2CTradeStatusCountsParams struct {
	FromAt time.Time
	ToAt   time.Time
}

type ListC2CTradeStatusCountsRow struct {
	Status string
	Count  int64
}

func (q *Queries) ListC2CTradeStatusCounts(ctx context.Context, arg ListC2CTradeStatusCountsParams) ([]ListC2CTradeStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, listC2CTradeStatusCounts, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListC2CTradeStatusCountsRow
	for rows.Next() {
		var i ListC2CTradeStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInspections = `-- name: ListInspections :many
SELECT id::text AS id, inspection_version, triggered_by, zero_sum_ok, projection_ok, call_settlement_ok, c2c_consistency_ok,
	zero_sum_difference_nano::text AS zero_sum_difference, posted_projection_difference_nano::text AS posted_projection_difference,
	asset_projection_difference_nano::text AS asset_projection_difference, authorization_projection_difference_nano::text AS authorization_projection_difference,
	successful_calls_without_settlement, settlements_without_ledger_transaction, c2c_quantity_violations, c2c_hold_violations, checked_at
FROM ops_inspections ORDER BY checked_at DESC, id DESC LIMIT $1
`

type ListInspectionsRow struct {
	ID                                  string
	InspectionVersion                   string
	TriggeredBy                         string
	ZeroSumOk                           bool
	ProjectionOk                        bool
	CallSettlementOk                    bool
	C2cConsistencyOk                    bool
	ZeroSumDifference                   string
	PostedProjectionDifference          string
	AssetProjectionDifference           string
	AuthorizationProjectionDifference   string
	SuccessfulCallsWithoutSettlement    int64
	SettlementsWithoutLedgerTransaction int64
	C2cQuantityViolations               int64
	C2cHoldViolations                   int64
	CheckedAt                           time.Time
}

func (q *Queries) ListInspections(ctx context.Context, rowLimit int32) ([]ListInspectionsRow, error) {
	rows, err := q.db.Query(ctx, listInspections, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInspectionsRow
	for rows.Next() {
		var i ListInspectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.InspectionVersion,
			&i.TriggeredBy,
			&i.ZeroSumOk,
			&i.ProjectionOk,
			&i.CallSettlementOk,
			&i.C2cConsistencyOk,
			&i.ZeroSumDifference,
			&i.PostedProjectionDifference,
			&i.AssetProjectionDifference,
			&i.AuthorizationProjectionDifference,
			&i.SuccessfulCallsWithoutSettlement,
			&i.SettlementsWithoutLedgerTransaction,
			&i.C2cQuantityViolations,
			&i.C2cHoldViolations,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNegativeBalances = `-- name: ListNegativeBalances :many

WITH neg AS (
	SELECT la.id, la.identity_account_id, la.posted_balance_nano, a.username, a.credit_limit_nano, a.credit_frozen
	FROM ledger_accounts la
	JOIN accounts a ON a.id = la.identity_account_id
	WHERE la.kind = 'user' AND la.posted_balance_nano < 0
), entries AS (
	SELECT e.ledger_account_id, e.created_at, e.amount_nano,
		sum(e.amount_nano) OVER (PARTITION BY e.ledger_account_id ORDER BY e.created_at, e.id
			ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS suffix_sum
	FROM ledger_entries e
	JOIN neg n ON n.id = e.ledger_account_id
), streak AS (
	SELECT n.id, n.posted_balance_nano, n.username, n.credit_limit_nano, n.credit_frozen,
		min(e.created_at) FILTER (WHERE e.suffix_sum < 0) AS negative_since,
		max(e.created_at) AS last_activity
	FROM neg n
	LEFT JOIN entries e ON e.ledger_account_id = n.id
	GROUP BY n.id, n.posted_balance_nano, n.username, n.credit_limit_nano, n.credit_frozen
)
SELECT id::text AS id, username, posted_balance_nano,
	COALESCE(negative_since, 'epoch'::timestamptz)::timestamptz AS negative_since,
	(negative_since IS NOT NULL)::boolean AS has_negative_since,
	COALESCE(last_activity, 'epoch'::timestamptz)::timestamptz AS last_activity,
	(last_activity IS NOT NULL)::boolean AS has_last_activity,
	-- 账本时间戳来自数据库时钟，闲置天数也用它度量；后端时钟落后时不得得到 -1。
	COALESCE(greatest(0, floor(extract(epoch FROM now() - last_activity) / 86400)), 0)::bigint AS inactive_days,
	credit_limit_nano, credit_frozen
FROM streak ORDER BY posted_balance_nano ASC LIMIT 200
`

type ListNegativeBalancesRow struct {
	ID                string
	Username          string
	PostedBalanceNano int64
	NegativeSince     time.Time
	HasNegativeSince  bool
	LastActivity      time.Time
	HasLastActivity   bool
	InactiveDays      int64
	CreditLimitNano   int64
	CreditFrozen      bool
}

// 运营领域全部 SQL：只读聚合（跨账本、调用、渠道与 C2C 表直接 JOIN）与巡检写入。
// 时间窗口由调用方以 UTC 显式传入；闲置天数使用数据库时钟 now()，不得为负（#107）。
// sqlc 不推断聚合/子查询的可空性，故空值以哨兵值加 has_* 标志表达，Go 侧还原为 NULL 语义。
func (q *Queries) ListNegativeBalances(ctx context.Context) ([]ListNegativeBalancesRow, error) {
	rows, err := q.db.Query(ctx, listNegativeBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNegativeBalancesRow
	for rows.Next() {
		var i ListNegativeBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PostedBalanceNano,
			&i.NegativeSince,
			&i.HasNegativeSince,
			&i.LastActivity,
			&i.HasLastActivity,
			&i.InactiveDays,
			&i.CreditLimitNano,
			&i.CreditFrozen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderIncome = `-- name: ListProviderIncome :many
WITH income AS (
	SELECT
		s.provider_account_id AS account_id,
		COALESCE(sum(s.provider_charge_nano) FILTER (WHERE s.kind IN ('captured', 'self_usage')), 0)::bigint AS total_income_nano,
		COALESCE(sum(s.provider_charge_nano) FILTER (WHERE s.kind = 'captured'), 0)::bigint AS other_consumer_income_nano,
		COALESCE(sum(s.provider_charge_nano) FILTER (WHERE s.kind = 'self_usage'), 0)::bigint AS own_usage_income_nano
	FROM api_call_settlements s
	JOIN api_calls c ON c.id = s.call_id
	WHERE c.created_at >= $1 AND c.created_at < $2
		AND s.provider_account_id IS NOT NULL
		AND s.kind IN ('captured', 'self_usage')
	GROUP BY s.provider_account_id
), attempts AS (
	SELECT
		a.provider_account_id AS account_id,
		count(*) FILTER (WHERE a.status IN ('succeeded', 'failed', 'cancelled', 'incomplete')) AS terminal_attempts,
		count(*) FILTER (WHERE a.status = 'succeeded') AS succeeded_attempts
	FROM api_call_attempts a
	WHERE a.started_at >= $1 AND a.started_at < $2
	GROUP BY a.provider_account_id
)
SELECT
	a.id::text AS account_id,
	a.display_name,
	COALESCE(income.total_income_nano, 0)::bigint AS total_income_nano,
	COALESCE(income.other_consumer_income_nano, 0)::bigint AS other_consumer_income_nano,
	COALESCE(income.own_usage_income_nano, 0)::bigint AS own_usage_income_nano,
	COALESCE(attempts.succeeded_attempts, 0)::bigint AS succeeded_attempts,
	COALESCE(attempts.terminal_attempts, 0)::bigint AS terminal_attempts
FROM accounts a
LEFT JOIN income ON income.account_id = a.id
LEFT JOIN attempts ON attempts.account_id = a.id
WHERE COALESCE(income.total_income_nano, 0) > 0
	OR COALESCE(attempts.terminal_attempts, 0) > 0
ORDER BY COALESCE(income.total_income_nano, 0) DESC, a.display_name, a.id
`

type ListProviderIncomeParams struct {
	FromAt time.Time
	ToAt   time.Time
}

type ListProviderIncomeRow struct {
	AccountID               string
	DisplayName             string
	TotalIncomeNano         int64
	OtherConsumerIncomeNano int64
	OwnUsageIncomeNano      int64
	SucceededAttempts       int64
	TerminalAttempts        int64
}

func (q *Queries) ListProviderIncome(ctx context.Context, arg ListProviderIncomeParams) ([]ListProviderIncomeRow, error) {
	rows, err := q.db.Query(ctx, listProviderIncome, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderIncomeRow
	for rows.Next() {
		var i ListProviderIncomeRow
		if err := rows.Scan(
			&i.AccountID,
			&i.DisplayName,
			&i.TotalIncomeNano,
			&i.OtherConsumerIncomeNano,
			&i.OwnUsageIncomeNano,
			&i.SucceededAttempts,
			&i.TerminalAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
