// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package c2cpg

import (
	"time"
)

type C2cPaymentMethod struct {
	ID          string
	OrderID     string
	MethodType  string
	Position    int32
	QrAvailable bool
	KeyID       string
	Nonce       []byte
	Ciphertext  []byte
	CreatedAt   time.Time
}
