// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package c2cpg

import (
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

type C2cOrder struct {
	ID                       string
	SellerID                 string
	TotalNano                money.Amount
	AvailableNano            money.Amount
	InTradeNano              money.Amount
	SoldNano                 money.Amount
	ClosedNano               money.Amount
	UnitPriceFen             int64
	MinPerTradeNano          money.Amount
	MaxPerTradeNano          *money.Amount
	PaymentMethodsCiphertext []byte
	PaymentMethodsNonce      []byte
	PaymentMethodsKeyID      string
	Status                   string
	CreatedAt                time.Time
	UpdatedAt                time.Time
	ClosedAt                 *time.Time
}

type C2cTrade struct {
	ID               string
	OrderID          string
	BuyerID          string
	SellerID         string
	AmountNano       money.Amount
	UnitPriceFen     int64
	TotalFen         int64
	Status           string
	PaymentDeadline  time.Time
	BuyerNote        *string
	DisputeOpenedBy  *string
	BuyerStatement   *string
	SellerStatement  *string
	ResolutionReason *string
	ResolvedBy       *string
	CreatedAt        time.Time
	PaidAt           *time.Time
	ReleasedAt       *time.Time
	CancelledAt      *time.Time
	DisputedAt       *time.Time
	ResolvedAt       *time.Time
	LedgerTxID       *string
}
