// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package c2cpg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const cancelOrder = `-- name: CancelOrder :execrows
UPDATE c2c_orders
SET available_nano = 0, closed_nano = closed_nano + $1,
	status = 'cancelled', cancelled_at = $2, updated_at = $2
WHERE id = $3
`

type CancelOrderParams struct {
	ClosingNano money.Amount
	CancelledAt *time.Time
	ID          string
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOrder, arg.ClosingNano, arg.CancelledAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupDisputeStatements = `-- name: CleanupDisputeStatements :execrows
WITH victims AS (
	SELECT s.id FROM c2c_dispute_statements s
	JOIN c2c_trades t ON t.id = s.trade_id
	WHERE s.deleted_at IS NULL
		AND t.status IN ('released_to_buyer', 'returned_to_seller', 'cancelled', 'expired')
		AND t.resolved_at <= $2
	ORDER BY t.resolved_at, s.id
	LIMIT $3
	FOR UPDATE OF s SKIP LOCKED
)
UPDATE c2c_dispute_statements s
SET key_id = NULL, nonce = NULL, ciphertext = NULL, deleted_at = $1
FROM victims WHERE s.id = victims.id
`

type CleanupDisputeStatementsParams struct {
	DeletedAt  *time.Time
	Cutoff     *time.Time
	BatchLimit int32
}

// 终态成交的争议陈述密文超过保留期后清除。
func (q *Queries) CleanupDisputeStatements(ctx context.Context, arg CleanupDisputeStatementsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupDisputeStatements, arg.DeletedAt, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupPaymentReferences = `-- name: CleanupPaymentReferences :execrows
WITH victims AS (
	SELECT candidate.id FROM c2c_trades candidate
	WHERE candidate.payment_reference_ciphertext IS NOT NULL
		AND candidate.status IN ('released_to_buyer', 'returned_to_seller', 'cancelled', 'expired')
		AND candidate.resolved_at <= $2
	ORDER BY candidate.resolved_at, candidate.id
	LIMIT $3
	FOR UPDATE OF candidate SKIP LOCKED
)
UPDATE c2c_trades t
SET payment_reference_key_id = NULL, payment_reference_nonce = NULL,
	payment_reference_ciphertext = NULL, payment_reference_deleted_at = $1
FROM victims WHERE t.id = victims.id
`

type CleanupPaymentReferencesParams struct {
	DeletedAt  *time.Time
	Cutoff     *time.Time
	BatchLimit int32
}

func (q *Queries) CleanupPaymentReferences(ctx context.Context, arg CleanupPaymentReferencesParams) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupPaymentReferences, arg.DeletedAt, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeCommand = `-- name: CompleteCommand :execrows
UPDATE c2c_commands SET result_payload = $1, completed_at = $2
WHERE actor_key = $3 AND operation = $4 AND idempotency_key = $5
	AND completed_at IS NULL
`

type CompleteCommandParams struct {
	ResultPayload  []byte
	CompletedAt    *time.Time
	ActorKey       string
	Operation      string
	IdempotencyKey string
}

func (q *Queries) CompleteCommand(ctx context.Context, arg CompleteCommandParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCommand,
		arg.ResultPayload,
		arg.CompletedAt,
		arg.ActorKey,
		arg.Operation,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendTradeReview = `-- name: ExtendTradeReview :execrows
UPDATE c2c_trades SET review_due_at = $1, updated_at = $2
WHERE id = $3 AND status = 'disputed'
`

type ExtendTradeReviewParams struct {
	ReviewDueAt *time.Time
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) ExtendTradeReview(ctx context.Context, arg ExtendTradeReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendTradeReview, arg.ReviewDueAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const freezeAccountCredit = `-- name: FreezeAccountCredit :one
UPDATE accounts
SET credit_frozen = true, version = version + 1, updated_at = $1
WHERE id = $2 AND version = $3
RETURNING version
`

type FreezeAccountCreditParams struct {
	UpdatedAt time.Time
	ID        string
	Version   int64
}

func (q *Queries) FreezeAccountCredit(ctx context.Context, arg FreezeAccountCreditParams) (int64, error) {
	row := q.db.QueryRow(ctx, freezeAccountCredit, arg.UpdatedAt, arg.ID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getAccountGate = `-- name: GetAccountGate :one
SELECT status, must_change_password, is_admin, credit_frozen FROM accounts WHERE id = $1
`

type GetAccountGateRow struct {
	Status             string
	MustChangePassword bool
	IsAdmin            bool
	CreditFrozen       bool
}

func (q *Queries) GetAccountGate(ctx context.Context, id string) (GetAccountGateRow, error) {
	row := q.db.QueryRow(ctx, getAccountGate, id)
	var i GetAccountGateRow
	err := row.Scan(
		&i.Status,
		&i.MustChangePassword,
		&i.IsAdmin,
		&i.CreditFrozen,
	)
	return i, err
}

const getCommandForUpdate = `-- name: GetCommandForUpdate :one
SELECT payload_hash, result_payload, completed_at
FROM c2c_commands
WHERE actor_key = $1 AND operation = $2 AND idempotency_key = $3
FOR UPDATE
`

type GetCommandForUpdateParams struct {
	ActorKey       string
	Operation      string
	IdempotencyKey string
}

type GetCommandForUpdateRow struct {
	PayloadHash   []byte
	ResultPayload []byte
	CompletedAt   *time.Time
}

func (q *Queries) GetCommandForUpdate(ctx context.Context, arg GetCommandForUpdateParams) (GetCommandForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCommandForUpdate, arg.ActorKey, arg.Operation, arg.IdempotencyKey)
	var i GetCommandForUpdateRow
	err := row.Scan(&i.PayloadHash, &i.ResultPayload, &i.CompletedAt)
	return i, err
}

const getLatestTradePrice = `-- name: GetLatestTradePrice :one
SELECT unit_price_fen FROM c2c_trades
WHERE status = 'released_to_buyer' ORDER BY resolved_at DESC, id DESC LIMIT 1
`

// 最优卖价取自 ListMarketSellOrders 的首行（按价格排序、过滤条件与盘口一致），
// 这里只需要最新成交价；没有成交时无行。
func (q *Queries) GetLatestTradePrice(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestTradePrice)
	var unit_price_fen int64
	err := row.Scan(&unit_price_fen)
	return unit_price_fen, err
}

const getOrder = `-- name: GetOrder :one


SELECT o.id, o.owner_account_id, owner.display_name AS owner_display_name,
	o.unit_price_fen, o.total_nano, o.available_nano, o.allocated_nano,
	o.settled_nano, o.closed_nano, o.minimum_nano, o.maximum_nano,
	o.status, COALESCE(o.parent_hold_id::text, '')::text AS parent_hold_id, o.created_at, o.updated_at,
	o.cancelled_at,
	((owner.status = 'active' AND NOT owner.must_change_password AND NOT owner.credit_frozen)
		AND o.status = 'open' AND o.available_nano > 0)::boolean AS takeable
FROM c2c_orders o
JOIN accounts owner ON owner.id = o.owner_account_id
WHERE o.id = $1
`

type GetOrderRow struct {
	ID               string
	OwnerAccountID   string
	OwnerDisplayName string
	UnitPriceFen     int64
	TotalNano        money.Amount
	AvailableNano    money.Amount
	AllocatedNano    money.Amount
	SettledNano      money.Amount
	ClosedNano       money.Amount
	MinimumNano      money.Amount
	MaximumNano      money.Amount
	Status           string
	ParentHoldID     string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CancelledAt      *time.Time
	Takeable         bool
}

// C2C 领域全部 SQL。
// 订单与成交的列表必须逐列相同：sqlc 没有片段复用，store.go 靠结构体转换共用一个映射函数
// （GetOrder / GetOrderForUpdate / ListMarketSellOrders / ListOwnerOrders，
// GetTrade / GetTradeForUpdate / ListAccountTrades / ListDisputedTrades）。
// takeable 的判定必须与 GetAccountGate 加 store.go 中 ensureOwnerReady 的口径一致。
// ---------------------------------------------------------------------------
// 订单读取
// ---------------------------------------------------------------------------
func (q *Queries) GetOrder(ctx context.Context, id string) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.OwnerDisplayName,
		&i.UnitPriceFen,
		&i.TotalNano,
		&i.AvailableNano,
		&i.AllocatedNano,
		&i.SettledNano,
		&i.ClosedNano,
		&i.MinimumNano,
		&i.MaximumNano,
		&i.Status,
		&i.ParentHoldID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.Takeable,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT o.id, o.owner_account_id, owner.display_name AS owner_display_name,
	o.unit_price_fen, o.total_nano, o.available_nano, o.allocated_nano,
	o.settled_nano, o.closed_nano, o.minimum_nano, o.maximum_nano,
	o.status, COALESCE(o.parent_hold_id::text, '')::text AS parent_hold_id, o.created_at, o.updated_at,
	o.cancelled_at,
	((owner.status = 'active' AND NOT owner.must_change_password AND NOT owner.credit_frozen)
		AND o.status = 'open' AND o.available_nano > 0)::boolean AS takeable
FROM c2c_orders o
JOIN accounts owner ON owner.id = o.owner_account_id
WHERE o.id = $1
FOR UPDATE OF o
`

type GetOrderForUpdateRow struct {
	ID               string
	OwnerAccountID   string
	OwnerDisplayName string
	UnitPriceFen     int64
	TotalNano        money.Amount
	AvailableNano    money.Amount
	AllocatedNano    money.Amount
	SettledNano      money.Amount
	ClosedNano       money.Amount
	MinimumNano      money.Amount
	MaximumNano      money.Amount
	Status           string
	ParentHoldID     string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CancelledAt      *time.Time
	Takeable         bool
}

func (q *Queries) GetOrderForUpdate(ctx context.Context, id string) (GetOrderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i GetOrderForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.OwnerDisplayName,
		&i.UnitPriceFen,
		&i.TotalNano,
		&i.AvailableNano,
		&i.AllocatedNano,
		&i.SettledNano,
		&i.ClosedNano,
		&i.MinimumNano,
		&i.MaximumNano,
		&i.Status,
		&i.ParentHoldID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.Takeable,
	)
	return i, err
}

const getOrderOwnerID = `-- name: GetOrderOwnerID :one
SELECT owner_account_id FROM c2c_orders WHERE id = $1
`

func (q *Queries) GetOrderOwnerID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getOrderOwnerID, id)
	var owner_account_id string
	err := row.Scan(&owner_account_id)
	return owner_account_id, err
}

const getSelectedPaymentMethod = `-- name: GetSelectedPaymentMethod :one
SELECT pm.id, pm.order_id, pm.method_type, pm.position, pm.qr_available,
	pm.key_id, pm.nonce, pm.ciphertext, pm.created_at
FROM c2c_trades t
JOIN c2c_payment_methods pm ON pm.id = t.selected_payment_method_id
WHERE t.id = $1
`

func (q *Queries) GetSelectedPaymentMethod(ctx context.Context, tradeID string) (C2cPaymentMethod, error) {
	row := q.db.QueryRow(ctx, getSelectedPaymentMethod, tradeID)
	var i C2cPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MethodType,
		&i.Position,
		&i.QrAvailable,
		&i.KeyID,
		&i.Nonce,
		&i.Ciphertext,
		&i.CreatedAt,
	)
	return i, err
}

const getTrade = `-- name: GetTrade :one

SELECT t.id, t.order_id,
	t.buyer_account_id, buyer.display_name AS buyer_display_name,
	t.seller_account_id, seller.display_name AS seller_display_name,
	buyer.credit_frozen AS buyer_credit_frozen, seller.credit_frozen AS seller_credit_frozen,
	t.quantity_nano, t.unit_price_fen, t.fiat_amount_fen, t.status,
	t.hold_id, t.payment_reference_chars,
	COALESCE(t.payment_reference_key_id, '')::text AS payment_reference_key_id,
	COALESCE(t.payment_reference_nonce, ''::bytea)::bytea AS payment_reference_nonce,
	COALESCE(t.payment_reference_ciphertext, ''::bytea)::bytea AS payment_reference_ciphertext,
	t.payment_reference_deleted_at,
	t.payment_deadline, t.review_due_at,
	COALESCE(t.ledger_transaction_id::text, '')::text AS ledger_transaction_id,
	t.created_at, t.updated_at, t.paid_at, t.resolved_at
FROM c2c_trades t
JOIN accounts buyer ON buyer.id = t.buyer_account_id
JOIN accounts seller ON seller.id = t.seller_account_id
WHERE t.id = $1
`

type GetTradeRow struct {
	ID                         string
	OrderID                    string
	BuyerAccountID             string
	BuyerDisplayName           string
	SellerAccountID            string
	SellerDisplayName          string
	BuyerCreditFrozen          bool
	SellerCreditFrozen         bool
	QuantityNano               money.Amount
	UnitPriceFen               int64
	FiatAmountFen              int64
	Status                     string
	HoldID                     string
	PaymentReferenceChars      int32
	PaymentReferenceKeyID      string
	PaymentReferenceNonce      []byte
	PaymentReferenceCiphertext []byte
	PaymentReferenceDeletedAt  *time.Time
	PaymentDeadline            time.Time
	ReviewDueAt                *time.Time
	LedgerTransactionID        string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	PaidAt                     *time.Time
	ResolvedAt                 *time.Time
}

// ---------------------------------------------------------------------------
// 成交读取
// ---------------------------------------------------------------------------
func (q *Queries) GetTrade(ctx context.Context, id string) (GetTradeRow, error) {
	row := q.db.QueryRow(ctx, getTrade, id)
	var i GetTradeRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerAccountID,
		&i.BuyerDisplayName,
		&i.SellerAccountID,
		&i.SellerDisplayName,
		&i.BuyerCreditFrozen,
		&i.SellerCreditFrozen,
		&i.QuantityNano,
		&i.UnitPriceFen,
		&i.FiatAmountFen,
		&i.Status,
		&i.HoldID,
		&i.PaymentReferenceChars,
		&i.PaymentReferenceKeyID,
		&i.PaymentReferenceNonce,
		&i.PaymentReferenceCiphertext,
		&i.PaymentReferenceDeletedAt,
		&i.PaymentDeadline,
		&i.ReviewDueAt,
		&i.LedgerTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getTradeForUpdate = `-- name: GetTradeForUpdate :one
SELECT t.id, t.order_id,
	t.buyer_account_id, buyer.display_name AS buyer_display_name,
	t.seller_account_id, seller.display_name AS seller_display_name,
	buyer.credit_frozen AS buyer_credit_frozen, seller.credit_frozen AS seller_credit_frozen,
	t.quantity_nano, t.unit_price_fen, t.fiat_amount_fen, t.status,
	t.hold_id, t.payment_reference_chars,
	COALESCE(t.payment_reference_key_id, '')::text AS payment_reference_key_id,
	COALESCE(t.payment_reference_nonce, ''::bytea)::bytea AS payment_reference_nonce,
	COALESCE(t.payment_reference_ciphertext, ''::bytea)::bytea AS payment_reference_ciphertext,
	t.payment_reference_deleted_at,
	t.payment_deadline, t.review_due_at,
	COALESCE(t.ledger_transaction_id::text, '')::text AS ledger_transaction_id,
	t.created_at, t.updated_at, t.paid_at, t.resolved_at
FROM c2c_trades t
JOIN accounts buyer ON buyer.id = t.buyer_account_id
JOIN accounts seller ON seller.id = t.seller_account_id
WHERE t.id = $1
FOR UPDATE OF t
`

type GetTradeForUpdateRow struct {
	ID                         string
	OrderID                    string
	BuyerAccountID             string
	BuyerDisplayName           string
	SellerAccountID            string
	SellerDisplayName          string
	BuyerCreditFrozen          bool
	SellerCreditFrozen         bool
	QuantityNano               money.Amount
	UnitPriceFen               int64
	FiatAmountFen              int64
	Status                     string
	HoldID                     string
	PaymentReferenceChars      int32
	PaymentReferenceKeyID      string
	PaymentReferenceNonce      []byte
	PaymentReferenceCiphertext []byte
	PaymentReferenceDeletedAt  *time.Time
	PaymentDeadline            time.Time
	ReviewDueAt                *time.Time
	LedgerTransactionID        string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	PaidAt                     *time.Time
	ResolvedAt                 *time.Time
}

func (q *Queries) GetTradeForUpdate(ctx context.Context, id string) (GetTradeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTradeForUpdate, id)
	var i GetTradeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerAccountID,
		&i.BuyerDisplayName,
		&i.SellerAccountID,
		&i.SellerDisplayName,
		&i.BuyerCreditFrozen,
		&i.SellerCreditFrozen,
		&i.QuantityNano,
		&i.UnitPriceFen,
		&i.FiatAmountFen,
		&i.Status,
		&i.HoldID,
		&i.PaymentReferenceChars,
		&i.PaymentReferenceKeyID,
		&i.PaymentReferenceNonce,
		&i.PaymentReferenceCiphertext,
		&i.PaymentReferenceDeletedAt,
		&i.PaymentDeadline,
		&i.ReviewDueAt,
		&i.LedgerTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getTradeOrderID = `-- name: GetTradeOrderID :one
SELECT order_id FROM c2c_trades WHERE id = $1
`

func (q *Queries) GetTradeOrderID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTradeOrderID, id)
	var order_id string
	err := row.Scan(&order_id)
	return order_id, err
}

const getTradeParties = `-- name: GetTradeParties :one
SELECT buyer_account_id, seller_account_id FROM c2c_trades WHERE id = $1
`

type GetTradePartiesRow struct {
	BuyerAccountID  string
	SellerAccountID string
}

func (q *Queries) GetTradeParties(ctx context.Context, id string) (GetTradePartiesRow, error) {
	row := q.db.QueryRow(ctx, getTradeParties, id)
	var i GetTradePartiesRow
	err := row.Scan(&i.BuyerAccountID, &i.SellerAccountID)
	return i, err
}

const insertDisputeStatement = `-- name: InsertDisputeStatement :exec
INSERT INTO c2c_dispute_statements (
	id, trade_id, actor_account_id, character_count, key_id, nonce, ciphertext, created_at
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertDisputeStatementParams struct {
	ID             string
	TradeID        string
	ActorAccountID string
	CharacterCount int32
	KeyID          *string
	Nonce          []byte
	Ciphertext     []byte
	CreatedAt      time.Time
}

func (q *Queries) InsertDisputeStatement(ctx context.Context, arg InsertDisputeStatementParams) error {
	_, err := q.db.Exec(ctx, insertDisputeStatement,
		arg.ID,
		arg.TradeID,
		arg.ActorAccountID,
		arg.CharacterCount,
		arg.KeyID,
		arg.Nonce,
		arg.Ciphertext,
		arg.CreatedAt,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO c2c_events (
	order_id, trade_id, actor_account_id, action, reason,
	ledger_transaction_id, hold_business_id, created_at
) VALUES (
	$1, $2, $3, $4, $5,
	$6, $7, $8
)
`

type InsertEventParams struct {
	OrderID             string
	TradeID             *string
	ActorAccountID      *string
	Action              string
	Reason              string
	LedgerTransactionID *string
	HoldBusinessID      *string
	CreatedAt           time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.OrderID,
		arg.TradeID,
		arg.ActorAccountID,
		arg.Action,
		arg.Reason,
		arg.LedgerTransactionID,
		arg.HoldBusinessID,
		arg.CreatedAt,
	)
	return err
}

const insertOrder = `-- name: InsertOrder :exec

INSERT INTO c2c_orders (
	id, owner_account_id, unit_price_fen, total_nano,
	available_nano, allocated_nano, settled_nano, closed_nano,
	minimum_nano, maximum_nano, status, parent_hold_id, created_at, updated_at
) VALUES (
	$1, $2, $3, $4,
	$4, 0, 0, 0,
	$5, $6, 'open', $7, $8, $8
)
`

type InsertOrderParams struct {
	ID             string
	OwnerAccountID string
	UnitPriceFen   int64
	TotalNano      money.Amount
	MinimumNano    money.Amount
	MaximumNano    money.Amount
	ParentHoldID   string
	CreatedAt      time.Time
}

// ---------------------------------------------------------------------------
// 订单写入
// ---------------------------------------------------------------------------
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.OwnerAccountID,
		arg.UnitPriceFen,
		arg.TotalNano,
		arg.MinimumNano,
		arg.MaximumNano,
		arg.ParentHoldID,
		arg.CreatedAt,
	)
	return err
}

const insertPaymentMethod = `-- name: InsertPaymentMethod :exec
INSERT INTO c2c_payment_methods (
	id, order_id, method_type, position, qr_available, key_id, nonce, ciphertext, created_at
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertPaymentMethodParams struct {
	ID          string
	OrderID     string
	MethodType  string
	Position    int32
	QrAvailable bool
	KeyID       string
	Nonce       []byte
	Ciphertext  []byte
	CreatedAt   time.Time
}

func (q *Queries) InsertPaymentMethod(ctx context.Context, arg InsertPaymentMethodParams) error {
	_, err := q.db.Exec(ctx, insertPaymentMethod,
		arg.ID,
		arg.OrderID,
		arg.MethodType,
		arg.Position,
		arg.QrAvailable,
		arg.KeyID,
		arg.Nonce,
		arg.Ciphertext,
		arg.CreatedAt,
	)
	return err
}

const insertTrade = `-- name: InsertTrade :exec

INSERT INTO c2c_trades (
	id, order_id, buyer_account_id, seller_account_id, quantity_nano,
	unit_price_fen, fiat_amount_fen, status, hold_id, selected_payment_method_id,
	payment_deadline, created_at, updated_at
) VALUES (
	$1, $2, $3, $4, $5,
	$6, $7, 'awaiting_payment', $8, $9,
	$10, $11, $11
)
`

type InsertTradeParams struct {
	ID                      string
	OrderID                 string
	BuyerAccountID          string
	SellerAccountID         string
	QuantityNano            money.Amount
	UnitPriceFen            int64
	FiatAmountFen           int64
	HoldID                  string
	SelectedPaymentMethodID string
	PaymentDeadline         time.Time
	CreatedAt               time.Time
}

// ---------------------------------------------------------------------------
// 成交写入
// ---------------------------------------------------------------------------
func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) error {
	_, err := q.db.Exec(ctx, insertTrade,
		arg.ID,
		arg.OrderID,
		arg.BuyerAccountID,
		arg.SellerAccountID,
		arg.QuantityNano,
		arg.UnitPriceFen,
		arg.FiatAmountFen,
		arg.HoldID,
		arg.SelectedPaymentMethodID,
		arg.PaymentDeadline,
		arg.CreatedAt,
	)
	return err
}

const isOrderParticipant = `-- name: IsOrderParticipant :one
SELECT EXISTS (
	SELECT 1 FROM c2c_trades
	WHERE order_id = $1 AND (buyer_account_id = $2 OR seller_account_id = $2)
)::boolean
`

type IsOrderParticipantParams struct {
	OrderID   string
	AccountID string
}

func (q *Queries) IsOrderParticipant(ctx context.Context, arg IsOrderParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOrderParticipant, arg.OrderID, arg.AccountID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAccountTrades = `-- name: ListAccountTrades :many
SELECT t.id, t.order_id,
	t.buyer_account_id, buyer.display_name AS buyer_display_name,
	t.seller_account_id, seller.display_name AS seller_display_name,
	buyer.credit_frozen AS buyer_credit_frozen, seller.credit_frozen AS seller_credit_frozen,
	t.quantity_nano, t.unit_price_fen, t.fiat_amount_fen, t.status,
	t.hold_id, t.payment_reference_chars,
	COALESCE(t.payment_reference_key_id, '')::text AS payment_reference_key_id,
	COALESCE(t.payment_reference_nonce, ''::bytea)::bytea AS payment_reference_nonce,
	COALESCE(t.payment_reference_ciphertext, ''::bytea)::bytea AS payment_reference_ciphertext,
	t.payment_reference_deleted_at,
	t.payment_deadline, t.review_due_at,
	COALESCE(t.ledger_transaction_id::text, '')::text AS ledger_transaction_id,
	t.created_at, t.updated_at, t.paid_at, t.resolved_at
FROM c2c_trades t
JOIN accounts buyer ON buyer.id = t.buyer_account_id
JOIN accounts seller ON seller.id = t.seller_account_id
WHERE t.buyer_account_id = $1 OR t.seller_account_id = $1
ORDER BY t.updated_at DESC, t.id DESC LIMIT 200
`

type ListAccountTradesRow struct {
	ID                         string
	OrderID                    string
	BuyerAccountID             string
	BuyerDisplayName           string
	SellerAccountID            string
	SellerDisplayName          string
	BuyerCreditFrozen          bool
	SellerCreditFrozen         bool
	QuantityNano               money.Amount
	UnitPriceFen               int64
	FiatAmountFen              int64
	Status                     string
	HoldID                     string
	PaymentReferenceChars      int32
	PaymentReferenceKeyID      string
	PaymentReferenceNonce      []byte
	PaymentReferenceCiphertext []byte
	PaymentReferenceDeletedAt  *time.Time
	PaymentDeadline            time.Time
	ReviewDueAt                *time.Time
	LedgerTransactionID        string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	PaidAt                     *time.Time
	ResolvedAt                 *time.Time
}

func (q *Queries) ListAccountTrades(ctx context.Context, accountID string) ([]ListAccountTradesRow, error) {
	rows, err := q.db.Query(ctx, listAccountTrades, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountTradesRow
	for rows.Next() {
		var i ListAccountTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.BuyerAccountID,
			&i.BuyerDisplayName,
			&i.SellerAccountID,
			&i.SellerDisplayName,
			&i.BuyerCreditFrozen,
			&i.SellerCreditFrozen,
			&i.QuantityNano,
			&i.UnitPriceFen,
			&i.FiatAmountFen,
			&i.Status,
			&i.HoldID,
			&i.PaymentReferenceChars,
			&i.PaymentReferenceKeyID,
			&i.PaymentReferenceNonce,
			&i.PaymentReferenceCiphertext,
			&i.PaymentReferenceDeletedAt,
			&i.PaymentDeadline,
			&i.ReviewDueAt,
			&i.LedgerTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputedTrades = `-- name: ListDisputedTrades :many
SELECT t.id, t.order_id,
	t.buyer_account_id, buyer.display_name AS buyer_display_name,
	t.seller_account_id, seller.display_name AS seller_display_name,
	buyer.credit_frozen AS buyer_credit_frozen, seller.credit_frozen AS seller_credit_frozen,
	t.quantity_nano, t.unit_price_fen, t.fiat_amount_fen, t.status,
	t.hold_id, t.payment_reference_chars,
	COALESCE(t.payment_reference_key_id, '')::text AS payment_reference_key_id,
	COALESCE(t.payment_reference_nonce, ''::bytea)::bytea AS payment_reference_nonce,
	COALESCE(t.payment_reference_ciphertext, ''::bytea)::bytea AS payment_reference_ciphertext,
	t.payment_reference_deleted_at,
	t.payment_deadline, t.review_due_at,
	COALESCE(t.ledger_transaction_id::text, '')::text AS ledger_transaction_id,
	t.created_at, t.updated_at, t.paid_at, t.resolved_at
FROM c2c_trades t
JOIN accounts buyer ON buyer.id = t.buyer_account_id
JOIN accounts seller ON seller.id = t.seller_account_id
WHERE t.status = 'disputed'
ORDER BY t.updated_at, t.id LIMIT 200
`

type ListDisputedTradesRow struct {
	ID                         string
	OrderID                    string
	BuyerAccountID             string
	BuyerDisplayName           string
	SellerAccountID            string
	SellerDisplayName          string
	BuyerCreditFrozen          bool
	SellerCreditFrozen         bool
	QuantityNano               money.Amount
	UnitPriceFen               int64
	FiatAmountFen              int64
	Status                     string
	HoldID                     string
	PaymentReferenceChars      int32
	PaymentReferenceKeyID      string
	PaymentReferenceNonce      []byte
	PaymentReferenceCiphertext []byte
	PaymentReferenceDeletedAt  *time.Time
	PaymentDeadline            time.Time
	ReviewDueAt                *time.Time
	LedgerTransactionID        string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	PaidAt                     *time.Time
	ResolvedAt                 *time.Time
}

func (q *Queries) ListDisputedTrades(ctx context.Context) ([]ListDisputedTradesRow, error) {
	rows, err := q.db.Query(ctx, listDisputedTrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisputedTradesRow
	for rows.Next() {
		var i ListDisputedTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.BuyerAccountID,
			&i.BuyerDisplayName,
			&i.SellerAccountID,
			&i.SellerDisplayName,
			&i.BuyerCreditFrozen,
			&i.SellerCreditFrozen,
			&i.QuantityNano,
			&i.UnitPriceFen,
			&i.FiatAmountFen,
			&i.Status,
			&i.HoldID,
			&i.PaymentReferenceChars,
			&i.PaymentReferenceKeyID,
			&i.PaymentReferenceNonce,
			&i.PaymentReferenceCiphertext,
			&i.PaymentReferenceDeletedAt,
			&i.PaymentDeadline,
			&i.ReviewDueAt,
			&i.LedgerTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueTradeIDs = `-- name: ListDueTradeIDs :many

SELECT id FROM c2c_trades
WHERE status = 'awaiting_payment' AND payment_deadline <= $1
ORDER BY payment_deadline, id LIMIT $2
`

type ListDueTradeIDsParams struct {
	Now        time.Time
	BatchLimit int32
}

// ---------------------------------------------------------------------------
// 超时与私密数据清理
// ---------------------------------------------------------------------------
func (q *Queries) ListDueTradeIDs(ctx context.Context, arg ListDueTradeIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listDueTradeIDs, arg.Now, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncryptionTargets = `-- name: ListEncryptionTargets :many
SELECT id::text AS record_id, 'payment_method'::text AS purpose, key_id, nonce, ciphertext FROM c2c_payment_methods
UNION ALL
SELECT id::text, 'payment_reference', payment_reference_key_id,
	payment_reference_nonce, payment_reference_ciphertext
FROM c2c_trades WHERE payment_reference_deleted_at IS NULL AND payment_reference_ciphertext IS NOT NULL
UNION ALL
SELECT id::text, 'dispute_statement', key_id, nonce, ciphertext
FROM c2c_dispute_statements WHERE deleted_at IS NULL
ORDER BY 1
`

type ListEncryptionTargetsRow struct {
	RecordID   string
	Purpose    string
	KeyID      string
	Nonce      []byte
	Ciphertext []byte
}

func (q *Queries) ListEncryptionTargets(ctx context.Context) ([]ListEncryptionTargetsRow, error) {
	rows, err := q.db.Query(ctx, listEncryptionTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncryptionTargetsRow
	for rows.Next() {
		var i ListEncryptionTargetsRow
		if err := rows.Scan(
			&i.RecordID,
			&i.Purpose,
			&i.KeyID,
			&i.Nonce,
			&i.Ciphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, order_id, COALESCE(trade_id::text, '')::text AS trade_id,
	COALESCE(actor_account_id::text, '')::text AS actor_account_id,
	action, reason, COALESCE(ledger_transaction_id::text, '')::text AS ledger_transaction_id,
	COALESCE(hold_business_id, '')::text AS hold_business_id, created_at
FROM c2c_events
WHERE order_id = $1 AND ($2::uuid IS NULL OR trade_id = $2::uuid)
ORDER BY id
`

type ListEventsParams struct {
	OrderID string
	TradeID *string
}

type ListEventsRow struct {
	ID                  int64
	OrderID             string
	TradeID             string
	ActorAccountID      string
	Action              string
	Reason              string
	LedgerTransactionID string
	HoldBusinessID      string
	CreatedAt           time.Time
}

// trade_id 为空表示整张订单的全部事件。
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.OrderID, arg.TradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TradeID,
			&i.ActorAccountID,
			&i.Action,
			&i.Reason,
			&i.LedgerTransactionID,
			&i.HoldBusinessID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketSellOrders = `-- name: ListMarketSellOrders :many
SELECT o.id, o.owner_account_id, owner.display_name AS owner_display_name,
	o.unit_price_fen, o.total_nano, o.available_nano, o.allocated_nano,
	o.settled_nano, o.closed_nano, o.minimum_nano, o.maximum_nano,
	o.status, COALESCE(o.parent_hold_id::text, '')::text AS parent_hold_id, o.created_at, o.updated_at,
	o.cancelled_at,
	((owner.status = 'active' AND NOT owner.must_change_password AND NOT owner.credit_frozen)
		AND o.status = 'open' AND o.available_nano > 0)::boolean AS takeable
FROM c2c_orders o JOIN accounts owner ON owner.id = o.owner_account_id
WHERE o.status = 'open' AND o.available_nano > 0
	AND (owner.status = 'active' AND NOT owner.must_change_password AND NOT owner.credit_frozen)
ORDER BY o.unit_price_fen ASC, o.created_at, o.id LIMIT 200
`

type ListMarketSellOrdersRow struct {
	ID               string
	OwnerAccountID   string
	OwnerDisplayName string
	UnitPriceFen     int64
	TotalNano        money.Amount
	AvailableNano    money.Amount
	AllocatedNano    money.Amount
	SettledNano      money.Amount
	ClosedNano       money.Amount
	MinimumNano      money.Amount
	MaximumNano      money.Amount
	Status           string
	ParentHoldID     string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CancelledAt      *time.Time
	Takeable         bool
}

func (q *Queries) ListMarketSellOrders(ctx context.Context) ([]ListMarketSellOrdersRow, error) {
	rows, err := q.db.Query(ctx, listMarketSellOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketSellOrdersRow
	for rows.Next() {
		var i ListMarketSellOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.OwnerDisplayName,
			&i.UnitPriceFen,
			&i.TotalNano,
			&i.AvailableNano,
			&i.AllocatedNano,
			&i.SettledNano,
			&i.ClosedNano,
			&i.MinimumNano,
			&i.MaximumNano,
			&i.Status,
			&i.ParentHoldID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
			&i.Takeable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerOrders = `-- name: ListOwnerOrders :many
SELECT o.id, o.owner_account_id, owner.display_name AS owner_display_name,
	o.unit_price_fen, o.total_nano, o.available_nano, o.allocated_nano,
	o.settled_nano, o.closed_nano, o.minimum_nano, o.maximum_nano,
	o.status, COALESCE(o.parent_hold_id::text, '')::text AS parent_hold_id, o.created_at, o.updated_at,
	o.cancelled_at,
	((owner.status = 'active' AND NOT owner.must_change_password AND NOT owner.credit_frozen)
		AND o.status = 'open' AND o.available_nano > 0)::boolean AS takeable
FROM c2c_orders o JOIN accounts owner ON owner.id = o.owner_account_id
WHERE o.owner_account_id = $1
ORDER BY o.updated_at DESC, o.id DESC LIMIT 200
`

type ListOwnerOrdersRow struct {
	ID               string
	OwnerAccountID   string
	OwnerDisplayName string
	UnitPriceFen     int64
	TotalNano        money.Amount
	AvailableNano    money.Amount
	AllocatedNano    money.Amount
	SettledNano      money.Amount
	ClosedNano       money.Amount
	MinimumNano      money.Amount
	MaximumNano      money.Amount
	Status           string
	ParentHoldID     string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CancelledAt      *time.Time
	Takeable         bool
}

func (q *Queries) ListOwnerOrders(ctx context.Context, ownerAccountID string) ([]ListOwnerOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOwnerOrders, ownerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerOrdersRow
	for rows.Next() {
		var i ListOwnerOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.OwnerDisplayName,
			&i.UnitPriceFen,
			&i.TotalNano,
			&i.AvailableNano,
			&i.AllocatedNano,
			&i.SettledNano,
			&i.ClosedNano,
			&i.MinimumNano,
			&i.MaximumNano,
			&i.Status,
			&i.ParentHoldID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
			&i.Takeable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethods = `-- name: ListPaymentMethods :many

SELECT id, order_id, method_type, position, qr_available, key_id, nonce, ciphertext, created_at
FROM c2c_payment_methods WHERE order_id = $1 ORDER BY position
`

// ---------------------------------------------------------------------------
// 收款方式
// ---------------------------------------------------------------------------
func (q *Queries) ListPaymentMethods(ctx context.Context, orderID string) ([]C2cPaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []C2cPaymentMethod
	for rows.Next() {
		var i C2cPaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MethodType,
			&i.Position,
			&i.QrAvailable,
			&i.KeyID,
			&i.Nonce,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatements = `-- name: ListStatements :many
SELECT s.id, s.trade_id, s.actor_account_id, actor.display_name AS actor_display_name,
	s.character_count, COALESCE(s.key_id, '')::text AS key_id,
	COALESCE(s.nonce, ''::bytea)::bytea AS nonce,
	COALESCE(s.ciphertext, ''::bytea)::bytea AS ciphertext, s.created_at, s.deleted_at
FROM c2c_dispute_statements s JOIN accounts actor ON actor.id = s.actor_account_id
WHERE s.trade_id = $1 ORDER BY s.created_at, s.id
`

type ListStatementsRow struct {
	ID               string
	TradeID          string
	ActorAccountID   string
	ActorDisplayName string
	CharacterCount   int32
	KeyID            string
	Nonce            []byte
	Ciphertext       []byte
	CreatedAt        time.Time
	DeletedAt        *time.Time
}

func (q *Queries) ListStatements(ctx context.Context, tradeID string) ([]ListStatementsRow, error) {
	rows, err := q.db.Query(ctx, listStatements, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementsRow
	for rows.Next() {
		var i ListStatementsRow
		if err := rows.Scan(
			&i.ID,
			&i.TradeID,
			&i.ActorAccountID,
			&i.ActorDisplayName,
			&i.CharacterCount,
			&i.KeyID,
			&i.Nonce,
			&i.Ciphertext,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountForUpdate = `-- name: LockAccountForUpdate :one
SELECT credit_frozen, version FROM accounts WHERE id = $1 FOR UPDATE
`

type LockAccountForUpdateRow struct {
	CreditFrozen bool
	Version      int64
}

func (q *Queries) LockAccountForUpdate(ctx context.Context, id string) (LockAccountForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockAccountForUpdate, id)
	var i LockAccountForUpdateRow
	err := row.Scan(&i.CreditFrozen, &i.Version)
	return i, err
}

const lockAccountMutationKey = `-- name: LockAccountMutationKey :exec

SELECT pg_advisory_xact_lock(hashtextextended('oh-my-aihub-account:' || $1::text, 0))
`

// ---------------------------------------------------------------------------
// 账户闸门与锁
// ---------------------------------------------------------------------------
// 同一事务内多个账户的咨询锁由调用方按账户 ID 排序后逐个获取。
func (q *Queries) LockAccountMutationKey(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, lockAccountMutationKey, accountID)
	return err
}

const lockLedgerAccountByIdentity = `-- name: LockLedgerAccountByIdentity :one
SELECT 1::int AS locked FROM ledger_accounts WHERE identity_account_id = $1::uuid FOR UPDATE
`

// 争议限制当事方：先锁账本账户行，再锁身份行（与 UpdateAccount 的账户策略锁序一致）。
func (q *Queries) LockLedgerAccountByIdentity(ctx context.Context, identityAccountID string) (int32, error) {
	row := q.db.QueryRow(ctx, lockLedgerAccountByIdentity, identityAccountID)
	var locked int32
	err := row.Scan(&locked)
	return locked, err
}

const markTradePaid = `-- name: MarkTradePaid :execrows
UPDATE c2c_trades
SET status = 'paid', payment_reference_chars = $1,
	payment_reference_key_id = $2,
	payment_reference_nonce = $3,
	payment_reference_ciphertext = $4,
	paid_at = $5, updated_at = $5
WHERE id = $6 AND status = 'awaiting_payment'
`

type MarkTradePaidParams struct {
	PaymentReferenceChars      int32
	PaymentReferenceKeyID      *string
	PaymentReferenceNonce      []byte
	PaymentReferenceCiphertext []byte
	PaidAt                     *time.Time
	ID                         string
}

// 买家声明已付款；收款凭据为空时三个密文字段均为 NULL。
func (q *Queries) MarkTradePaid(ctx context.Context, arg MarkTradePaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTradePaid,
		arg.PaymentReferenceChars,
		arg.PaymentReferenceKeyID,
		arg.PaymentReferenceNonce,
		arg.PaymentReferenceCiphertext,
		arg.PaidAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const openTradeDispute = `-- name: OpenTradeDispute :execrows
UPDATE c2c_trades SET status = 'disputed', review_due_at = $1, updated_at = $2
WHERE id = $3 AND status = 'paid'
`

type OpenTradeDisputeParams struct {
	ReviewDueAt *time.Time
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) OpenTradeDispute(ctx context.Context, arg OpenTradeDisputeParams) (int64, error) {
	result, err := q.db.Exec(ctx, openTradeDispute, arg.ReviewDueAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseTrade = `-- name: ReleaseTrade :execrows
UPDATE c2c_trades
SET status = 'released_to_buyer', ledger_transaction_id = $1,
	resolved_at = $2, updated_at = $2
WHERE id = $3 AND status = $4
`

type ReleaseTradeParams struct {
	LedgerTransactionID *string
	ResolvedAt          *time.Time
	ID                  string
	ExpectedStatus      string
}

func (q *Queries) ReleaseTrade(ctx context.Context, arg ReleaseTradeParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseTrade,
		arg.LedgerTransactionID,
		arg.ResolvedAt,
		arg.ID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveCommand = `-- name: ReserveCommand :execrows

INSERT INTO c2c_commands (
	actor_key, actor_account_id, operation, idempotency_key, payload_hash, created_at
) VALUES (
	$1, $2, $3, $4, $5, $6
)
ON CONFLICT (actor_key, operation, idempotency_key) DO NOTHING
`

type ReserveCommandParams struct {
	ActorKey       string
	ActorAccountID *string
	Operation      string
	IdempotencyKey string
	PayloadHash    []byte
	CreatedAt      time.Time
}

// ---------------------------------------------------------------------------
// 幂等命令
// ---------------------------------------------------------------------------
func (q *Queries) ReserveCommand(ctx context.Context, arg ReserveCommandParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveCommand,
		arg.ActorKey,
		arg.ActorAccountID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.PayloadHash,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const returnTrade = `-- name: ReturnTrade :execrows
UPDATE c2c_trades SET status = $1, resolved_at = $2, updated_at = $2
WHERE id = $3 AND status = $4
`

type ReturnTradeParams struct {
	NewStatus      string
	ResolvedAt     *time.Time
	ID             string
	ExpectedStatus string
}

// 退回分配量：待付款 -> cancelled/expired，已付款或争议中 -> returned_to_seller。
func (q *Queries) ReturnTrade(ctx context.Context, arg ReturnTradeParams) (int64, error) {
	result, err := q.db.Exec(ctx, returnTrade,
		arg.NewStatus,
		arg.ResolvedAt,
		arg.ID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchTrade = `-- name: TouchTrade :exec
UPDATE c2c_trades SET updated_at = $1 WHERE id = $2
`

type TouchTradeParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) TouchTrade(ctx context.Context, arg TouchTradeParams) error {
	_, err := q.db.Exec(ctx, touchTrade, arg.UpdatedAt, arg.ID)
	return err
}

const updateOrderAmounts = `-- name: UpdateOrderAmounts :execrows
UPDATE c2c_orders
SET available_nano = $1, allocated_nano = $2, settled_nano = $3,
	closed_nano = $4, status = $5, updated_at = $6
WHERE id = $7
`

type UpdateOrderAmountsParams struct {
	AvailableNano money.Amount
	AllocatedNano money.Amount
	SettledNano   money.Amount
	ClosedNano    money.Amount
	Status        string
	UpdatedAt     time.Time
	ID            string
}

func (q *Queries) UpdateOrderAmounts(ctx context.Context, arg UpdateOrderAmountsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderAmounts,
		arg.AvailableNano,
		arg.AllocatedNano,
		arg.SettledNano,
		arg.ClosedNano,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
