// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package c2cpg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const accountStatus = `-- name: AccountStatus :one
SELECT status FROM accounts WHERE id = $1
`

func (q *Queries) AccountStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, accountStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const countUnfinishedTrades = `-- name: CountUnfinishedTrades :one
SELECT count(*) FROM c2c_trades
WHERE order_id = $1 AND buyer_id = $2 AND status IN ('awaiting_payment', 'paid', 'disputed')
`

type CountUnfinishedTradesParams struct {
	OrderID string
	BuyerID string
}

func (q *Queries) CountUnfinishedTrades(ctx context.Context, arg CountUnfinishedTradesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnfinishedTrades, arg.OrderID, arg.BuyerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishTrade = `-- name: FinishTrade :exec
UPDATE c2c_trades
SET status = $1::text,
    ledger_tx_id = $2,
    resolved_by = $3,
    resolution_reason = $4,
    released_at = CASE WHEN $1::text = 'released' THEN now() ELSE released_at END,
    cancelled_at = CASE WHEN $1::text = 'cancelled' THEN now() ELSE cancelled_at END,
    resolved_at = CASE WHEN $1::text LIKE 'resolved\_%' THEN now() ELSE resolved_at END
WHERE id = $5
`

type FinishTradeParams struct {
	Status           string
	LedgerTxID       *string
	ResolvedBy       *string
	ResolutionReason *string
	ID               string
}

// Moves a trade to a terminal status. Releases and returns reference the
// ledger transaction that moved the points.
func (q *Queries) FinishTrade(ctx context.Context, arg FinishTradeParams) error {
	_, err := q.db.Exec(ctx, finishTrade,
		arg.Status,
		arg.LedgerTxID,
		arg.ResolvedBy,
		arg.ResolutionReason,
		arg.ID,
	)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT o.id, o.seller_id, o.total_nano, o.available_nano, o.in_trade_nano, o.sold_nano, o.closed_nano, o.unit_price_fen, o.min_per_trade_nano, o.max_per_trade_nano, o.payment_methods_ciphertext, o.payment_methods_nonce, o.payment_methods_key_id, o.status, o.created_at, o.updated_at, o.closed_at, a.display_name AS seller_name
FROM c2c_orders o JOIN accounts a ON a.id = o.seller_id
WHERE o.id = $1
`

type GetOrderRow struct {
	C2cOrder   C2cOrder
	SellerName string
}

func (q *Queries) GetOrder(ctx context.Context, id string) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.C2cOrder.ID,
		&i.C2cOrder.SellerID,
		&i.C2cOrder.TotalNano,
		&i.C2cOrder.AvailableNano,
		&i.C2cOrder.InTradeNano,
		&i.C2cOrder.SoldNano,
		&i.C2cOrder.ClosedNano,
		&i.C2cOrder.UnitPriceFen,
		&i.C2cOrder.MinPerTradeNano,
		&i.C2cOrder.MaxPerTradeNano,
		&i.C2cOrder.PaymentMethodsCiphertext,
		&i.C2cOrder.PaymentMethodsNonce,
		&i.C2cOrder.PaymentMethodsKeyID,
		&i.C2cOrder.Status,
		&i.C2cOrder.CreatedAt,
		&i.C2cOrder.UpdatedAt,
		&i.C2cOrder.ClosedAt,
		&i.SellerName,
	)
	return i, err
}

const getTrade = `-- name: GetTrade :one
SELECT t.id, t.order_id, t.buyer_id, t.seller_id, t.amount_nano, t.unit_price_fen, t.total_fen, t.status, t.payment_deadline, t.buyer_note, t.dispute_opened_by, t.buyer_statement, t.seller_statement, t.resolution_reason, t.resolved_by, t.created_at, t.paid_at, t.released_at, t.cancelled_at, t.disputed_at, t.resolved_at, t.ledger_tx_id, b.display_name AS buyer_name, s.display_name AS seller_name,
       o.payment_methods_ciphertext, o.payment_methods_nonce, o.payment_methods_key_id
FROM c2c_trades t
JOIN c2c_orders o ON o.id = t.order_id
JOIN accounts b ON b.id = t.buyer_id
JOIN accounts s ON s.id = t.seller_id
WHERE t.id = $1
`

type GetTradeRow struct {
	C2cTrade                 C2cTrade
	BuyerName                string
	SellerName               string
	PaymentMethodsCiphertext []byte
	PaymentMethodsNonce      []byte
	PaymentMethodsKeyID      string
}

func (q *Queries) GetTrade(ctx context.Context, id string) (GetTradeRow, error) {
	row := q.db.QueryRow(ctx, getTrade, id)
	var i GetTradeRow
	err := row.Scan(
		&i.C2cTrade.ID,
		&i.C2cTrade.OrderID,
		&i.C2cTrade.BuyerID,
		&i.C2cTrade.SellerID,
		&i.C2cTrade.AmountNano,
		&i.C2cTrade.UnitPriceFen,
		&i.C2cTrade.TotalFen,
		&i.C2cTrade.Status,
		&i.C2cTrade.PaymentDeadline,
		&i.C2cTrade.BuyerNote,
		&i.C2cTrade.DisputeOpenedBy,
		&i.C2cTrade.BuyerStatement,
		&i.C2cTrade.SellerStatement,
		&i.C2cTrade.ResolutionReason,
		&i.C2cTrade.ResolvedBy,
		&i.C2cTrade.CreatedAt,
		&i.C2cTrade.PaidAt,
		&i.C2cTrade.ReleasedAt,
		&i.C2cTrade.CancelledAt,
		&i.C2cTrade.DisputedAt,
		&i.C2cTrade.ResolvedAt,
		&i.C2cTrade.LedgerTxID,
		&i.BuyerName,
		&i.SellerName,
		&i.PaymentMethodsCiphertext,
		&i.PaymentMethodsNonce,
		&i.PaymentMethodsKeyID,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO c2c_orders (
    id, seller_id, total_nano, available_nano, unit_price_fen, min_per_trade_nano, max_per_trade_nano,
    payment_methods_ciphertext, payment_methods_nonce, payment_methods_key_id
) VALUES ($1, $2, $3, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO NOTHING
RETURNING id
`

type InsertOrderParams struct {
	ID                       string
	SellerID                 string
	TotalNano                money.Amount
	UnitPriceFen             int64
	MinPerTradeNano          money.Amount
	MaxPerTradeNano          *money.Amount
	PaymentMethodsCiphertext []byte
	PaymentMethodsNonce      []byte
	PaymentMethodsKeyID      string
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (string, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ID,
		arg.SellerID,
		arg.TotalNano,
		arg.UnitPriceFen,
		arg.MinPerTradeNano,
		arg.MaxPerTradeNano,
		arg.PaymentMethodsCiphertext,
		arg.PaymentMethodsNonce,
		arg.PaymentMethodsKeyID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertTrade = `-- name: InsertTrade :one
INSERT INTO c2c_trades (id, order_id, buyer_id, seller_id, amount_nano, unit_price_fen, total_fen, payment_deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        now() + make_interval(mins => (SELECT c2c_payment_timeout_minutes FROM settings)))
ON CONFLICT (id) DO NOTHING
RETURNING id
`

type InsertTradeParams struct {
	ID           string
	OrderID      string
	BuyerID      string
	SellerID     string
	AmountNano   money.Amount
	UnitPriceFen int64
	TotalFen     int64
}

// The payment deadline comes from the platform setting at insert time.
func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) (string, error) {
	row := q.db.QueryRow(ctx, insertTrade,
		arg.ID,
		arg.OrderID,
		arg.BuyerID,
		arg.SellerID,
		arg.AmountNano,
		arg.UnitPriceFen,
		arg.TotalFen,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listDisputedTrades = `-- name: ListDisputedTrades :many
SELECT t.id, t.order_id, t.buyer_id, t.seller_id, t.amount_nano, t.unit_price_fen, t.total_fen, t.status, t.payment_deadline, t.buyer_note, t.dispute_opened_by, t.buyer_statement, t.seller_statement, t.resolution_reason, t.resolved_by, t.created_at, t.paid_at, t.released_at, t.cancelled_at, t.disputed_at, t.resolved_at, t.ledger_tx_id, b.display_name AS buyer_name, s.display_name AS seller_name,
       o.payment_methods_ciphertext, o.payment_methods_nonce, o.payment_methods_key_id
FROM c2c_trades t
JOIN c2c_orders o ON o.id = t.order_id
JOIN accounts b ON b.id = t.buyer_id
JOIN accounts s ON s.id = t.seller_id
WHERE t.status = $1::text
  AND (NOT $2::bool OR (t.disputed_at, t.id) > ($3::timestamptz, $4::uuid))
ORDER BY t.disputed_at, t.id
LIMIT $5
`

type ListDisputedTradesParams struct {
	Status    string
	HasCursor bool
	AfterTime time.Time
	AfterID   string
	RowLimit  int32
}

type ListDisputedTradesRow struct {
	C2cTrade                 C2cTrade
	BuyerName                string
	SellerName               string
	PaymentMethodsCiphertext []byte
	PaymentMethodsNonce      []byte
	PaymentMethodsKeyID      string
}

func (q *Queries) ListDisputedTrades(ctx context.Context, arg ListDisputedTradesParams) ([]ListDisputedTradesRow, error) {
	rows, err := q.db.Query(ctx, listDisputedTrades,
		arg.Status,
		arg.HasCursor,
		arg.AfterTime,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisputedTradesRow
	for rows.Next() {
		var i ListDisputedTradesRow
		if err := rows.Scan(
			&i.C2cTrade.ID,
			&i.C2cTrade.OrderID,
			&i.C2cTrade.BuyerID,
			&i.C2cTrade.SellerID,
			&i.C2cTrade.AmountNano,
			&i.C2cTrade.UnitPriceFen,
			&i.C2cTrade.TotalFen,
			&i.C2cTrade.Status,
			&i.C2cTrade.PaymentDeadline,
			&i.C2cTrade.BuyerNote,
			&i.C2cTrade.DisputeOpenedBy,
			&i.C2cTrade.BuyerStatement,
			&i.C2cTrade.SellerStatement,
			&i.C2cTrade.ResolutionReason,
			&i.C2cTrade.ResolvedBy,
			&i.C2cTrade.CreatedAt,
			&i.C2cTrade.PaidAt,
			&i.C2cTrade.ReleasedAt,
			&i.C2cTrade.CancelledAt,
			&i.C2cTrade.DisputedAt,
			&i.C2cTrade.ResolvedAt,
			&i.C2cTrade.LedgerTxID,
			&i.BuyerName,
			&i.SellerName,
			&i.PaymentMethodsCiphertext,
			&i.PaymentMethodsNonce,
			&i.PaymentMethodsKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueTrades = `-- name: ListDueTrades :many
SELECT id FROM c2c_trades
WHERE status = 'awaiting_payment' AND payment_deadline <= now()
ORDER BY payment_deadline
LIMIT $1
`

func (q *Queries) ListDueTrades(ctx context.Context, limit int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listDueTrades, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketOrders = `-- name: ListMarketOrders :many
SELECT o.id, o.seller_id, o.total_nano, o.available_nano, o.in_trade_nano, o.sold_nano, o.closed_nano, o.unit_price_fen, o.min_per_trade_nano, o.max_per_trade_nano, o.payment_methods_ciphertext, o.payment_methods_nonce, o.payment_methods_key_id, o.status, o.created_at, o.updated_at, o.closed_at, a.display_name AS seller_name
FROM c2c_orders o JOIN accounts a ON a.id = o.seller_id
WHERE o.status = 'open' AND o.available_nano > 0 AND o.seller_id <> $1
  AND (NOT $2::bool
       OR (o.unit_price_fen, o.created_at, o.id) > ($3::bigint, $4::timestamptz, $5::uuid))
ORDER BY o.unit_price_fen, o.created_at, o.id
LIMIT $6
`

type ListMarketOrdersParams struct {
	ViewerID   string
	HasCursor  bool
	AfterPrice int64
	AfterTime  time.Time
	AfterID    string
	RowLimit   int32
}

type ListMarketOrdersRow struct {
	C2cOrder   C2cOrder
	SellerName string
}

// Open orders by unit price, then age. The keyset cursor is the last row
// of the previous page.
func (q *Queries) ListMarketOrders(ctx context.Context, arg ListMarketOrdersParams) ([]ListMarketOrdersRow, error) {
	rows, err := q.db.Query(ctx, listMarketOrders,
		arg.ViewerID,
		arg.HasCursor,
		arg.AfterPrice,
		arg.AfterTime,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketOrdersRow
	for rows.Next() {
		var i ListMarketOrdersRow
		if err := rows.Scan(
			&i.C2cOrder.ID,
			&i.C2cOrder.SellerID,
			&i.C2cOrder.TotalNano,
			&i.C2cOrder.AvailableNano,
			&i.C2cOrder.InTradeNano,
			&i.C2cOrder.SoldNano,
			&i.C2cOrder.ClosedNano,
			&i.C2cOrder.UnitPriceFen,
			&i.C2cOrder.MinPerTradeNano,
			&i.C2cOrder.MaxPerTradeNano,
			&i.C2cOrder.PaymentMethodsCiphertext,
			&i.C2cOrder.PaymentMethodsNonce,
			&i.C2cOrder.PaymentMethodsKeyID,
			&i.C2cOrder.Status,
			&i.C2cOrder.CreatedAt,
			&i.C2cOrder.UpdatedAt,
			&i.C2cOrder.ClosedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerOrders = `-- name: ListSellerOrders :many
SELECT o.id, o.seller_id, o.total_nano, o.available_nano, o.in_trade_nano, o.sold_nano, o.closed_nano, o.unit_price_fen, o.min_per_trade_nano, o.max_per_trade_nano, o.payment_methods_ciphertext, o.payment_methods_nonce, o.payment_methods_key_id, o.status, o.created_at, o.updated_at, o.closed_at, a.display_name AS seller_name
FROM c2c_orders o JOIN accounts a ON a.id = o.seller_id
WHERE o.seller_id = $1
  AND ($2::text = '' OR o.status = $2::text)
  AND (NOT $3::bool OR (o.created_at, o.id) < ($4::timestamptz, $5::uuid))
ORDER BY o.created_at DESC, o.id DESC
LIMIT $6
`

type ListSellerOrdersParams struct {
	SellerID  string
	Status    string
	HasCursor bool
	AfterTime time.Time
	AfterID   string
	RowLimit  int32
}

type ListSellerOrdersRow struct {
	C2cOrder   C2cOrder
	SellerName string
}

func (q *Queries) ListSellerOrders(ctx context.Context, arg ListSellerOrdersParams) ([]ListSellerOrdersRow, error) {
	rows, err := q.db.Query(ctx, listSellerOrders,
		arg.SellerID,
		arg.Status,
		arg.HasCursor,
		arg.AfterTime,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSellerOrdersRow
	for rows.Next() {
		var i ListSellerOrdersRow
		if err := rows.Scan(
			&i.C2cOrder.ID,
			&i.C2cOrder.SellerID,
			&i.C2cOrder.TotalNano,
			&i.C2cOrder.AvailableNano,
			&i.C2cOrder.InTradeNano,
			&i.C2cOrder.SoldNano,
			&i.C2cOrder.ClosedNano,
			&i.C2cOrder.UnitPriceFen,
			&i.C2cOrder.MinPerTradeNano,
			&i.C2cOrder.MaxPerTradeNano,
			&i.C2cOrder.PaymentMethodsCiphertext,
			&i.C2cOrder.PaymentMethodsNonce,
			&i.C2cOrder.PaymentMethodsKeyID,
			&i.C2cOrder.Status,
			&i.C2cOrder.CreatedAt,
			&i.C2cOrder.UpdatedAt,
			&i.C2cOrder.ClosedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTrades = `-- name: ListUserTrades :many
SELECT t.id, t.order_id, t.buyer_id, t.seller_id, t.amount_nano, t.unit_price_fen, t.total_fen, t.status, t.payment_deadline, t.buyer_note, t.dispute_opened_by, t.buyer_statement, t.seller_statement, t.resolution_reason, t.resolved_by, t.created_at, t.paid_at, t.released_at, t.cancelled_at, t.disputed_at, t.resolved_at, t.ledger_tx_id, b.display_name AS buyer_name, s.display_name AS seller_name,
       o.payment_methods_ciphertext, o.payment_methods_nonce, o.payment_methods_key_id
FROM c2c_trades t
JOIN c2c_orders o ON o.id = t.order_id
JOIN accounts b ON b.id = t.buyer_id
JOIN accounts s ON s.id = t.seller_id
WHERE (CASE $1::text
         WHEN 'buyer' THEN t.buyer_id = $2
         WHEN 'seller' THEN t.seller_id = $2
         ELSE t.buyer_id = $2 OR t.seller_id = $2 END)
  AND ($3::text = '' OR t.status = $3::text)
  AND (NOT $4::bool
       OR (t.buyer_id = $2 AND t.status = 'awaiting_payment')
       OR (t.seller_id = $2 AND t.status = 'paid'))
  AND (NOT $5::bool OR (t.created_at, t.id) < ($6::timestamptz, $7::uuid))
ORDER BY t.created_at DESC, t.id DESC
LIMIT $8
`

type ListUserTradesParams struct {
	Role      string
	UserID    string
	Status    string
	Pending   bool
	HasCursor bool
	AfterTime time.Time
	AfterID   string
	RowLimit  int32
}

type ListUserTradesRow struct {
	C2cTrade                 C2cTrade
	BuyerName                string
	SellerName               string
	PaymentMethodsCiphertext []byte
	PaymentMethodsNonce      []byte
	PaymentMethodsKeyID      string
}

func (q *Queries) ListUserTrades(ctx context.Context, arg ListUserTradesParams) ([]ListUserTradesRow, error) {
	rows, err := q.db.Query(ctx, listUserTrades,
		arg.Role,
		arg.UserID,
		arg.Status,
		arg.Pending,
		arg.HasCursor,
		arg.AfterTime,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTradesRow
	for rows.Next() {
		var i ListUserTradesRow
		if err := rows.Scan(
			&i.C2cTrade.ID,
			&i.C2cTrade.OrderID,
			&i.C2cTrade.BuyerID,
			&i.C2cTrade.SellerID,
			&i.C2cTrade.AmountNano,
			&i.C2cTrade.UnitPriceFen,
			&i.C2cTrade.TotalFen,
			&i.C2cTrade.Status,
			&i.C2cTrade.PaymentDeadline,
			&i.C2cTrade.BuyerNote,
			&i.C2cTrade.DisputeOpenedBy,
			&i.C2cTrade.BuyerStatement,
			&i.C2cTrade.SellerStatement,
			&i.C2cTrade.ResolutionReason,
			&i.C2cTrade.ResolvedBy,
			&i.C2cTrade.CreatedAt,
			&i.C2cTrade.PaidAt,
			&i.C2cTrade.ReleasedAt,
			&i.C2cTrade.CancelledAt,
			&i.C2cTrade.DisputedAt,
			&i.C2cTrade.ResolvedAt,
			&i.C2cTrade.LedgerTxID,
			&i.BuyerName,
			&i.SellerName,
			&i.PaymentMethodsCiphertext,
			&i.PaymentMethodsNonce,
			&i.PaymentMethodsKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrder = `-- name: LockOrder :one
SELECT o.id, o.seller_id, o.total_nano, o.available_nano, o.in_trade_nano, o.sold_nano, o.closed_nano, o.unit_price_fen, o.min_per_trade_nano, o.max_per_trade_nano, o.payment_methods_ciphertext, o.payment_methods_nonce, o.payment_methods_key_id, o.status, o.created_at, o.updated_at, o.closed_at, a.display_name AS seller_name
FROM c2c_orders o JOIN accounts a ON a.id = o.seller_id
WHERE o.id = $1
FOR UPDATE OF o
`

type LockOrderRow struct {
	C2cOrder   C2cOrder
	SellerName string
}

func (q *Queries) LockOrder(ctx context.Context, id string) (LockOrderRow, error) {
	row := q.db.QueryRow(ctx, lockOrder, id)
	var i LockOrderRow
	err := row.Scan(
		&i.C2cOrder.ID,
		&i.C2cOrder.SellerID,
		&i.C2cOrder.TotalNano,
		&i.C2cOrder.AvailableNano,
		&i.C2cOrder.InTradeNano,
		&i.C2cOrder.SoldNano,
		&i.C2cOrder.ClosedNano,
		&i.C2cOrder.UnitPriceFen,
		&i.C2cOrder.MinPerTradeNano,
		&i.C2cOrder.MaxPerTradeNano,
		&i.C2cOrder.PaymentMethodsCiphertext,
		&i.C2cOrder.PaymentMethodsNonce,
		&i.C2cOrder.PaymentMethodsKeyID,
		&i.C2cOrder.Status,
		&i.C2cOrder.CreatedAt,
		&i.C2cOrder.UpdatedAt,
		&i.C2cOrder.ClosedAt,
		&i.SellerName,
	)
	return i, err
}

const lockTrade = `-- name: LockTrade :one
SELECT id FROM c2c_trades WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockTrade(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockTrade, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const markTradePaid = `-- name: MarkTradePaid :exec
UPDATE c2c_trades SET status = 'paid', buyer_note = $2, paid_at = now() WHERE id = $1
`

type MarkTradePaidParams struct {
	ID   string
	Note *string
}

func (q *Queries) MarkTradePaid(ctx context.Context, arg MarkTradePaidParams) error {
	_, err := q.db.Exec(ctx, markTradePaid, arg.ID, arg.Note)
	return err
}

const orderIDOfTrade = `-- name: OrderIDOfTrade :one
SELECT order_id FROM c2c_trades WHERE id = $1
`

func (q *Queries) OrderIDOfTrade(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, orderIDOfTrade, id)
	var order_id string
	err := row.Scan(&order_id)
	return order_id, err
}

const setDisputeStatement = `-- name: SetDisputeStatement :exec
UPDATE c2c_trades
SET status = 'disputed',
    dispute_opened_by = COALESCE(dispute_opened_by, $1),
    disputed_at = COALESCE(disputed_at, now()),
    buyer_statement = CASE WHEN $2::bool THEN $3::text ELSE buyer_statement END,
    seller_statement = CASE WHEN $2::bool THEN seller_statement ELSE $3::text END
WHERE id = $4
`

type SetDisputeStatementParams struct {
	ActorID   *string
	IsBuyer   bool
	Statement string
	ID        string
}

func (q *Queries) SetDisputeStatement(ctx context.Context, arg SetDisputeStatementParams) error {
	_, err := q.db.Exec(ctx, setDisputeStatement,
		arg.ActorID,
		arg.IsBuyer,
		arg.Statement,
		arg.ID,
	)
	return err
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE c2c_orders
SET available_nano = $2, in_trade_nano = $3, sold_nano = $4, closed_nano = $5, status = $6::text,
    closed_at = CASE WHEN $6::text = 'closed' THEN COALESCE(closed_at, now()) ELSE closed_at END,
    updated_at = now()
WHERE id = $1
`

type UpdateOrderParams struct {
	ID            string
	AvailableNano money.Amount
	InTradeNano   money.Amount
	SoldNano      money.Amount
	ClosedNano    money.Amount
	Status        string
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.Exec(ctx, updateOrder,
		arg.ID,
		arg.AvailableNano,
		arg.InTradeNano,
		arg.SoldNano,
		arg.ClosedNano,
		arg.Status,
	)
	return err
}
