// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogpg

import (
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

type Model struct {
	ID                            string
	DisplayName                   string
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	Enabled                       bool
	SortOrder                     int32
	Provider                      string
	ContextWindow                 *int64
	InputModalities               []string
	OutputModalities              []string
	SupportsTools                 bool
	SupportsStructuredOutput      bool
	SupportsVision                bool
	ParameterInfo                 string
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
}

type ModelPriceTier struct {
	ModelID                       string
	Seq                           int32
	Name                          string
	MinPromptTokens               *int64
	MaxPromptTokens               *int64
	Timezone                      string
	Weekdays                      []int16
	StartMinuteOfDay              *int16
	EndMinuteOfDay                *int16
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
}
