// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package catalogpg

import (
	"context"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const createModel = `-- name: CreateModel :one
INSERT INTO models (
	id, name, provider, context_window, parameter_info,
	input_modalities, output_modalities, supports_tools,
	supports_structured_output, supports_vision,
	input_price_nano_per_million, output_price_nano_per_million,
	cache_write_price_nano_per_million, cache_read_price_nano_per_million,
	status
) VALUES (
	$1, $2, $3, $4, $5,
	$6, $7, $8,
	$9, $10,
	$11, $12,
	$13, $14,
	$15
)
RETURNING internal_id, id, name, provider, context_window, parameter_info, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, status, version, created_at, updated_at, price_updated_at
`

type CreateModelParams struct {
	ID                            string
	Name                          string
	Provider                      string
	ContextWindow                 int64
	ParameterInfo                 string
	InputModalities               []string
	OutputModalities              []string
	SupportsTools                 bool
	SupportsStructuredOutput      bool
	SupportsVision                bool
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	Status                        string
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.ID,
		arg.Name,
		arg.Provider,
		arg.ContextWindow,
		arg.ParameterInfo,
		arg.InputModalities,
		arg.OutputModalities,
		arg.SupportsTools,
		arg.SupportsStructuredOutput,
		arg.SupportsVision,
		arg.InputPriceNanoPerMillion,
		arg.OutputPriceNanoPerMillion,
		arg.CacheWritePriceNanoPerMillion,
		arg.CacheReadPriceNanoPerMillion,
		arg.Status,
	)
	var i Model
	err := row.Scan(
		&i.InternalID,
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.ContextWindow,
		&i.ParameterInfo,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceUpdatedAt,
	)
	return i, err
}

const deleteModelPriceTiers = `-- name: DeleteModelPriceTiers :exec
DELETE FROM model_price_tiers WHERE model_id = $1
`

func (q *Queries) DeleteModelPriceTiers(ctx context.Context, modelID string) error {
	_, err := q.db.Exec(ctx, deleteModelPriceTiers, modelID)
	return err
}

const getModel = `-- name: GetModel :one
SELECT internal_id, id, name, provider, context_window, parameter_info, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, status, version, created_at, updated_at, price_updated_at FROM models
WHERE id = $1 AND ($2::boolean OR status = 'active')
`

type GetModelParams struct {
	ID              string
	IncludeDisabled bool
}

func (q *Queries) GetModel(ctx context.Context, arg GetModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, getModel, arg.ID, arg.IncludeDisabled)
	var i Model
	err := row.Scan(
		&i.InternalID,
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.ContextWindow,
		&i.ParameterInfo,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceUpdatedAt,
	)
	return i, err
}

const insertModelPriceTier = `-- name: InsertModelPriceTier :exec
INSERT INTO model_price_tiers (
	model_id, seq, name, min_prompt_tokens, max_prompt_tokens, timezone, weekdays,
	start_minute_of_day, end_minute_of_day,
	input_price_nano_per_million, output_price_nano_per_million,
	cache_write_price_nano_per_million, cache_read_price_nano_per_million
) VALUES (
	$1, $2, $3, $4, $5, $6, $7,
	$8, $9,
	$10, $11,
	$12, $13
)
`

type InsertModelPriceTierParams struct {
	ModelID                       string
	Seq                           int32
	Name                          string
	MinPromptTokens               *int64
	MaxPromptTokens               *int64
	Timezone                      string
	Weekdays                      []int16
	StartMinuteOfDay              *int16
	EndMinuteOfDay                *int16
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
}

func (q *Queries) InsertModelPriceTier(ctx context.Context, arg InsertModelPriceTierParams) error {
	_, err := q.db.Exec(ctx, insertModelPriceTier,
		arg.ModelID,
		arg.Seq,
		arg.Name,
		arg.MinPromptTokens,
		arg.MaxPromptTokens,
		arg.Timezone,
		arg.Weekdays,
		arg.StartMinuteOfDay,
		arg.EndMinuteOfDay,
		arg.InputPriceNanoPerMillion,
		arg.OutputPriceNanoPerMillion,
		arg.CacheWritePriceNanoPerMillion,
		arg.CacheReadPriceNanoPerMillion,
	)
	return err
}

const listModelPriceTiers = `-- name: ListModelPriceTiers :many
SELECT model_id, seq, name, min_prompt_tokens, max_prompt_tokens, timezone, weekdays, start_minute_of_day, end_minute_of_day, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million FROM model_price_tiers
WHERE model_id = ANY($1::text[])
ORDER BY model_id, seq
`

func (q *Queries) ListModelPriceTiers(ctx context.Context, modelIds []string) ([]ModelPriceTier, error) {
	rows, err := q.db.Query(ctx, listModelPriceTiers, modelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelPriceTier
	for rows.Next() {
		var i ModelPriceTier
		if err := rows.Scan(
			&i.ModelID,
			&i.Seq,
			&i.Name,
			&i.MinPromptTokens,
			&i.MaxPromptTokens,
			&i.Timezone,
			&i.Weekdays,
			&i.StartMinuteOfDay,
			&i.EndMinuteOfDay,
			&i.InputPriceNanoPerMillion,
			&i.OutputPriceNanoPerMillion,
			&i.CacheWritePriceNanoPerMillion,
			&i.CacheReadPriceNanoPerMillion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT internal_id, id, name, provider, context_window, parameter_info, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, status, version, created_at, updated_at, price_updated_at FROM models
WHERE ($1::boolean OR status = 'active')
	AND ($2::text = '' OR id ILIKE '%' || $2::text || '%'
		OR name ILIKE '%' || $2::text || '%'
		OR provider ILIKE '%' || $2::text || '%')
ORDER BY provider, name, id
`

type ListModelsParams struct {
	IncludeDisabled bool
	Query           string
}

func (q *Queries) ListModels(ctx context.Context, arg ListModelsParams) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels, arg.IncludeDisabled, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.InternalID,
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.ContextWindow,
			&i.ParameterInfo,
			&i.InputModalities,
			&i.OutputModalities,
			&i.SupportsTools,
			&i.SupportsStructuredOutput,
			&i.SupportsVision,
			&i.InputPriceNanoPerMillion,
			&i.OutputPriceNanoPerMillion,
			&i.CacheWritePriceNanoPerMillion,
			&i.CacheReadPriceNanoPerMillion,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PriceUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelExists = `-- name: ModelExists :one
SELECT EXISTS (SELECT 1 FROM models WHERE id = $1)
`

func (q *Queries) ModelExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, modelExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateModel = `-- name: UpdateModel :one
UPDATE models SET
	name = $1,
	provider = $2,
	context_window = $3,
	parameter_info = $4,
	input_modalities = $5,
	output_modalities = $6,
	supports_tools = $7,
	supports_structured_output = $8,
	supports_vision = $9,
	input_price_nano_per_million = $10,
	output_price_nano_per_million = $11,
	cache_write_price_nano_per_million = $12,
	cache_read_price_nano_per_million = $13,
	status = $14,
	version = version + 1,
	updated_at = now(),
	price_updated_at = CASE
		WHEN input_price_nano_per_million <> $10
			OR output_price_nano_per_million <> $11
			OR cache_write_price_nano_per_million <> $12
			OR cache_read_price_nano_per_million <> $13
			OR $15::boolean
		THEN now()
		ELSE price_updated_at
	END
WHERE id = $16 AND version = $17
RETURNING internal_id, id, name, provider, context_window, parameter_info, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, status, version, created_at, updated_at, price_updated_at
`

type UpdateModelParams struct {
	Name                          string
	Provider                      string
	ContextWindow                 int64
	ParameterInfo                 string
	InputModalities               []string
	OutputModalities              []string
	SupportsTools                 bool
	SupportsStructuredOutput      bool
	SupportsVision                bool
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	Status                        string
	PriceTiersChanged             bool
	ID                            string
	ExpectedVersion               int64
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateModel,
		arg.Name,
		arg.Provider,
		arg.ContextWindow,
		arg.ParameterInfo,
		arg.InputModalities,
		arg.OutputModalities,
		arg.SupportsTools,
		arg.SupportsStructuredOutput,
		arg.SupportsVision,
		arg.InputPriceNanoPerMillion,
		arg.OutputPriceNanoPerMillion,
		arg.CacheWritePriceNanoPerMillion,
		arg.CacheReadPriceNanoPerMillion,
		arg.Status,
		arg.PriceTiersChanged,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Model
	err := row.Scan(
		&i.InternalID,
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.ContextWindow,
		&i.ParameterInfo,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceUpdatedAt,
	)
	return i, err
}
