// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package catalogpg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const deleteTiers = `-- name: DeleteTiers :exec
DELETE FROM model_price_tiers WHERE model_id = $1
`

func (q *Queries) DeleteTiers(ctx context.Context, modelID string) error {
	_, err := q.db.Exec(ctx, deleteTiers, modelID)
	return err
}

const deletedModels = `-- name: DeletedModels :many
SELECT model_id FROM catalog_deleted_models
`

func (q *Queries) DeletedModels(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, deletedModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var model_id string
		if err := rows.Scan(&model_id); err != nil {
			return nil, err
		}
		items = append(items, model_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failSync = `-- name: FailSync :exec
UPDATE catalog_sync SET status='failed', finished_at=now(), error=$1 WHERE id
`

func (q *Queries) FailSync(ctx context.Context, error string) error {
	_, err := q.db.Exec(ctx, failSync, error)
	return err
}

const finishSync = `-- name: FinishSync :exec
UPDATE catalog_sync SET status='succeeded', finished_at=now(), error='', result=$1, report=$2, available_providers=$3 WHERE id
`

type FinishSyncParams struct {
	Result             []byte
	Report             []byte
	AvailableProviders []string
}

func (q *Queries) FinishSync(ctx context.Context, arg FinishSyncParams) error {
	_, err := q.db.Exec(ctx, finishSync, arg.Result, arg.Report, arg.AvailableProviders)
	return err
}

const getModel = `-- name: GetModel :one
SELECT id, display_name, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, enabled, sort_order, provider, context_window, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, parameter_info, created_at, updated_at FROM models WHERE id = $1
`

func (q *Queries) GetModel(ctx context.Context, id string) (Model, error) {
	row := q.db.QueryRow(ctx, getModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.TokenPrices,
		&i.Enabled,
		&i.SortOrder,
		&i.Provider,
		&i.ContextWindow,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.ParameterInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT model_id, ignored, sync_enabled, info FROM model_sources WHERE model_id=$1
`

type GetSourceRow struct {
	ModelID     string
	Ignored     bool
	SyncEnabled bool
	Info        []byte
}

func (q *Queries) GetSource(ctx context.Context, modelID string) (GetSourceRow, error) {
	row := q.db.QueryRow(ctx, getSource, modelID)
	var i GetSourceRow
	err := row.Scan(
		&i.ModelID,
		&i.Ignored,
		&i.SyncEnabled,
		&i.Info,
	)
	return i, err
}

const getSourceRaw = `-- name: GetSourceRaw :one
SELECT raw_record FROM model_sources WHERE model_id=$1 AND NOT ignored
`

func (q *Queries) GetSourceRaw(ctx context.Context, modelID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSourceRaw, modelID)
	var raw_record []byte
	err := row.Scan(&raw_record)
	return raw_record, err
}

const getSyncStatus = `-- name: GetSyncStatus :one
SELECT exchange_rate, providers, providers_configured, available_providers, report, started_at, finished_at, status, error, result FROM catalog_sync WHERE id
`

type GetSyncStatusRow struct {
	ExchangeRate        string
	Providers           []string
	ProvidersConfigured bool
	AvailableProviders  []string
	Report              []byte
	StartedAt           *time.Time
	FinishedAt          *time.Time
	Status              string
	Error               string
	Result              []byte
}

func (q *Queries) GetSyncStatus(ctx context.Context) (GetSyncStatusRow, error) {
	row := q.db.QueryRow(ctx, getSyncStatus)
	var i GetSyncStatusRow
	err := row.Scan(
		&i.ExchangeRate,
		&i.Providers,
		&i.ProvidersConfigured,
		&i.AvailableProviders,
		&i.Report,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Error,
		&i.Result,
	)
	return i, err
}

const ignoreSource = `-- name: IgnoreSource :exec
UPDATE model_sources SET ignored=true,sync_enabled=false WHERE model_id=$1
`

func (q *Queries) IgnoreSource(ctx context.Context, modelID string) error {
	_, err := q.db.Exec(ctx, ignoreSource, modelID)
	return err
}

const insertModel = `-- name: InsertModel :one
INSERT INTO models (
    id, display_name,
    input_price_nano_per_million, output_price_nano_per_million,
    cache_write_price_nano_per_million, cache_read_price_nano_per_million,
    enabled, sort_order, provider, context_window, input_modalities, output_modalities,
    supports_tools, supports_structured_output, supports_vision, parameter_info, token_prices
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, display_name, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, enabled, sort_order, provider, context_window, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, parameter_info, created_at, updated_at
`

type InsertModelParams struct {
	ID                            string
	DisplayName                   string
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	Enabled                       bool
	SortOrder                     int32
	Provider                      string
	ContextWindow                 *int64
	InputModalities               []string
	OutputModalities              []string
	SupportsTools                 bool
	SupportsStructuredOutput      bool
	SupportsVision                bool
	ParameterInfo                 string
	TokenPrices                   []byte
}

func (q *Queries) InsertModel(ctx context.Context, arg InsertModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, insertModel,
		arg.ID,
		arg.DisplayName,
		arg.InputPriceNanoPerMillion,
		arg.OutputPriceNanoPerMillion,
		arg.CacheWritePriceNanoPerMillion,
		arg.CacheReadPriceNanoPerMillion,
		arg.Enabled,
		arg.SortOrder,
		arg.Provider,
		arg.ContextWindow,
		arg.InputModalities,
		arg.OutputModalities,
		arg.SupportsTools,
		arg.SupportsStructuredOutput,
		arg.SupportsVision,
		arg.ParameterInfo,
		arg.TokenPrices,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.TokenPrices,
		&i.Enabled,
		&i.SortOrder,
		&i.Provider,
		&i.ContextWindow,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.ParameterInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTier = `-- name: InsertTier :exec
INSERT INTO model_price_tiers (
    model_id, seq, name, min_prompt_tokens, max_prompt_tokens, timezone, weekdays,
    start_minute_of_day, end_minute_of_day,
    input_price_nano_per_million, output_price_nano_per_million,
    cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, service_tier, thinking_mode
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type InsertTierParams struct {
	ModelID                       string
	Seq                           int32
	Name                          string
	MinPromptTokens               *int64
	MaxPromptTokens               *int64
	Timezone                      string
	Weekdays                      []int16
	StartMinuteOfDay              *int16
	EndMinuteOfDay                *int16
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	TokenPrices                   []byte
	ServiceTier                   string
	ThinkingMode                  string
}

func (q *Queries) InsertTier(ctx context.Context, arg InsertTierParams) error {
	_, err := q.db.Exec(ctx, insertTier,
		arg.ModelID,
		arg.Seq,
		arg.Name,
		arg.MinPromptTokens,
		arg.MaxPromptTokens,
		arg.Timezone,
		arg.Weekdays,
		arg.StartMinuteOfDay,
		arg.EndMinuteOfDay,
		arg.InputPriceNanoPerMillion,
		arg.OutputPriceNanoPerMillion,
		arg.CacheWritePriceNanoPerMillion,
		arg.CacheReadPriceNanoPerMillion,
		arg.TokenPrices,
		arg.ServiceTier,
		arg.ThinkingMode,
	)
	return err
}

const isModelDeleted = `-- name: IsModelDeleted :one
SELECT EXISTS(SELECT 1 FROM catalog_deleted_models WHERE model_id=$1)
`

func (q *Queries) IsModelDeleted(ctx context.Context, modelID string) (bool, error) {
	row := q.db.QueryRow(ctx, isModelDeleted, modelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listManagedSources = `-- name: ListManagedSources :many
SELECT s.model_id,s.source_key,s.info,s.sync_enabled FROM model_sources s JOIN models m ON m.id=s.model_id
WHERE NOT s.ignored ORDER BY s.model_id
`

type ListManagedSourcesRow struct {
	ModelID     string
	SourceKey   string
	Info        []byte
	SyncEnabled bool
}

func (q *Queries) ListManagedSources(ctx context.Context) ([]ListManagedSourcesRow, error) {
	rows, err := q.db.Query(ctx, listManagedSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagedSourcesRow
	for rows.Next() {
		var i ListManagedSourcesRow
		if err := rows.Scan(
			&i.ModelID,
			&i.SourceKey,
			&i.Info,
			&i.SyncEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, display_name, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, enabled, sort_order, provider, context_window, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, parameter_info, created_at, updated_at FROM models
WHERE enabled OR $1::boolean
ORDER BY sort_order, id
`

func (q *Queries) ListModels(ctx context.Context, includeDisabled bool) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels, includeDisabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.InputPriceNanoPerMillion,
			&i.OutputPriceNanoPerMillion,
			&i.CacheWritePriceNanoPerMillion,
			&i.CacheReadPriceNanoPerMillion,
			&i.TokenPrices,
			&i.Enabled,
			&i.SortOrder,
			&i.Provider,
			&i.ContextWindow,
			&i.InputModalities,
			&i.OutputModalities,
			&i.SupportsTools,
			&i.SupportsStructuredOutput,
			&i.SupportsVision,
			&i.ParameterInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT model_id, info, sync_enabled FROM model_sources WHERE model_id=ANY($1::text[]) AND NOT ignored
`

type ListSourcesRow struct {
	ModelID     string
	Info        []byte
	SyncEnabled bool
}

func (q *Queries) ListSources(ctx context.Context, ids []string) ([]ListSourcesRow, error) {
	rows, err := q.db.Query(ctx, listSources, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourcesRow
	for rows.Next() {
		var i ListSourcesRow
		if err := rows.Scan(&i.ModelID, &i.Info, &i.SyncEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiers = `-- name: ListTiers :many
SELECT model_id, seq, token_prices, service_tier, thinking_mode, name, min_prompt_tokens, max_prompt_tokens, timezone, weekdays, start_minute_of_day, end_minute_of_day, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million FROM model_price_tiers
WHERE model_id = ANY($1::text[])
ORDER BY model_id, seq
`

func (q *Queries) ListTiers(ctx context.Context, modelIds []string) ([]ModelPriceTier, error) {
	rows, err := q.db.Query(ctx, listTiers, modelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelPriceTier
	for rows.Next() {
		var i ModelPriceTier
		if err := rows.Scan(
			&i.ModelID,
			&i.Seq,
			&i.TokenPrices,
			&i.ServiceTier,
			&i.ThinkingMode,
			&i.Name,
			&i.MinPromptTokens,
			&i.MaxPromptTokens,
			&i.Timezone,
			&i.Weekdays,
			&i.StartMinuteOfDay,
			&i.EndMinuteOfDay,
			&i.InputPriceNanoPerMillion,
			&i.OutputPriceNanoPerMillion,
			&i.CacheWritePriceNanoPerMillion,
			&i.CacheReadPriceNanoPerMillion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExplicitModelReferences = `-- name: LockExplicitModelReferences :exec
LOCK TABLE calls, api_keys IN SHARE ROW EXCLUSIVE MODE
`

func (q *Queries) LockExplicitModelReferences(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockExplicitModelReferences)
	return err
}

const lockModel = `-- name: LockModel :one
SELECT id, display_name, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, enabled, sort_order, provider, context_window, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, parameter_info, created_at, updated_at FROM models WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockModel(ctx context.Context, id string) (Model, error) {
	row := q.db.QueryRow(ctx, lockModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.TokenPrices,
		&i.Enabled,
		&i.SortOrder,
		&i.Provider,
		&i.ContextWindow,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.ParameterInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockModelWrites = `-- name: LockModelWrites :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,201))
`

func (q *Queries) LockModelWrites(ctx context.Context, modelID string) error {
	_, err := q.db.Exec(ctx, lockModelWrites, modelID)
	return err
}

const lockSyncConfig = `-- name: LockSyncConfig :one
SELECT exchange_rate, providers, providers_configured, config_version FROM catalog_sync WHERE id FOR UPDATE
`

type LockSyncConfigRow struct {
	ExchangeRate        string
	Providers           []string
	ProvidersConfigured bool
	ConfigVersion       int64
}

func (q *Queries) LockSyncConfig(ctx context.Context) (LockSyncConfigRow, error) {
	row := q.db.QueryRow(ctx, lockSyncConfig)
	var i LockSyncConfigRow
	err := row.Scan(
		&i.ExchangeRate,
		&i.Providers,
		&i.ProvidersConfigured,
		&i.ConfigVersion,
	)
	return i, err
}

const modelReferenceReasons = `-- name: ModelReferenceReasons :one
SELECT
 EXISTS(SELECT 1 FROM channel_models WHERE model_id=$1::text) AS channels,
 EXISTS(SELECT 1 FROM calls WHERE model_id=$1::text OR requested_model=$1::text) AS calls,
 EXISTS(SELECT 1 FROM route_prefs WHERE model_id=$1::text) AS routes,
 EXISTS(SELECT 1 FROM api_keys WHERE $1::text=ANY(allowed_models)
   OR model_aliases ? $1::text
   OR EXISTS(SELECT 1 FROM jsonb_each_text(model_aliases) alias WHERE alias.value=$1::text)) AS keys
`

type ModelReferenceReasonsRow struct {
	Channels bool
	Calls    bool
	Routes   bool
	Keys     bool
}

func (q *Queries) ModelReferenceReasons(ctx context.Context, targetID string) (ModelReferenceReasonsRow, error) {
	row := q.db.QueryRow(ctx, modelReferenceReasons, targetID)
	var i ModelReferenceReasonsRow
	err := row.Scan(
		&i.Channels,
		&i.Calls,
		&i.Routes,
		&i.Keys,
	)
	return i, err
}

const releaseSyncLock = `-- name: ReleaseSyncLock :exec
SELECT pg_advisory_unlock(201201)
`

func (q *Queries) ReleaseSyncLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, releaseSyncLock)
	return err
}

const rememberDeletedModel = `-- name: RememberDeletedModel :exec
INSERT INTO catalog_deleted_models(model_id)
 SELECT $1::text
 UNION SELECT regexp_replace(s.source_key,'^.*/','') FROM model_sources s WHERE s.model_id=$1::text AND NOT s.ignored
 ON CONFLICT DO NOTHING
`

func (q *Queries) RememberDeletedModel(ctx context.Context, targetID string) error {
	_, err := q.db.Exec(ctx, rememberDeletedModel, targetID)
	return err
}

const removeOldConflictRecords = `-- name: RemoveOldConflictRecords :exec
DELETE FROM model_sources WHERE ignored AND info->>'status'='conflict'
`

func (q *Queries) RemoveOldConflictRecords(ctx context.Context) error {
	_, err := q.db.Exec(ctx, removeOldConflictRecords)
	return err
}

const removeSource = `-- name: RemoveSource :exec
DELETE FROM model_sources WHERE model_id=$1
`

func (q *Queries) RemoveSource(ctx context.Context, modelID string) error {
	_, err := q.db.Exec(ctx, removeSource, modelID)
	return err
}

const removeUnusedModel = `-- name: RemoveUnusedModel :exec
DELETE FROM models WHERE id=$1
`

func (q *Queries) RemoveUnusedModel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, removeUnusedModel, id)
	return err
}

const seenSource = `-- name: SeenSource :exec
UPDATE model_sources SET seen_at=$2 WHERE model_id=$1
`

type SeenSourceParams struct {
	ModelID string
	SeenAt  time.Time
}

func (q *Queries) SeenSource(ctx context.Context, arg SeenSourceParams) error {
	_, err := q.db.Exec(ctx, seenSource, arg.ModelID, arg.SeenAt)
	return err
}

const setSourceRetention = `-- name: SetSourceRetention :exec
UPDATE model_sources SET info=jsonb_set(jsonb_set(info,'{status}',to_jsonb($1::text)),'{retained_reason}',to_jsonb($2::text)) WHERE model_id=$3::text
`

type SetSourceRetentionParams struct {
	Status   string
	Reason   string
	TargetID string
}

func (q *Queries) SetSourceRetention(ctx context.Context, arg SetSourceRetentionParams) error {
	_, err := q.db.Exec(ctx, setSourceRetention, arg.Status, arg.Reason, arg.TargetID)
	return err
}

const setSyncConfig = `-- name: SetSyncConfig :exec
UPDATE catalog_sync SET exchange_rate=$1, providers=$2, providers_configured=true, config_version=config_version+1 WHERE id
`

type SetSyncConfigParams struct {
	ExchangeRate string
	Providers    []string
}

func (q *Queries) SetSyncConfig(ctx context.Context, arg SetSyncConfigParams) error {
	_, err := q.db.Exec(ctx, setSyncConfig, arg.ExchangeRate, arg.Providers)
	return err
}

const startSync = `-- name: StartSync :one
UPDATE catalog_sync SET status='running', started_at=now(), error='' WHERE id RETURNING exchange_rate, providers, providers_configured, config_version
`

type StartSyncRow struct {
	ExchangeRate        string
	Providers           []string
	ProvidersConfigured bool
	ConfigVersion       int64
}

func (q *Queries) StartSync(ctx context.Context) (StartSyncRow, error) {
	row := q.db.QueryRow(ctx, startSync)
	var i StartSyncRow
	err := row.Scan(
		&i.ExchangeRate,
		&i.Providers,
		&i.ProvidersConfigured,
		&i.ConfigVersion,
	)
	return i, err
}

const trySyncLock = `-- name: TrySyncLock :one
SELECT pg_try_advisory_lock(201201)::boolean
`

func (q *Queries) TrySyncLock(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, trySyncLock)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateModel = `-- name: UpdateModel :one
UPDATE models SET
    display_name = $2,
    input_price_nano_per_million = $3,
    output_price_nano_per_million = $4,
    cache_write_price_nano_per_million = $5,
    cache_read_price_nano_per_million = $6,
    enabled = $7,
    sort_order = $8,
    provider = $9,
    context_window = $10,
    input_modalities = $11,
    output_modalities = $12,
    supports_tools = $13,
    supports_structured_output = $14,
    supports_vision = $15,
    parameter_info = $16,
 token_prices = $17,
    updated_at = now()
WHERE id = $1
RETURNING id, display_name, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, enabled, sort_order, provider, context_window, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, parameter_info, created_at, updated_at
`

type UpdateModelParams struct {
	ID                            string
	DisplayName                   string
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	Enabled                       bool
	SortOrder                     int32
	Provider                      string
	ContextWindow                 *int64
	InputModalities               []string
	OutputModalities              []string
	SupportsTools                 bool
	SupportsStructuredOutput      bool
	SupportsVision                bool
	ParameterInfo                 string
	TokenPrices                   []byte
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateModel,
		arg.ID,
		arg.DisplayName,
		arg.InputPriceNanoPerMillion,
		arg.OutputPriceNanoPerMillion,
		arg.CacheWritePriceNanoPerMillion,
		arg.CacheReadPriceNanoPerMillion,
		arg.Enabled,
		arg.SortOrder,
		arg.Provider,
		arg.ContextWindow,
		arg.InputModalities,
		arg.OutputModalities,
		arg.SupportsTools,
		arg.SupportsStructuredOutput,
		arg.SupportsVision,
		arg.ParameterInfo,
		arg.TokenPrices,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.TokenPrices,
		&i.Enabled,
		&i.SortOrder,
		&i.Provider,
		&i.ContextWindow,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.ParameterInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSourceControl = `-- name: UpdateSourceControl :exec
UPDATE model_sources SET sync_enabled=$2,info=$3 WHERE model_id=$1 AND NOT ignored
`

type UpdateSourceControlParams struct {
	ModelID     string
	SyncEnabled bool
	Info        []byte
}

func (q *Queries) UpdateSourceControl(ctx context.Context, arg UpdateSourceControlParams) error {
	_, err := q.db.Exec(ctx, updateSourceControl, arg.ModelID, arg.SyncEnabled, arg.Info)
	return err
}

const upsertSource = `-- name: UpsertSource :exec
INSERT INTO model_sources(source_key,model_id,raw_record,info,seen_at) VALUES($1,$2,$3,$4,$5)
ON CONFLICT(model_id) DO UPDATE SET source_key=excluded.source_key, ignored=false, raw_record=excluded.raw_record,info=excluded.info,seen_at=excluded.seen_at
`

type UpsertSourceParams struct {
	SourceKey string
	ModelID   string
	RawRecord []byte
	Info      []byte
	SeenAt    time.Time
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) error {
	_, err := q.db.Exec(ctx, upsertSource,
		arg.SourceKey,
		arg.ModelID,
		arg.RawRecord,
		arg.Info,
		arg.SeenAt,
	)
	return err
}
