// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package catalogpg

import (
	"context"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const deleteTiers = `-- name: DeleteTiers :exec
DELETE FROM model_price_tiers WHERE model_id = $1
`

func (q *Queries) DeleteTiers(ctx context.Context, modelID string) error {
	_, err := q.db.Exec(ctx, deleteTiers, modelID)
	return err
}

const getModel = `-- name: GetModel :one
SELECT id, display_name, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, enabled, sort_order, provider, context_window, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, parameter_info, created_at, updated_at FROM models WHERE id = $1
`

func (q *Queries) GetModel(ctx context.Context, id string) (Model, error) {
	row := q.db.QueryRow(ctx, getModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.TokenPrices,
		&i.Enabled,
		&i.SortOrder,
		&i.Provider,
		&i.ContextWindow,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.ParameterInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertModel = `-- name: InsertModel :one
INSERT INTO models (
    id, display_name,
    input_price_nano_per_million, output_price_nano_per_million,
    cache_write_price_nano_per_million, cache_read_price_nano_per_million,
    enabled, sort_order, provider, context_window, input_modalities, output_modalities,
    supports_tools, supports_structured_output, supports_vision, parameter_info, token_prices
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, display_name, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, enabled, sort_order, provider, context_window, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, parameter_info, created_at, updated_at
`

type InsertModelParams struct {
	ID                            string
	DisplayName                   string
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	Enabled                       bool
	SortOrder                     int32
	Provider                      string
	ContextWindow                 *int64
	InputModalities               []string
	OutputModalities              []string
	SupportsTools                 bool
	SupportsStructuredOutput      bool
	SupportsVision                bool
	ParameterInfo                 string
	TokenPrices                   []byte
}

func (q *Queries) InsertModel(ctx context.Context, arg InsertModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, insertModel,
		arg.ID,
		arg.DisplayName,
		arg.InputPriceNanoPerMillion,
		arg.OutputPriceNanoPerMillion,
		arg.CacheWritePriceNanoPerMillion,
		arg.CacheReadPriceNanoPerMillion,
		arg.Enabled,
		arg.SortOrder,
		arg.Provider,
		arg.ContextWindow,
		arg.InputModalities,
		arg.OutputModalities,
		arg.SupportsTools,
		arg.SupportsStructuredOutput,
		arg.SupportsVision,
		arg.ParameterInfo,
		arg.TokenPrices,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.TokenPrices,
		&i.Enabled,
		&i.SortOrder,
		&i.Provider,
		&i.ContextWindow,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.ParameterInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTier = `-- name: InsertTier :exec
INSERT INTO model_price_tiers (
    model_id, seq, name, min_prompt_tokens, max_prompt_tokens, timezone, weekdays,
    start_minute_of_day, end_minute_of_day,
    input_price_nano_per_million, output_price_nano_per_million,
    cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, service_tier, thinking_mode
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type InsertTierParams struct {
	ModelID                       string
	Seq                           int32
	Name                          string
	MinPromptTokens               *int64
	MaxPromptTokens               *int64
	Timezone                      string
	Weekdays                      []int16
	StartMinuteOfDay              *int16
	EndMinuteOfDay                *int16
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	TokenPrices                   []byte
	ServiceTier                   string
	ThinkingMode                  string
}

func (q *Queries) InsertTier(ctx context.Context, arg InsertTierParams) error {
	_, err := q.db.Exec(ctx, insertTier,
		arg.ModelID,
		arg.Seq,
		arg.Name,
		arg.MinPromptTokens,
		arg.MaxPromptTokens,
		arg.Timezone,
		arg.Weekdays,
		arg.StartMinuteOfDay,
		arg.EndMinuteOfDay,
		arg.InputPriceNanoPerMillion,
		arg.OutputPriceNanoPerMillion,
		arg.CacheWritePriceNanoPerMillion,
		arg.CacheReadPriceNanoPerMillion,
		arg.TokenPrices,
		arg.ServiceTier,
		arg.ThinkingMode,
	)
	return err
}

const listModels = `-- name: ListModels :many
SELECT id, display_name, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, enabled, sort_order, provider, context_window, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, parameter_info, created_at, updated_at FROM models
WHERE enabled OR $1::boolean
ORDER BY sort_order, id
`

func (q *Queries) ListModels(ctx context.Context, includeDisabled bool) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels, includeDisabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.InputPriceNanoPerMillion,
			&i.OutputPriceNanoPerMillion,
			&i.CacheWritePriceNanoPerMillion,
			&i.CacheReadPriceNanoPerMillion,
			&i.TokenPrices,
			&i.Enabled,
			&i.SortOrder,
			&i.Provider,
			&i.ContextWindow,
			&i.InputModalities,
			&i.OutputModalities,
			&i.SupportsTools,
			&i.SupportsStructuredOutput,
			&i.SupportsVision,
			&i.ParameterInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiers = `-- name: ListTiers :many
SELECT model_id, seq, token_prices, service_tier, thinking_mode, name, min_prompt_tokens, max_prompt_tokens, timezone, weekdays, start_minute_of_day, end_minute_of_day, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million FROM model_price_tiers
WHERE model_id = ANY($1::text[])
ORDER BY model_id, seq
`

func (q *Queries) ListTiers(ctx context.Context, modelIds []string) ([]ModelPriceTier, error) {
	rows, err := q.db.Query(ctx, listTiers, modelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelPriceTier
	for rows.Next() {
		var i ModelPriceTier
		if err := rows.Scan(
			&i.ModelID,
			&i.Seq,
			&i.TokenPrices,
			&i.ServiceTier,
			&i.ThinkingMode,
			&i.Name,
			&i.MinPromptTokens,
			&i.MaxPromptTokens,
			&i.Timezone,
			&i.Weekdays,
			&i.StartMinuteOfDay,
			&i.EndMinuteOfDay,
			&i.InputPriceNanoPerMillion,
			&i.OutputPriceNanoPerMillion,
			&i.CacheWritePriceNanoPerMillion,
			&i.CacheReadPriceNanoPerMillion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockModel = `-- name: LockModel :one
SELECT id, display_name, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, enabled, sort_order, provider, context_window, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, parameter_info, created_at, updated_at FROM models WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockModel(ctx context.Context, id string) (Model, error) {
	row := q.db.QueryRow(ctx, lockModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.TokenPrices,
		&i.Enabled,
		&i.SortOrder,
		&i.Provider,
		&i.ContextWindow,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.ParameterInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModel = `-- name: UpdateModel :one
UPDATE models SET
    display_name = $2,
    input_price_nano_per_million = $3,
    output_price_nano_per_million = $4,
    cache_write_price_nano_per_million = $5,
    cache_read_price_nano_per_million = $6,
    enabled = $7,
    sort_order = $8,
    provider = $9,
    context_window = $10,
    input_modalities = $11,
    output_modalities = $12,
    supports_tools = $13,
    supports_structured_output = $14,
    supports_vision = $15,
    parameter_info = $16,
 token_prices = $17,
    updated_at = now()
WHERE id = $1
RETURNING id, display_name, input_price_nano_per_million, output_price_nano_per_million, cache_write_price_nano_per_million, cache_read_price_nano_per_million, token_prices, enabled, sort_order, provider, context_window, input_modalities, output_modalities, supports_tools, supports_structured_output, supports_vision, parameter_info, created_at, updated_at
`

type UpdateModelParams struct {
	ID                            string
	DisplayName                   string
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	Enabled                       bool
	SortOrder                     int32
	Provider                      string
	ContextWindow                 *int64
	InputModalities               []string
	OutputModalities              []string
	SupportsTools                 bool
	SupportsStructuredOutput      bool
	SupportsVision                bool
	ParameterInfo                 string
	TokenPrices                   []byte
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateModel,
		arg.ID,
		arg.DisplayName,
		arg.InputPriceNanoPerMillion,
		arg.OutputPriceNanoPerMillion,
		arg.CacheWritePriceNanoPerMillion,
		arg.CacheReadPriceNanoPerMillion,
		arg.Enabled,
		arg.SortOrder,
		arg.Provider,
		arg.ContextWindow,
		arg.InputModalities,
		arg.OutputModalities,
		arg.SupportsTools,
		arg.SupportsStructuredOutput,
		arg.SupportsVision,
		arg.ParameterInfo,
		arg.TokenPrices,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.TokenPrices,
		&i.Enabled,
		&i.SortOrder,
		&i.Provider,
		&i.ContextWindow,
		&i.InputModalities,
		&i.OutputModalities,
		&i.SupportsTools,
		&i.SupportsStructuredOutput,
		&i.SupportsVision,
		&i.ParameterInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
