// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package settingspg

import (
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

type Setting struct {
	ID                       bool
	FeeRateNano              int64
	C2cPaymentTimeoutMinutes int32
	DefaultCreditLimitNano   money.Amount
	DefaultMaxAttempts       int32
	DefaultTtftTimeoutMs     int32
	DefaultTotalTimeoutMs    int32
	DefaultCooldownFailures  int32
	DefaultCooldownSeconds   int32
	ExtraBlockedHosts        []string
	UpdatedAt                time.Time
}
