// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package settingspg

import (
	"context"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const getSettings = `-- name: GetSettings :one
SELECT id, fee_rate_nano, c2c_payment_timeout_minutes, default_credit_limit_nano, default_max_attempts, default_ttft_timeout_ms, default_total_timeout_ms, default_cooldown_failures, default_cooldown_seconds, extra_blocked_hosts, updated_at FROM settings
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.FeeRateNano,
		&i.C2cPaymentTimeoutMinutes,
		&i.DefaultCreditLimitNano,
		&i.DefaultMaxAttempts,
		&i.DefaultTtftTimeoutMs,
		&i.DefaultTotalTimeoutMs,
		&i.DefaultCooldownFailures,
		&i.DefaultCooldownSeconds,
		&i.ExtraBlockedHosts,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSettings = `-- name: LockSettings :one
SELECT id, fee_rate_nano, c2c_payment_timeout_minutes, default_credit_limit_nano, default_max_attempts, default_ttft_timeout_ms, default_total_timeout_ms, default_cooldown_failures, default_cooldown_seconds, extra_blocked_hosts, updated_at FROM settings FOR UPDATE
`

func (q *Queries) LockSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, lockSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.FeeRateNano,
		&i.C2cPaymentTimeoutMinutes,
		&i.DefaultCreditLimitNano,
		&i.DefaultMaxAttempts,
		&i.DefaultTtftTimeoutMs,
		&i.DefaultTotalTimeoutMs,
		&i.DefaultCooldownFailures,
		&i.DefaultCooldownSeconds,
		&i.ExtraBlockedHosts,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET fee_rate_nano = $1,
    c2c_payment_timeout_minutes = $2,
    default_credit_limit_nano = $3,
    default_max_attempts = $4,
    default_ttft_timeout_ms = $5,
    default_total_timeout_ms = $6,
    default_cooldown_failures = $7,
    default_cooldown_seconds = $8,
    extra_blocked_hosts = $9,
    updated_at = now()
RETURNING id, fee_rate_nano, c2c_payment_timeout_minutes, default_credit_limit_nano, default_max_attempts, default_ttft_timeout_ms, default_total_timeout_ms, default_cooldown_failures, default_cooldown_seconds, extra_blocked_hosts, updated_at
`

type UpdateSettingsParams struct {
	FeeRateNano              int64
	C2cPaymentTimeoutMinutes int32
	DefaultCreditLimitNano   money.Amount
	DefaultMaxAttempts       int32
	DefaultTtftTimeoutMs     int32
	DefaultTotalTimeoutMs    int32
	DefaultCooldownFailures  int32
	DefaultCooldownSeconds   int32
	ExtraBlockedHosts        []string
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings,
		arg.FeeRateNano,
		arg.C2cPaymentTimeoutMinutes,
		arg.DefaultCreditLimitNano,
		arg.DefaultMaxAttempts,
		arg.DefaultTtftTimeoutMs,
		arg.DefaultTotalTimeoutMs,
		arg.DefaultCooldownFailures,
		arg.DefaultCooldownSeconds,
		arg.ExtraBlockedHosts,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.FeeRateNano,
		&i.C2cPaymentTimeoutMinutes,
		&i.DefaultCreditLimitNano,
		&i.DefaultMaxAttempts,
		&i.DefaultTtftTimeoutMs,
		&i.DefaultTotalTimeoutMs,
		&i.DefaultCooldownFailures,
		&i.DefaultCooldownSeconds,
		&i.ExtraBlockedHosts,
		&i.UpdatedAt,
	)
	return i, err
}
