// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package channelpg

type ChannelModel struct {
	ChannelID      string
	ModelID        string
	UpstreamModel  string
	MultiplierNano int64
	Formats        []string
	FormatTests    []byte
	Enabled        bool
}
