// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package channelpg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const bumpChannelCredentialRevoked = `-- name: BumpChannelCredentialRevoked :exec
UPDATE channels SET credential_version = credential_version + 1,
	credential_updated_at = now(), version = version + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) BumpChannelCredentialRevoked(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpChannelCredentialRevoked, id)
	return err
}

const bumpChannelVersion = `-- name: BumpChannelVersion :exec
UPDATE channels SET version = version + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) BumpChannelVersion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpChannelVersion, id)
	return err
}

const canViewOfferValidation = `-- name: CanViewOfferValidation :one
SELECT EXISTS (
	SELECT 1 FROM channel_offers offer
	JOIN channel_models channel_model ON channel_model.id = offer.channel_model_id
	JOIN channels c ON c.id = channel_model.channel_id
	JOIN accounts actor ON actor.id = $1
	WHERE offer.id = $2 AND actor.status = 'active' AND NOT actor.must_change_password
		AND (c.owner_account_id = actor.id OR actor.is_admin)
)::boolean
`

type CanViewOfferValidationParams struct {
	ActorAccountID string
	OfferID        string
}

func (q *Queries) CanViewOfferValidation(ctx context.Context, arg CanViewOfferValidationParams) (bool, error) {
	row := q.db.QueryRow(ctx, canViewOfferValidation, arg.ActorAccountID, arg.OfferID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const completeValidationAttempt = `-- name: CompleteValidationAttempt :execrows
UPDATE channel_validation_attempts SET
	status = $1::text, error_category = $2::text,
	http_status = NULLIF($3::integer, 0), raw_error = $4::text,
	raw_error_truncated = $5::boolean, duration_milliseconds = $6::bigint,
	completed_at = GREATEST(clock_timestamp(), started_at)
WHERE id = $7 AND offer_id = $8 AND validation_version = $9 AND attempt_seq = $10
	AND status = 'in_progress'
`

type CompleteValidationAttemptParams struct {
	Status               string
	ErrorCategory        string
	HttpStatus           int32
	RawError             string
	RawErrorTruncated    bool
	DurationMilliseconds int64
	ID                   string
	OfferID              string
	ValidationVersion    int64
	AttemptSeq           int64
}

func (q *Queries) CompleteValidationAttempt(ctx context.Context, arg CompleteValidationAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeValidationAttempt,
		arg.Status,
		arg.ErrorCategory,
		arg.HttpStatus,
		arg.RawError,
		arg.RawErrorTruncated,
		arg.DurationMilliseconds,
		arg.ID,
		arg.OfferID,
		arg.ValidationVersion,
		arg.AttemptSeq,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPublishableOffers = `-- name: CountPublishableOffers :one
SELECT count(*)
FROM channel_offers offer
JOIN channel_models channel_model ON channel_model.id = offer.channel_model_id
JOIN models model ON model.id = channel_model.model_id
JOIN channel_credentials credential ON credential.channel_id = channel_model.channel_id
JOIN channel_validation_attempts attempt
	ON attempt.offer_id = offer.id
	AND attempt.validation_version = offer.validation_version
	AND attempt.attempt_seq = offer.validation_attempt_seq
WHERE channel_model.channel_id = $1 AND offer.status = 'active'
	AND model.status = 'active' AND attempt.status = 'passed'
`

func (q *Queries) CountPublishableOffers(ctx context.Context, channelID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishableOffers, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const credentialInventory = `-- name: CredentialInventory :many
SELECT credential.channel_id, credential.credential_version,
	credential.key_id, credential.nonce, credential.ciphertext
FROM channel_credentials credential
JOIN channels c ON c.id = credential.channel_id
WHERE c.status <> 'deleted'
ORDER BY credential.channel_id
`

type CredentialInventoryRow struct {
	ChannelID         string
	CredentialVersion int64
	KeyID             string
	Nonce             []byte
	Ciphertext        []byte
}

func (q *Queries) CredentialInventory(ctx context.Context) ([]CredentialInventoryRow, error) {
	rows, err := q.db.Query(ctx, credentialInventory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CredentialInventoryRow
	for rows.Next() {
		var i CredentialInventoryRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.CredentialVersion,
			&i.KeyID,
			&i.Nonce,
			&i.Ciphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const credentialTargetsForReencrypt = `-- name: CredentialTargetsForReencrypt :many
SELECT credential.channel_id, credential.credential_version,
	credential.key_id, credential.nonce, credential.ciphertext
FROM channel_credentials credential
JOIN channels c ON c.id = credential.channel_id
WHERE credential.key_id <> $1 AND c.status <> 'deleted'
ORDER BY credential.updated_at, credential.channel_id
LIMIT $2::bigint
`

type CredentialTargetsForReencryptParams struct {
	ActiveKeyID string
	RowLimit    int64
}

type CredentialTargetsForReencryptRow struct {
	ChannelID         string
	CredentialVersion int64
	KeyID             string
	Nonce             []byte
	Ciphertext        []byte
}

func (q *Queries) CredentialTargetsForReencrypt(ctx context.Context, arg CredentialTargetsForReencryptParams) ([]CredentialTargetsForReencryptRow, error) {
	rows, err := q.db.Query(ctx, credentialTargetsForReencrypt, arg.ActiveKeyID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CredentialTargetsForReencryptRow
	for rows.Next() {
		var i CredentialTargetsForReencryptRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.CredentialVersion,
			&i.KeyID,
			&i.Nonce,
			&i.Ciphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM channel_credentials WHERE channel_id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, channelID string) error {
	_, err := q.db.Exec(ctx, deleteCredential, channelID)
	return err
}

const expireValidationAttempts = `-- name: ExpireValidationAttempts :many
UPDATE channel_validation_attempts SET
	status = 'failed', error_category = 'timeout',
	raw_error = 'validation worker did not complete before recovery deadline',
	raw_error_truncated = false,
	duration_milliseconds = GREATEST(0, floor(extract(epoch FROM (clock_timestamp() - started_at)) * 1000))::bigint,
	completed_at = GREATEST(clock_timestamp(), started_at)
WHERE status = 'in_progress' AND started_at < $1::timestamptz
RETURNING offer_id, actor_account_id, validation_version, attempt_seq
`

type ExpireValidationAttemptsRow struct {
	OfferID           string
	ActorAccountID    string
	ValidationVersion int64
	AttemptSeq        int64
}

func (q *Queries) ExpireValidationAttempts(ctx context.Context, before time.Time) ([]ExpireValidationAttemptsRow, error) {
	rows, err := q.db.Query(ctx, expireValidationAttempts, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpireValidationAttemptsRow
	for rows.Next() {
		var i ExpireValidationAttemptsRow
		if err := rows.Scan(
			&i.OfferID,
			&i.ActorAccountID,
			&i.ValidationVersion,
			&i.AttemptSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannel = `-- name: GetChannel :one

SELECT c.id, c.owner_account_id, owner.display_name AS owner_display_name,
	owner.status AS owner_status, owner.must_change_password AS owner_must_change_password,
	c.display_name, c.normalized_base_url,
	(credential.channel_id IS NOT NULL)::boolean AS credential_configured,
	c.credential_version, c.credential_updated_at, c.status, c.version,
	COALESCE(rating.average_rating, '')::text AS average_rating,
	COALESCE(rating.rating_count, 0)::bigint AS rating_count,
	current_rating.score AS current_rating,
	c.created_at, c.updated_at
FROM channels c
JOIN accounts owner ON owner.id = c.owner_account_id
LEFT JOIN channel_credentials credential ON credential.channel_id = c.id
LEFT JOIN LATERAL (
	SELECT round(avg(score)::numeric, 2)::text AS average_rating, count(*) AS rating_count
	FROM channel_ratings WHERE channel_id = c.id
) rating ON true
LEFT JOIN channel_ratings current_rating
	ON current_rating.channel_id = c.id AND current_rating.account_id = $1::uuid
WHERE c.id = $2
`

type GetChannelParams struct {
	ViewerID *string
	ID       string
}

type GetChannelRow struct {
	ID                      string
	OwnerAccountID          string
	OwnerDisplayName        string
	OwnerStatus             string
	OwnerMustChangePassword bool
	DisplayName             string
	NormalizedBaseUrl       string
	CredentialConfigured    bool
	CredentialVersion       int64
	CredentialUpdatedAt     *time.Time
	Status                  string
	Version                 int64
	AverageRating           string
	RatingCount             int64
	CurrentRating           *int16
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

// 渠道领域全部 SQL。锁顺序（先渠道、再渠道模型/报价）由 store.go 中的调用顺序保证。
func (q *Queries) GetChannel(ctx context.Context, arg GetChannelParams) (GetChannelRow, error) {
	row := q.db.QueryRow(ctx, getChannel, arg.ViewerID, arg.ID)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.OwnerDisplayName,
		&i.OwnerStatus,
		&i.OwnerMustChangePassword,
		&i.DisplayName,
		&i.NormalizedBaseUrl,
		&i.CredentialConfigured,
		&i.CredentialVersion,
		&i.CredentialUpdatedAt,
		&i.Status,
		&i.Version,
		&i.AverageRating,
		&i.RatingCount,
		&i.CurrentRating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelModelMultiplier = `-- name: GetChannelModelMultiplier :one
SELECT multiplier_nano FROM channel_models WHERE id = $1
`

func (q *Queries) GetChannelModelMultiplier(ctx context.Context, id string) (money.Amount, error) {
	row := q.db.QueryRow(ctx, getChannelModelMultiplier, id)
	var multiplier_nano money.Amount
	err := row.Scan(&multiplier_nano)
	return multiplier_nano, err
}

const getOffer = `-- name: GetOffer :one
WITH offer_metrics AS (
	SELECT gateway_attempt.offer_id,
		round((count(*) FILTER (WHERE gateway_attempt.status = 'succeeded'))::numeric /
			NULLIF(count(*) FILTER (WHERE gateway_attempt.status IN ('succeeded', 'failed', 'cancelled', 'incomplete')), 0), 4)::text AS success_rate,
		round(avg(gateway_attempt.ttft_milliseconds) FILTER (WHERE gateway_attempt.status = 'succeeded'))::bigint AS ttft_milliseconds,
		round((avg(gateway_attempt.tokens_per_second_nano) FILTER (WHERE gateway_attempt.status = 'succeeded'))::numeric /
			1000000000, 3)::text AS tokens_per_second,
		NULLIF(count(*) FILTER (WHERE gateway_attempt.status IN ('succeeded', 'failed', 'cancelled', 'incomplete')), 0)::bigint AS call_count
	FROM api_call_attempts gateway_attempt
	WHERE gateway_attempt.offer_id = $1
	GROUP BY gateway_attempt.offer_id
), offer_income AS (
	SELECT gateway_call.final_offer_id AS offer_id,
		NULLIF(sum(gateway_settlement.provider_charge_nano), 0)::bigint AS provider_income_nano
	FROM api_call_settlements gateway_settlement
	JOIN api_calls gateway_call ON gateway_call.id = gateway_settlement.call_id
	WHERE gateway_call.status = 'succeeded'
		AND gateway_call.final_offer_id = $1
	GROUP BY gateway_call.final_offer_id
)
SELECT o.id, cm.channel_id, cm.model_id, m.name AS model_name, m.provider AS model_provider, o.protocol,
	o.upstream_model_id, COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano)::bigint AS multiplier_nano,
	o.status, o.validation_version, o.version,
	m.status AS model_status, m.context_window, m.input_price_nano_per_million, m.output_price_nano_per_million,
	m.cache_write_price_nano_per_million, m.cache_read_price_nano_per_million,
	attempt.id AS attempt_id, attempt.attempt_seq, attempt.actor_account_id AS attempt_actor_account_id,
	attempt.status AS attempt_status, attempt.error_category, COALESCE(attempt.http_status, 0)::integer AS http_status,
	attempt.raw_error, attempt.raw_error_truncated, attempt.duration_milliseconds,
	attempt.started_at, attempt.completed_at, o.created_at, o.updated_at,
	gateway_metrics.success_rate, gateway_metrics.ttft_milliseconds,
	gateway_metrics.tokens_per_second, gateway_metrics.call_count,
	gateway_income.provider_income_nano
FROM channel_offers o
JOIN channel_models cm ON cm.id = o.channel_model_id
JOIN models m ON m.id = cm.model_id
LEFT JOIN channel_validation_attempts attempt
	ON attempt.offer_id = o.id
	AND attempt.validation_version = o.validation_version
	AND attempt.attempt_seq = o.validation_attempt_seq
LEFT JOIN offer_metrics gateway_metrics ON gateway_metrics.offer_id = o.id
LEFT JOIN offer_income gateway_income ON gateway_income.offer_id = o.id
WHERE o.id = $1
`

type GetOfferRow struct {
	ID                            string
	ChannelID                     string
	ModelID                       string
	ModelName                     string
	ModelProvider                 string
	Protocol                      string
	UpstreamModelID               string
	MultiplierNano                int64
	Status                        string
	ValidationVersion             int64
	Version                       int64
	ModelStatus                   string
	ContextWindow                 int64
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	AttemptID                     *string
	AttemptSeq                    *int64
	AttemptActorAccountID         *string
	AttemptStatus                 *string
	ErrorCategory                 *string
	HttpStatus                    int32
	RawError                      *string
	RawErrorTruncated             *bool
	DurationMilliseconds          *int64
	StartedAt                     *time.Time
	CompletedAt                   *time.Time
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
	SuccessRate                   *string
	TtftMilliseconds              *int64
	TokensPerSecond               *string
	CallCount                     *int64
	ProviderIncomeNano            *int64
}

func (q *Queries) GetOffer(ctx context.Context, id string) (GetOfferRow, error) {
	row := q.db.QueryRow(ctx, getOffer, id)
	var i GetOfferRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ModelID,
		&i.ModelName,
		&i.ModelProvider,
		&i.Protocol,
		&i.UpstreamModelID,
		&i.MultiplierNano,
		&i.Status,
		&i.ValidationVersion,
		&i.Version,
		&i.ModelStatus,
		&i.ContextWindow,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.AttemptID,
		&i.AttemptSeq,
		&i.AttemptActorAccountID,
		&i.AttemptStatus,
		&i.ErrorCategory,
		&i.HttpStatus,
		&i.RawError,
		&i.RawErrorTruncated,
		&i.DurationMilliseconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuccessRate,
		&i.TtftMilliseconds,
		&i.TokensPerSecond,
		&i.CallCount,
		&i.ProviderIncomeNano,
	)
	return i, err
}

const getRoutingRow = `-- name: GetRoutingRow :one
SELECT cm.channel_id, c.display_name AS channel_display_name, c.owner_account_id, owner.display_name AS owner_display_name,
	owner.status AS owner_status, owner.must_change_password AS owner_must_change_password, c.status AS channel_status,
	cm.model_id, m.name AS model_name, m.provider AS model_provider, m.status AS model_status,
	o.protocol, o.status AS offer_status, cm.multiplier_nano, o.validation_version,
	m.context_window, m.input_price_nano_per_million, m.output_price_nano_per_million,
	m.cache_write_price_nano_per_million, m.cache_read_price_nano_per_million,
	attempt.status AS validation_status, credential.credential_version, credential.key_id,
	credential.nonce, credential.ciphertext, c.normalized_base_url, o.upstream_model_id,
	COALESCE(rating.average_rating::text, '')::text AS average_rating, COALESCE(rating.rating_count, 0)::bigint AS rating_count
FROM channel_offers o
JOIN channel_models cm ON cm.id = o.channel_model_id
JOIN channels c ON c.id = cm.channel_id
JOIN accounts owner ON owner.id = c.owner_account_id
JOIN models m ON m.id = cm.model_id
LEFT JOIN channel_credentials credential
	ON credential.channel_id = c.id AND credential.credential_version = c.credential_version
LEFT JOIN channel_validation_attempts attempt
	ON attempt.offer_id = o.id AND attempt.validation_version = o.validation_version
	AND attempt.attempt_seq = o.validation_attempt_seq
LEFT JOIN LATERAL (
	SELECT round(avg(score)::numeric, 2) AS average_rating, count(*) AS rating_count
	FROM channel_ratings WHERE channel_id = c.id
) rating ON true
WHERE o.id = $1
`

type GetRoutingRowRow struct {
	ChannelID                     string
	ChannelDisplayName            string
	OwnerAccountID                string
	OwnerDisplayName              string
	OwnerStatus                   string
	OwnerMustChangePassword       bool
	ChannelStatus                 string
	ModelID                       string
	ModelName                     string
	ModelProvider                 string
	ModelStatus                   string
	Protocol                      string
	OfferStatus                   string
	MultiplierNano                money.Amount
	ValidationVersion             int64
	ContextWindow                 int64
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	ValidationStatus              *string
	CredentialVersion             *int64
	KeyID                         *string
	Nonce                         []byte
	Ciphertext                    []byte
	NormalizedBaseUrl             string
	UpstreamModelID               string
	AverageRating                 string
	RatingCount                   int64
}

func (q *Queries) GetRoutingRow(ctx context.Context, offerID string) (GetRoutingRowRow, error) {
	row := q.db.QueryRow(ctx, getRoutingRow, offerID)
	var i GetRoutingRowRow
	err := row.Scan(
		&i.ChannelID,
		&i.ChannelDisplayName,
		&i.OwnerAccountID,
		&i.OwnerDisplayName,
		&i.OwnerStatus,
		&i.OwnerMustChangePassword,
		&i.ChannelStatus,
		&i.ModelID,
		&i.ModelName,
		&i.ModelProvider,
		&i.ModelStatus,
		&i.Protocol,
		&i.OfferStatus,
		&i.MultiplierNano,
		&i.ValidationVersion,
		&i.ContextWindow,
		&i.InputPriceNanoPerMillion,
		&i.OutputPriceNanoPerMillion,
		&i.CacheWritePriceNanoPerMillion,
		&i.CacheReadPriceNanoPerMillion,
		&i.ValidationStatus,
		&i.CredentialVersion,
		&i.KeyID,
		&i.Nonce,
		&i.Ciphertext,
		&i.NormalizedBaseUrl,
		&i.UpstreamModelID,
		&i.AverageRating,
		&i.RatingCount,
	)
	return i, err
}

const getValidationTarget = `-- name: GetValidationTarget :one
SELECT cm.channel_id, c.owner_account_id, c.normalized_base_url,
	o.protocol, o.upstream_model_id, o.validation_version, o.validation_attempt_seq,
	credential.credential_version, credential.key_id, credential.nonce, credential.ciphertext
FROM channel_offers o
JOIN channel_models cm ON cm.id = o.channel_model_id
JOIN channels c ON c.id = cm.channel_id
JOIN channel_credentials credential
	ON credential.channel_id = c.id AND credential.credential_version = c.credential_version
JOIN accounts actor ON actor.id = $1
WHERE o.id = $2 AND o.status <> 'deleted' AND c.status <> 'deleted'
	AND actor.status = 'active' AND NOT actor.must_change_password
	AND (c.owner_account_id = actor.id OR actor.is_admin)
	AND c.id = $3
FOR UPDATE OF o
`

type GetValidationTargetParams struct {
	ActorAccountID string
	OfferID        string
	ChannelID      string
}

type GetValidationTargetRow struct {
	ChannelID            string
	OwnerAccountID       string
	NormalizedBaseUrl    string
	Protocol             string
	UpstreamModelID      string
	ValidationVersion    int64
	ValidationAttemptSeq int64
	CredentialVersion    int64
	KeyID                string
	Nonce                []byte
	Ciphertext           []byte
}

func (q *Queries) GetValidationTarget(ctx context.Context, arg GetValidationTargetParams) (GetValidationTargetRow, error) {
	row := q.db.QueryRow(ctx, getValidationTarget, arg.ActorAccountID, arg.OfferID, arg.ChannelID)
	var i GetValidationTargetRow
	err := row.Scan(
		&i.ChannelID,
		&i.OwnerAccountID,
		&i.NormalizedBaseUrl,
		&i.Protocol,
		&i.UpstreamModelID,
		&i.ValidationVersion,
		&i.ValidationAttemptSeq,
		&i.CredentialVersion,
		&i.KeyID,
		&i.Nonce,
		&i.Ciphertext,
	)
	return i, err
}

const insertChannel = `-- name: InsertChannel :execrows
INSERT INTO channels (
	id, owner_account_id, display_name, normalized_base_url,
	credential_version, credential_updated_at
)
SELECT $1::uuid, a.id, $2::text, $3::text, $4::bigint, now()
FROM accounts a
WHERE a.id = $5 AND a.status = 'active' AND NOT a.must_change_password
`

type InsertChannelParams struct {
	ID                string
	DisplayName       string
	NormalizedBaseUrl string
	CredentialVersion int64
	OwnerAccountID    string
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertChannel,
		arg.ID,
		arg.DisplayName,
		arg.NormalizedBaseUrl,
		arg.CredentialVersion,
		arg.OwnerAccountID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertChannelModel = `-- name: InsertChannelModel :one
INSERT INTO channel_models (channel_id, model_id, multiplier_nano)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertChannelModelParams struct {
	ChannelID      string
	ModelID        string
	MultiplierNano money.Amount
}

func (q *Queries) InsertChannelModel(ctx context.Context, arg InsertChannelModelParams) (string, error) {
	row := q.db.QueryRow(ctx, insertChannelModel, arg.ChannelID, arg.ModelID, arg.MultiplierNano)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO channel_credentials (channel_id, credential_version, key_id, nonce, ciphertext)
VALUES ($1, $2, $3, $4, $5)
`

type InsertCredentialParams struct {
	ChannelID         string
	CredentialVersion int64
	KeyID             string
	Nonce             []byte
	Ciphertext        []byte
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential,
		arg.ChannelID,
		arg.CredentialVersion,
		arg.KeyID,
		arg.Nonce,
		arg.Ciphertext,
	)
	return err
}

const insertOffer = `-- name: InsertOffer :exec
INSERT INTO channel_offers (id, channel_model_id, protocol, upstream_model_id)
VALUES ($1, $2, $3, $4)
`

type InsertOfferParams struct {
	ID              string
	ChannelModelID  string
	Protocol        string
	UpstreamModelID string
}

func (q *Queries) InsertOffer(ctx context.Context, arg InsertOfferParams) error {
	_, err := q.db.Exec(ctx, insertOffer,
		arg.ID,
		arg.ChannelModelID,
		arg.Protocol,
		arg.UpstreamModelID,
	)
	return err
}

const insertValidationAttempt = `-- name: InsertValidationAttempt :one
INSERT INTO channel_validation_attempts (
	offer_id, validation_version, attempt_seq, actor_account_id, status
) VALUES ($1, $2, $3, $4, 'in_progress')
RETURNING id, started_at
`

type InsertValidationAttemptParams struct {
	OfferID           string
	ValidationVersion int64
	AttemptSeq        int64
	ActorAccountID    string
}

type InsertValidationAttemptRow struct {
	ID        string
	StartedAt time.Time
}

func (q *Queries) InsertValidationAttempt(ctx context.Context, arg InsertValidationAttemptParams) (InsertValidationAttemptRow, error) {
	row := q.db.QueryRow(ctx, insertValidationAttempt,
		arg.OfferID,
		arg.ValidationVersion,
		arg.AttemptSeq,
		arg.ActorAccountID,
	)
	var i InsertValidationAttemptRow
	err := row.Scan(&i.ID, &i.StartedAt)
	return i, err
}

const isChannelOwner = `-- name: IsChannelOwner :one
SELECT EXISTS (SELECT 1 FROM channels WHERE id = $1 AND owner_account_id = $2)::boolean
`

type IsChannelOwnerParams struct {
	ID             string
	OwnerAccountID string
}

func (q *Queries) IsChannelOwner(ctx context.Context, arg IsChannelOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelOwner, arg.ID, arg.OwnerAccountID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAllChannelIDs = `-- name: ListAllChannelIDs :many
SELECT id FROM channels ORDER BY updated_at DESC, id
`

func (q *Queries) ListAllChannelIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllChannelIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelOffers = `-- name: ListChannelOffers :many

WITH offer_metrics AS (
	SELECT gateway_attempt.offer_id,
		round((count(*) FILTER (WHERE gateway_attempt.status = 'succeeded'))::numeric /
			NULLIF(count(*) FILTER (WHERE gateway_attempt.status IN ('succeeded', 'failed', 'cancelled', 'incomplete')), 0), 4)::text AS success_rate,
		round(avg(gateway_attempt.ttft_milliseconds) FILTER (WHERE gateway_attempt.status = 'succeeded'))::bigint AS ttft_milliseconds,
		round((avg(gateway_attempt.tokens_per_second_nano) FILTER (WHERE gateway_attempt.status = 'succeeded'))::numeric /
			1000000000, 3)::text AS tokens_per_second,
		NULLIF(count(*) FILTER (WHERE gateway_attempt.status IN ('succeeded', 'failed', 'cancelled', 'incomplete')), 0)::bigint AS call_count
	FROM api_call_attempts gateway_attempt
	WHERE gateway_attempt.offer_id IN (
		SELECT scoped_offer.id FROM channel_offers scoped_offer
		JOIN channel_models scoped_model ON scoped_model.id = scoped_offer.channel_model_id
		WHERE scoped_model.channel_id = $1)
	GROUP BY gateway_attempt.offer_id
), offer_income AS (
	SELECT gateway_call.final_offer_id AS offer_id,
		NULLIF(sum(gateway_settlement.provider_charge_nano), 0)::bigint AS provider_income_nano
	FROM api_call_settlements gateway_settlement
	JOIN api_calls gateway_call ON gateway_call.id = gateway_settlement.call_id
	WHERE gateway_call.status = 'succeeded'
		AND gateway_call.final_offer_id IN (
			SELECT scoped_offer.id FROM channel_offers scoped_offer
			JOIN channel_models scoped_model ON scoped_model.id = scoped_offer.channel_model_id
			WHERE scoped_model.channel_id = $1)
	GROUP BY gateway_call.final_offer_id
)
SELECT o.id, cm.channel_id, cm.model_id, m.name AS model_name, m.provider AS model_provider, o.protocol,
	o.upstream_model_id, COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano)::bigint AS multiplier_nano,
	o.status, o.validation_version, o.version,
	m.status AS model_status, m.context_window, m.input_price_nano_per_million, m.output_price_nano_per_million,
	m.cache_write_price_nano_per_million, m.cache_read_price_nano_per_million,
	attempt.id AS attempt_id, attempt.attempt_seq, attempt.actor_account_id AS attempt_actor_account_id,
	attempt.status AS attempt_status, attempt.error_category, COALESCE(attempt.http_status, 0)::integer AS http_status,
	attempt.raw_error, attempt.raw_error_truncated, attempt.duration_milliseconds,
	attempt.started_at, attempt.completed_at, o.created_at, o.updated_at,
	gateway_metrics.success_rate, gateway_metrics.ttft_milliseconds,
	gateway_metrics.tokens_per_second, gateway_metrics.call_count,
	gateway_income.provider_income_nano
FROM channel_offers o
JOIN channel_models cm ON cm.id = o.channel_model_id
JOIN models m ON m.id = cm.model_id
LEFT JOIN channel_validation_attempts attempt
	ON attempt.offer_id = o.id
	AND attempt.validation_version = o.validation_version
	AND attempt.attempt_seq = o.validation_attempt_seq
LEFT JOIN offer_metrics gateway_metrics ON gateway_metrics.offer_id = o.id
LEFT JOIN offer_income gateway_income ON gateway_income.offer_id = o.id
WHERE cm.channel_id = $1 AND ($2::boolean OR o.status <> 'deleted')
ORDER BY m.provider, m.name, o.protocol, o.created_at, o.id
`

type ListChannelOffersParams struct {
	ChannelID      string
	IncludeDeleted bool
}

type ListChannelOffersRow struct {
	ID                            string
	ChannelID                     string
	ModelID                       string
	ModelName                     string
	ModelProvider                 string
	Protocol                      string
	UpstreamModelID               string
	MultiplierNano                int64
	Status                        string
	ValidationVersion             int64
	Version                       int64
	ModelStatus                   string
	ContextWindow                 int64
	InputPriceNanoPerMillion      money.Amount
	OutputPriceNanoPerMillion     money.Amount
	CacheWritePriceNanoPerMillion money.Amount
	CacheReadPriceNanoPerMillion  money.Amount
	AttemptID                     *string
	AttemptSeq                    *int64
	AttemptActorAccountID         *string
	AttemptStatus                 *string
	ErrorCategory                 *string
	HttpStatus                    int32
	RawError                      *string
	RawErrorTruncated             *bool
	DurationMilliseconds          *int64
	StartedAt                     *time.Time
	CompletedAt                   *time.Time
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
	SuccessRate                   *string
	TtftMilliseconds              *int64
	TokensPerSecond               *string
	CallCount                     *int64
	ProviderIncomeNano            *int64
}

// 报价读取与指标连接：ListChannelOffers 与 GetOffer 的列表必须逐列相同，
// store.go 靠结构体转换共用一个映射函数（sqlc 没有片段复用）。
func (q *Queries) ListChannelOffers(ctx context.Context, arg ListChannelOffersParams) ([]ListChannelOffersRow, error) {
	rows, err := q.db.Query(ctx, listChannelOffers, arg.ChannelID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelOffersRow
	for rows.Next() {
		var i ListChannelOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ModelID,
			&i.ModelName,
			&i.ModelProvider,
			&i.Protocol,
			&i.UpstreamModelID,
			&i.MultiplierNano,
			&i.Status,
			&i.ValidationVersion,
			&i.Version,
			&i.ModelStatus,
			&i.ContextWindow,
			&i.InputPriceNanoPerMillion,
			&i.OutputPriceNanoPerMillion,
			&i.CacheWritePriceNanoPerMillion,
			&i.CacheReadPriceNanoPerMillion,
			&i.AttemptID,
			&i.AttemptSeq,
			&i.AttemptActorAccountID,
			&i.AttemptStatus,
			&i.ErrorCategory,
			&i.HttpStatus,
			&i.RawError,
			&i.RawErrorTruncated,
			&i.DurationMilliseconds,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuccessRate,
			&i.TtftMilliseconds,
			&i.TokensPerSecond,
			&i.CallCount,
			&i.ProviderIncomeNano,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketOffers = `-- name: ListMarketOffers :many
WITH offer_metrics AS (
	SELECT gateway_attempt.offer_id,
		round((count(*) FILTER (WHERE gateway_attempt.status = 'succeeded'))::numeric /
			NULLIF(count(*) FILTER (WHERE gateway_attempt.status IN ('succeeded', 'failed', 'cancelled', 'incomplete')), 0), 4)::text AS success_rate,
		round(avg(gateway_attempt.ttft_milliseconds) FILTER (WHERE gateway_attempt.status = 'succeeded'))::bigint AS ttft_milliseconds,
		round((avg(gateway_attempt.tokens_per_second_nano) FILTER (WHERE gateway_attempt.status = 'succeeded'))::numeric /
			1000000000, 3)::text AS tokens_per_second,
		NULLIF(count(*) FILTER (WHERE gateway_attempt.status IN ('succeeded', 'failed', 'cancelled', 'incomplete')), 0)::bigint AS call_count
	FROM api_call_attempts gateway_attempt
	GROUP BY gateway_attempt.offer_id
), candidates AS (
	SELECT o.id AS offer_id, cm.channel_id, c.display_name AS channel_name,
		owner.id AS owner_account_id, owner.display_name AS owner_name, cm.model_id, m.name AS model_name,
		m.provider AS model_provider, o.protocol, COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano) AS multiplier_nano,
		CASE WHEN m.input_price_nano_per_million BETWEEN 0 AND 100000000000000
				AND COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano) BETWEEN 0 AND 1000000000000
			THEN ceil(m.input_price_nano_per_million::numeric * COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano)::numeric / 1000000000)::bigint END AS input_price_nano,
		CASE WHEN m.output_price_nano_per_million BETWEEN 0 AND 100000000000000
				AND COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano) BETWEEN 0 AND 1000000000000
			THEN ceil(m.output_price_nano_per_million::numeric * COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano)::numeric / 1000000000)::bigint END AS output_price_nano,
		CASE WHEN m.cache_write_price_nano_per_million BETWEEN 0 AND 100000000000000
				AND COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano) BETWEEN 0 AND 1000000000000
			THEN ceil(m.cache_write_price_nano_per_million::numeric * COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano)::numeric / 1000000000)::bigint END AS cache_write_price_nano,
		CASE WHEN m.cache_read_price_nano_per_million BETWEEN 0 AND 100000000000000
				AND COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano) BETWEEN 0 AND 1000000000000
			THEN ceil(m.cache_read_price_nano_per_million::numeric * COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano)::numeric / 1000000000)::bigint END AS cache_read_price_nano,
		rating.average_rating, COALESCE(rating.rating_count, 0)::bigint AS rating_count, attempt.completed_at AS last_tested_at,
		gateway_metrics.success_rate,
		gateway_metrics.ttft_milliseconds,
		gateway_metrics.tokens_per_second,
		gateway_metrics.call_count,
		(owner.status = 'active' AND NOT owner.must_change_password
			AND c.status = 'published' AND m.status = 'active' AND o.status = 'active'
			AND m.input_price_nano_per_million BETWEEN 0 AND 100000000000000
			AND m.output_price_nano_per_million BETWEEN 0 AND 100000000000000
			AND m.cache_write_price_nano_per_million BETWEEN 0 AND 100000000000000
			AND m.cache_read_price_nano_per_million BETWEEN 0 AND 100000000000000
			AND COALESCE(o.deleted_multiplier_nano, cm.multiplier_nano) BETWEEN 0 AND 1000000000000
			AND credential.channel_id IS NOT NULL AND attempt.status = 'passed')::boolean AS eligible
	FROM channel_offers o
	JOIN channel_models cm ON cm.id = o.channel_model_id
	JOIN channels c ON c.id = cm.channel_id
	JOIN accounts owner ON owner.id = c.owner_account_id
	JOIN models m ON m.id = cm.model_id
	LEFT JOIN channel_credentials credential
		ON credential.channel_id = c.id AND credential.credential_version = c.credential_version
	LEFT JOIN channel_validation_attempts attempt
		ON attempt.offer_id = o.id AND attempt.validation_version = o.validation_version
		AND attempt.attempt_seq = o.validation_attempt_seq
	LEFT JOIN LATERAL (
		SELECT round(avg(score)::numeric, 2) AS average_rating, count(*) AS rating_count
		FROM channel_ratings WHERE channel_id = c.id
	) rating ON true
	LEFT JOIN offer_metrics gateway_metrics ON gateway_metrics.offer_id = o.id
), keyed AS (
	SELECT offer_id, channel_id, channel_name, owner_account_id, owner_name, model_id, model_name,
		model_provider, protocol, multiplier_nano,
		input_price_nano, output_price_nano, cache_write_price_nano, cache_read_price_nano,
		average_rating, rating_count, last_tested_at, success_rate, ttft_milliseconds, tokens_per_second,
		call_count, eligible,
		CASE $5::text
			WHEN 'output_price' THEN output_price_nano
			WHEN 'cache_write_price' THEN cache_write_price_nano
			WHEN 'cache_read_price' THEN cache_read_price_nano
			ELSE input_price_nano
		END AS price_key,
		CASE $5::text
			WHEN 'success_rate' THEN success_rate::numeric
			WHEN 'ttft' THEN ttft_milliseconds::numeric
			WHEN 'tps' THEN tokens_per_second::numeric
		END AS metric_key
	FROM candidates
)
SELECT offer_id, channel_id, channel_name, owner_account_id, owner_name,
	model_id, model_name, model_provider, protocol, multiplier_nano::bigint AS multiplier_nano,
	COALESCE(input_price_nano, 0)::bigint AS input_price_nano,
	COALESCE(output_price_nano, 0)::bigint AS output_price_nano,
	COALESCE(cache_write_price_nano, 0)::bigint AS cache_write_price_nano,
	COALESCE(cache_read_price_nano, 0)::bigint AS cache_read_price_nano,
	COALESCE(average_rating::text, '')::text AS average_rating, rating_count, last_tested_at,
	success_rate, ttft_milliseconds, tokens_per_second, call_count
FROM keyed
WHERE eligible
	AND ($1::text = '' OR model_id = $1::text)
	AND ($2::text = '' OR protocol = $2::text)
	AND ($3::text = '' OR owner_name ILIKE '%' || $3::text || '%')
	AND ($4::uuid IS NULL OR CASE
		WHEN $5::text = 'rating' THEN (
			($6::text::numeric IS NOT NULL AND (
				average_rating IS NULL OR average_rating < $6::text::numeric OR
				(average_rating = $6::text::numeric AND (
					rating_count < $7::bigint OR
					(rating_count = $7::bigint AND offer_id > $4::uuid)))))
			OR ($6::text::numeric IS NULL AND average_rating IS NULL AND (
				rating_count < $7::bigint OR
				(rating_count = $7::bigint AND offer_id > $4::uuid)))
		)
		WHEN $5::text IN ('success_rate', 'ttft', 'tps') THEN (
			($6::text::numeric IS NOT NULL AND (
				metric_key IS NULL
				OR CASE WHEN $5::text = 'ttft'
					THEN metric_key > $6::text::numeric
					ELSE metric_key < $6::text::numeric END
				OR (metric_key = $6::text::numeric AND offer_id > $4::uuid)))
			OR ($6::text::numeric IS NULL AND metric_key IS NULL AND offer_id > $4::uuid)
		)
		ELSE (price_key > $8::bigint
			OR (price_key = $8::bigint AND offer_id > $4::uuid))
	END)
ORDER BY
	CASE WHEN $5::text NOT IN ('rating', 'success_rate', 'ttft', 'tps') THEN price_key END ASC,
	CASE WHEN $5::text = 'rating' THEN average_rating END DESC NULLS LAST,
	CASE WHEN $5::text = 'rating' THEN rating_count END DESC,
	CASE WHEN $5::text IN ('success_rate', 'tps') THEN metric_key END DESC NULLS LAST,
	CASE WHEN $5::text = 'ttft' THEN metric_key END ASC NULLS LAST,
	offer_id ASC
LIMIT $9::bigint
`

type ListMarketOffersParams struct {
	ModelID           string
	Protocol          string
	OwnerQuery        string
	CursorOfferID     *string
	Sort              string
	CursorMetric      *string
	CursorRatingCount int64
	CursorPrice       int64
	RowLimit          int64
}

type ListMarketOffersRow struct {
	OfferID             string
	ChannelID           string
	ChannelName         string
	OwnerAccountID      string
	OwnerName           string
	ModelID             string
	ModelName           string
	ModelProvider       string
	Protocol            string
	MultiplierNano      int64
	InputPriceNano      int64
	OutputPriceNano     int64
	CacheWritePriceNano int64
	CacheReadPriceNano  int64
	AverageRating       string
	RatingCount         int64
	LastTestedAt        *time.Time
	SuccessRate         *string
	TtftMilliseconds    *int64
	TokensPerSecond     *string
	CallCount           *int64
}

// 市场列表保留为单条查询：八种排序用 sort 参数选择排序键，ORDER BY 与键集游标条件
// 都以 CASE 分支表达。原手写版本按排序拼接 SQL 文本，这里改为固定文本以便 sqlc 检查。
// 排序键与方向（与旧实现一致，末位总是 offer_id ASC）：
//
//	价格类（input/output/cache_write/cache_read，其余未知值按 input_price）：price ASC
//	rating：average_rating DESC NULLS LAST, rating_count DESC
//	success_rate / tps：metric DESC NULLS LAST；ttft：metric ASC NULLS LAST
func (q *Queries) ListMarketOffers(ctx context.Context, arg ListMarketOffersParams) ([]ListMarketOffersRow, error) {
	rows, err := q.db.Query(ctx, listMarketOffers,
		arg.ModelID,
		arg.Protocol,
		arg.OwnerQuery,
		arg.CursorOfferID,
		arg.Sort,
		arg.CursorMetric,
		arg.CursorRatingCount,
		arg.CursorPrice,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketOffersRow
	for rows.Next() {
		var i ListMarketOffersRow
		if err := rows.Scan(
			&i.OfferID,
			&i.ChannelID,
			&i.ChannelName,
			&i.OwnerAccountID,
			&i.OwnerName,
			&i.ModelID,
			&i.ModelName,
			&i.ModelProvider,
			&i.Protocol,
			&i.MultiplierNano,
			&i.InputPriceNano,
			&i.OutputPriceNano,
			&i.CacheWritePriceNano,
			&i.CacheReadPriceNano,
			&i.AverageRating,
			&i.RatingCount,
			&i.LastTestedAt,
			&i.SuccessRate,
			&i.TtftMilliseconds,
			&i.TokensPerSecond,
			&i.CallCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerChannelIDs = `-- name: ListOwnerChannelIDs :many
SELECT id FROM channels WHERE owner_account_id = $1 ORDER BY updated_at DESC, id
`

func (q *Queries) ListOwnerChannelIDs(ctx context.Context, ownerAccountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listOwnerChannelIDs, ownerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidationAttempts = `-- name: ListValidationAttempts :many
SELECT attempt.id, attempt.offer_id, attempt.validation_version,
	attempt.attempt_seq, attempt.actor_account_id, attempt.status,
	attempt.error_category, COALESCE(attempt.http_status, 0)::integer AS http_status,
	attempt.raw_error, attempt.raw_error_truncated,
	attempt.duration_milliseconds, attempt.started_at, attempt.completed_at
FROM channel_validation_attempts attempt
JOIN channel_offers offer ON offer.id = attempt.offer_id
JOIN channel_models channel_model ON channel_model.id = offer.channel_model_id
JOIN channels c ON c.id = channel_model.channel_id
JOIN accounts actor ON actor.id = $1
WHERE attempt.offer_id = $2
	AND actor.status = 'active' AND NOT actor.must_change_password
	AND (c.owner_account_id = actor.id OR actor.is_admin)
ORDER BY attempt.validation_version DESC, attempt.attempt_seq DESC
LIMIT $3::bigint
`

type ListValidationAttemptsParams struct {
	ActorAccountID string
	OfferID        string
	RowLimit       int64
}

type ListValidationAttemptsRow struct {
	ID                   string
	OfferID              string
	ValidationVersion    int64
	AttemptSeq           int64
	ActorAccountID       string
	Status               string
	ErrorCategory        string
	HttpStatus           int32
	RawError             string
	RawErrorTruncated    bool
	DurationMilliseconds *int64
	StartedAt            time.Time
	CompletedAt          *time.Time
}

func (q *Queries) ListValidationAttempts(ctx context.Context, arg ListValidationAttemptsParams) ([]ListValidationAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listValidationAttempts, arg.ActorAccountID, arg.OfferID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListValidationAttemptsRow
	for rows.Next() {
		var i ListValidationAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.ValidationVersion,
			&i.AttemptSeq,
			&i.ActorAccountID,
			&i.Status,
			&i.ErrorCategory,
			&i.HttpStatus,
			&i.RawError,
			&i.RawErrorTruncated,
			&i.DurationMilliseconds,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChannelForAdmin = `-- name: LockChannelForAdmin :one
SELECT c.status, c.version, c.owner_account_id
FROM channels c
WHERE c.id = $1 AND EXISTS (
	SELECT 1 FROM accounts actor WHERE actor.id = $2 AND actor.status = 'active' AND actor.is_admin
) FOR UPDATE
`

type LockChannelForAdminParams struct {
	ID             string
	ActorAccountID string
}

type LockChannelForAdminRow struct {
	Status         string
	Version        int64
	OwnerAccountID string
}

func (q *Queries) LockChannelForAdmin(ctx context.Context, arg LockChannelForAdminParams) (LockChannelForAdminRow, error) {
	row := q.db.QueryRow(ctx, lockChannelForAdmin, arg.ID, arg.ActorAccountID)
	var i LockChannelForAdminRow
	err := row.Scan(&i.Status, &i.Version, &i.OwnerAccountID)
	return i, err
}

const lockChannelForOwner = `-- name: LockChannelForOwner :one
SELECT c.status, c.version, c.owner_account_id
FROM channels c JOIN accounts owner ON owner.id = c.owner_account_id
WHERE c.id = $1 AND c.owner_account_id = $2
	AND owner.status = 'active' AND NOT owner.must_change_password
FOR UPDATE
`

type LockChannelForOwnerParams struct {
	ID             string
	ActorAccountID string
}

type LockChannelForOwnerRow struct {
	Status         string
	Version        int64
	OwnerAccountID string
}

func (q *Queries) LockChannelForOwner(ctx context.Context, arg LockChannelForOwnerParams) (LockChannelForOwnerRow, error) {
	row := q.db.QueryRow(ctx, lockChannelForOwner, arg.ID, arg.ActorAccountID)
	var i LockChannelForOwnerRow
	err := row.Scan(&i.Status, &i.Version, &i.OwnerAccountID)
	return i, err
}

const lockChannelForReencrypt = `-- name: LockChannelForReencrypt :one
SELECT c.version FROM channels c
JOIN accounts actor ON actor.id = $1
WHERE c.id = $2 AND c.status <> 'deleted' AND actor.status = 'active' AND actor.is_admin
FOR UPDATE OF c
`

type LockChannelForReencryptParams struct {
	ActorAccountID string
	ID             string
}

func (q *Queries) LockChannelForReencrypt(ctx context.Context, arg LockChannelForReencryptParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockChannelForReencrypt, arg.ActorAccountID, arg.ID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const lockChannelForValidation = `-- name: LockChannelForValidation :one
SELECT c.id
FROM channel_offers o
JOIN channel_models cm ON cm.id = o.channel_model_id
JOIN channels c ON c.id = cm.channel_id
JOIN accounts actor ON actor.id = $1
WHERE o.id = $2 AND o.status <> 'deleted' AND c.status <> 'deleted'
	AND actor.status = 'active' AND NOT actor.must_change_password
	AND (c.owner_account_id = actor.id OR actor.is_admin)
FOR UPDATE OF c
`

type LockChannelForValidationParams struct {
	ActorAccountID string
	OfferID        string
}

// 先锁渠道再锁报价，与配置变更同序，目标是一致的 Base URL、凭据与验证版本快照。
func (q *Queries) LockChannelForValidation(ctx context.Context, arg LockChannelForValidationParams) (string, error) {
	row := q.db.QueryRow(ctx, lockChannelForValidation, arg.ActorAccountID, arg.OfferID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockChannelModel = `-- name: LockChannelModel :one
SELECT cm.id, cm.multiplier_nano,
	(SELECT count(*) FROM channel_offers existing_offer
	 WHERE existing_offer.channel_model_id = cm.id AND existing_offer.status <> 'deleted')::bigint AS live_offer_count
FROM channel_models cm
WHERE cm.channel_id = $1 AND cm.model_id = $2
FOR UPDATE OF cm
`

type LockChannelModelParams struct {
	ChannelID string
	ModelID   string
}

type LockChannelModelRow struct {
	ID             string
	MultiplierNano money.Amount
	LiveOfferCount int64
}

func (q *Queries) LockChannelModel(ctx context.Context, arg LockChannelModelParams) (LockChannelModelRow, error) {
	row := q.db.QueryRow(ctx, lockChannelModel, arg.ChannelID, arg.ModelID)
	var i LockChannelModelRow
	err := row.Scan(&i.ID, &i.MultiplierNano, &i.LiveOfferCount)
	return i, err
}

const lockChannelWithCredential = `-- name: LockChannelWithCredential :one
SELECT c.owner_account_id, c.version
FROM channels c JOIN accounts owner ON owner.id = c.owner_account_id
JOIN channel_credentials credential ON credential.channel_id = c.id
WHERE c.id = $1 AND c.owner_account_id = $2 AND c.status <> 'deleted'
	AND owner.status = 'active' AND NOT owner.must_change_password
FOR UPDATE
`

type LockChannelWithCredentialParams struct {
	ID             string
	ActorAccountID string
}

type LockChannelWithCredentialRow struct {
	OwnerAccountID string
	Version        int64
}

func (q *Queries) LockChannelWithCredential(ctx context.Context, arg LockChannelWithCredentialParams) (LockChannelWithCredentialRow, error) {
	row := q.db.QueryRow(ctx, lockChannelWithCredential, arg.ID, arg.ActorAccountID)
	var i LockChannelWithCredentialRow
	err := row.Scan(&i.OwnerAccountID, &i.Version)
	return i, err
}

const lockLiveOwnerChannelVersion = `-- name: LockLiveOwnerChannelVersion :one
SELECT c.version
FROM channels c JOIN accounts owner ON owner.id = c.owner_account_id
WHERE c.id = $1 AND c.owner_account_id = $2 AND c.status <> 'deleted'
	AND owner.status = 'active' AND NOT owner.must_change_password
FOR UPDATE OF c
`

type LockLiveOwnerChannelVersionParams struct {
	ID             string
	OwnerAccountID string
}

func (q *Queries) LockLiveOwnerChannelVersion(ctx context.Context, arg LockLiveOwnerChannelVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockLiveOwnerChannelVersion, arg.ID, arg.OwnerAccountID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const lockModelStatusShared = `-- name: LockModelStatusShared :one
SELECT status FROM models WHERE id = $1 FOR SHARE
`

func (q *Queries) LockModelStatusShared(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockModelStatusShared, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const lockOfferForStatus = `-- name: LockOfferForStatus :one
SELECT o.version, o.status
FROM channel_offers o JOIN channel_models cm ON cm.id = o.channel_model_id
JOIN channels c ON c.id = cm.channel_id JOIN accounts owner ON owner.id = c.owner_account_id
WHERE o.id = $1 AND c.owner_account_id = $2 AND c.status <> 'deleted'
	AND owner.status = 'active' AND NOT owner.must_change_password
FOR UPDATE OF o
`

type LockOfferForStatusParams struct {
	ID             string
	OwnerAccountID string
}

type LockOfferForStatusRow struct {
	Version int64
	Status  string
}

func (q *Queries) LockOfferForStatus(ctx context.Context, arg LockOfferForStatusParams) (LockOfferForStatusRow, error) {
	row := q.db.QueryRow(ctx, lockOfferForStatus, arg.ID, arg.OwnerAccountID)
	var i LockOfferForStatusRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const lockOfferForUpdate = `-- name: LockOfferForUpdate :one
SELECT o.version, o.upstream_model_id, o.protocol, o.channel_model_id, cm.multiplier_nano
FROM channel_offers o JOIN channel_models cm ON cm.id = o.channel_model_id
JOIN channels c ON c.id = cm.channel_id JOIN accounts owner ON owner.id = c.owner_account_id
WHERE o.id = $1 AND c.owner_account_id = $2 AND o.status <> 'deleted' AND c.status <> 'deleted'
	AND owner.status = 'active' AND NOT owner.must_change_password
FOR UPDATE OF cm, o
`

type LockOfferForUpdateParams struct {
	ID             string
	OwnerAccountID string
}

type LockOfferForUpdateRow struct {
	Version         int64
	UpstreamModelID string
	Protocol        string
	ChannelModelID  string
	MultiplierNano  money.Amount
}

func (q *Queries) LockOfferForUpdate(ctx context.Context, arg LockOfferForUpdateParams) (LockOfferForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockOfferForUpdate, arg.ID, arg.OwnerAccountID)
	var i LockOfferForUpdateRow
	err := row.Scan(
		&i.Version,
		&i.UpstreamModelID,
		&i.Protocol,
		&i.ChannelModelID,
		&i.MultiplierNano,
	)
	return i, err
}

const lockOwnerChannel = `-- name: LockOwnerChannel :one
SELECT c.version, c.credential_version, c.normalized_base_url, c.status
FROM channels c JOIN accounts owner ON owner.id = c.owner_account_id
WHERE c.id = $1 AND c.owner_account_id = $2
	AND owner.status = 'active' AND NOT owner.must_change_password
FOR UPDATE
`

type LockOwnerChannelParams struct {
	ID             string
	OwnerAccountID string
}

type LockOwnerChannelRow struct {
	Version           int64
	CredentialVersion int64
	NormalizedBaseUrl string
	Status            string
}

func (q *Queries) LockOwnerChannel(ctx context.Context, arg LockOwnerChannelParams) (LockOwnerChannelRow, error) {
	row := q.db.QueryRow(ctx, lockOwnerChannel, arg.ID, arg.OwnerAccountID)
	var i LockOwnerChannelRow
	err := row.Scan(
		&i.Version,
		&i.CredentialVersion,
		&i.NormalizedBaseUrl,
		&i.Status,
	)
	return i, err
}

const lockRatableChannel = `-- name: LockRatableChannel :one
SELECT c.id
FROM channels c JOIN accounts actor ON actor.id = $1
WHERE c.id = $2 AND c.status IN ('published', 'paused')
	AND actor.status = 'active' AND NOT actor.must_change_password
FOR UPDATE OF c
`

type LockRatableChannelParams struct {
	AccountID string
	ID        string
}

func (q *Queries) LockRatableChannel(ctx context.Context, arg LockRatableChannelParams) (string, error) {
	row := q.db.QueryRow(ctx, lockRatableChannel, arg.AccountID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const replaceCredentialCiphertext = `-- name: ReplaceCredentialCiphertext :execrows
UPDATE channel_credentials SET key_id = $1, nonce = $2, ciphertext = $3, updated_at = now()
WHERE channel_id = $4 AND credential_version = $5
	AND key_id = $6 AND nonce = $7 AND ciphertext = $8
`

type ReplaceCredentialCiphertextParams struct {
	KeyID             string
	Nonce             []byte
	Ciphertext        []byte
	ChannelID         string
	CredentialVersion int64
	OldKeyID          string
	OldNonce          []byte
	OldCiphertext     []byte
}

// 仅当库内密文仍等于读取时的旧值才替换（compare-and-swap）。
func (q *Queries) ReplaceCredentialCiphertext(ctx context.Context, arg ReplaceCredentialCiphertextParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceCredentialCiphertext,
		arg.KeyID,
		arg.Nonce,
		arg.Ciphertext,
		arg.ChannelID,
		arg.CredentialVersion,
		arg.OldKeyID,
		arg.OldNonce,
		arg.OldCiphertext,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetChannelOfferValidation = `-- name: ResetChannelOfferValidation :exec
UPDATE channel_offers o SET validation_version = validation_version + 1,
	validation_attempt_seq = 0, updated_at = now()
FROM channel_models cm
WHERE o.channel_model_id = cm.id AND cm.channel_id = $1 AND o.status <> 'deleted'
`

// 配置、吊销凭据或删除渠道后，渠道下所有未删除报价的验证作废并重新计数。
func (q *Queries) ResetChannelOfferValidation(ctx context.Context, channelID string) error {
	_, err := q.db.Exec(ctx, resetChannelOfferValidation, channelID)
	return err
}

const setOfferAttemptSeq = `-- name: SetOfferAttemptSeq :exec
UPDATE channel_offers SET validation_attempt_seq = $1, updated_at = now()
WHERE id = $2
`

type SetOfferAttemptSeqParams struct {
	AttemptSeq int64
	ID         string
}

func (q *Queries) SetOfferAttemptSeq(ctx context.Context, arg SetOfferAttemptSeqParams) error {
	_, err := q.db.Exec(ctx, setOfferAttemptSeq, arg.AttemptSeq, arg.ID)
	return err
}

const updateChannelConfig = `-- name: UpdateChannelConfig :exec
UPDATE channels SET display_name = $1, normalized_base_url = $2,
	credential_version = $3,
	credential_updated_at = CASE WHEN $4::boolean THEN now() ELSE credential_updated_at END,
	version = version + 1, updated_at = now()
WHERE id = $5
`

type UpdateChannelConfigParams struct {
	DisplayName       string
	NormalizedBaseUrl string
	CredentialVersion int64
	CredentialChanged bool
	ID                string
}

func (q *Queries) UpdateChannelConfig(ctx context.Context, arg UpdateChannelConfigParams) error {
	_, err := q.db.Exec(ctx, updateChannelConfig,
		arg.DisplayName,
		arg.NormalizedBaseUrl,
		arg.CredentialVersion,
		arg.CredentialChanged,
		arg.ID,
	)
	return err
}

const updateChannelModelMultiplier = `-- name: UpdateChannelModelMultiplier :exec
UPDATE channel_models SET multiplier_nano = $1, updated_at = now() WHERE id = $2
`

type UpdateChannelModelMultiplierParams struct {
	MultiplierNano money.Amount
	ID             string
}

func (q *Queries) UpdateChannelModelMultiplier(ctx context.Context, arg UpdateChannelModelMultiplierParams) error {
	_, err := q.db.Exec(ctx, updateChannelModelMultiplier, arg.MultiplierNano, arg.ID)
	return err
}

const updateChannelStatus = `-- name: UpdateChannelStatus :exec
UPDATE channels SET status = $1, version = version + 1, updated_at = now(),
	deleted_at = CASE WHEN $2::boolean THEN now() ELSE NULL END,
	credential_version = credential_version + CASE WHEN $2::boolean THEN 1 ELSE 0 END,
	credential_updated_at = CASE WHEN $2::boolean THEN now() ELSE credential_updated_at END
WHERE id = $3
`

type UpdateChannelStatusParams struct {
	Status  string
	Deleted bool
	ID      string
}

func (q *Queries) UpdateChannelStatus(ctx context.Context, arg UpdateChannelStatusParams) error {
	_, err := q.db.Exec(ctx, updateChannelStatus, arg.Status, arg.Deleted, arg.ID)
	return err
}

const updateOfferStatus = `-- name: UpdateOfferStatus :exec
UPDATE channel_offers offer SET status = $1::text, version = version + 1, updated_at = now(),
	deleted_at = CASE WHEN $1::text = 'deleted' THEN now() ELSE NULL END,
	deleted_multiplier_nano = CASE WHEN $1::text = 'deleted' THEN model.multiplier_nano ELSE NULL END
FROM channel_models model
WHERE offer.id = $2 AND model.id = offer.channel_model_id
`

type UpdateOfferStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateOfferStatus(ctx context.Context, arg UpdateOfferStatusParams) error {
	_, err := q.db.Exec(ctx, updateOfferStatus, arg.Status, arg.ID)
	return err
}

const updateOfferUpstream = `-- name: UpdateOfferUpstream :exec
UPDATE channel_offers SET upstream_model_id = $1::text, version = version + 1,
	validation_version = validation_version + CASE WHEN $2::boolean THEN 1 ELSE 0 END,
	validation_attempt_seq = CASE WHEN $2::boolean THEN 0 ELSE validation_attempt_seq END,
	updated_at = now()
WHERE id = $3
`

type UpdateOfferUpstreamParams struct {
	UpstreamModelID string
	UpstreamChanged bool
	ID              string
}

func (q *Queries) UpdateOfferUpstream(ctx context.Context, arg UpdateOfferUpstreamParams) error {
	_, err := q.db.Exec(ctx, updateOfferUpstream, arg.UpstreamModelID, arg.UpstreamChanged, arg.ID)
	return err
}

const updateSiblingOffers = `-- name: UpdateSiblingOffers :execrows
UPDATE channel_offers SET
	upstream_model_id = CASE WHEN id = $1 THEN $2::text ELSE upstream_model_id END,
	version = version + 1,
	validation_version = validation_version + CASE WHEN id = $1 AND $3::boolean THEN 1 ELSE 0 END,
	validation_attempt_seq = CASE WHEN id = $1 AND $3::boolean THEN 0 ELSE validation_attempt_seq END,
	updated_at = now()
WHERE channel_model_id = $4 AND status <> 'deleted'
`

type UpdateSiblingOffersParams struct {
	OfferID         string
	UpstreamModelID string
	UpstreamChanged bool
	ChannelModelID  string
}

// 倍率变化时同一渠道模型下所有未删除报价一起升版本；仅目标报价可能改上游模型并重置验证。
func (q *Queries) UpdateSiblingOffers(ctx context.Context, arg UpdateSiblingOffersParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSiblingOffers,
		arg.OfferID,
		arg.UpstreamModelID,
		arg.UpstreamChanged,
		arg.ChannelModelID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCredential = `-- name: UpsertCredential :exec
INSERT INTO channel_credentials (channel_id, credential_version, key_id, nonce, ciphertext)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (channel_id) DO UPDATE SET
	credential_version = EXCLUDED.credential_version,
	key_id = EXCLUDED.key_id,
	nonce = EXCLUDED.nonce,
	ciphertext = EXCLUDED.ciphertext,
	configured_at = now(), updated_at = now()
`

type UpsertCredentialParams struct {
	ChannelID         string
	CredentialVersion int64
	KeyID             string
	Nonce             []byte
	Ciphertext        []byte
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertCredential,
		arg.ChannelID,
		arg.CredentialVersion,
		arg.KeyID,
		arg.Nonce,
		arg.Ciphertext,
	)
	return err
}

const upsertRating = `-- name: UpsertRating :exec
INSERT INTO channel_ratings (channel_id, account_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (channel_id, account_id) DO UPDATE SET score = EXCLUDED.score, updated_at = now()
`

type UpsertRatingParams struct {
	ChannelID string
	AccountID string
	Score     int16
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) error {
	_, err := q.db.Exec(ctx, upsertRating, arg.ChannelID, arg.AccountID, arg.Score)
	return err
}
