// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package channelpg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const channelTodayStats = `-- name: ChannelTodayStats :many
SELECT final_channel_id AS channel_id,
       count(*)::bigint AS calls,
       count(*) FILTER (WHERE outcome IN ('succeeded', 'succeeded_unbilled'))::bigint AS ok_calls,
       coalesce(sum(cost_nano), 0)::bigint AS revenue_nano
FROM calls
WHERE final_channel_id = ANY($1::uuid[]) AND created_at >= $2
GROUP BY final_channel_id
`

type ChannelTodayStatsParams struct {
	ChannelIds []string
	Since      time.Time
}

type ChannelTodayStatsRow struct {
	ChannelID   *string
	Calls       int64
	OkCalls     int64
	RevenueNano int64
}

// Statistics since sqlc.arg(since) of the calls whose final channel is one of ids.
func (q *Queries) ChannelTodayStats(ctx context.Context, arg ChannelTodayStatsParams) ([]ChannelTodayStatsRow, error) {
	rows, err := q.db.Query(ctx, channelTodayStats, arg.ChannelIds, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelTodayStatsRow
	for rows.Next() {
		var i ChannelTodayStatsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Calls,
			&i.OkCalls,
			&i.RevenueNano,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChannelModels = `-- name: DeleteChannelModels :exec
DELETE FROM channel_models WHERE channel_id = $1
`

func (q *Queries) DeleteChannelModels(ctx context.Context, channelID string) error {
	_, err := q.db.Exec(ctx, deleteChannelModels, channelID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT c.id, c.owner_id, c.name, c.base_url, c.status, c.suspended_reason, c.user_agent, c.header_rules,
       c.concurrency_limit, c.rpm_limit, c.daily_revenue_cap_nano, c.ttft_timeout_ms, c.total_timeout_ms,
       c.cooldown_failures, c.cooldown_seconds, c.created_at, c.updated_at,
       a.username AS owner_username, a.display_name AS owner_display_name
FROM channels c
JOIN accounts a ON a.id = c.owner_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetChannelRow struct {
	ID                  string
	OwnerID             string
	Name                string
	BaseUrl             string
	Status              string
	SuspendedReason     *string
	UserAgent           *string
	HeaderRules         []byte
	ConcurrencyLimit    *int32
	RpmLimit            *int32
	DailyRevenueCapNano *money.Amount
	TtftTimeoutMs       *int32
	TotalTimeoutMs      *int32
	CooldownFailures    *int32
	CooldownSeconds     *int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	OwnerUsername       string
	OwnerDisplayName    string
}

func (q *Queries) GetChannel(ctx context.Context, id string) (GetChannelRow, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.SuspendedReason,
		&i.UserAgent,
		&i.HeaderRules,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.DailyRevenueCapNano,
		&i.TtftTimeoutMs,
		&i.TotalTimeoutMs,
		&i.CooldownFailures,
		&i.CooldownSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUsername,
		&i.OwnerDisplayName,
	)
	return i, err
}

const getChannelCredential = `-- name: GetChannelCredential :one
SELECT api_key_ciphertext, api_key_nonce, api_key_key_id FROM channels WHERE id = $1 AND deleted_at IS NULL
`

type GetChannelCredentialRow struct {
	ApiKeyCiphertext []byte
	ApiKeyNonce      []byte
	ApiKeyKeyID      string
}

func (q *Queries) GetChannelCredential(ctx context.Context, id string) (GetChannelCredentialRow, error) {
	row := q.db.QueryRow(ctx, getChannelCredential, id)
	var i GetChannelCredentialRow
	err := row.Scan(&i.ApiKeyCiphertext, &i.ApiKeyNonce, &i.ApiKeyKeyID)
	return i, err
}

const getChannelForUpdate = `-- name: GetChannelForUpdate :one
SELECT status FROM channels WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) GetChannelForUpdate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getChannelForUpdate, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertChannel = `-- name: InsertChannel :exec
INSERT INTO channels (
    id, owner_id, name, base_url, api_key_ciphertext, api_key_nonce, api_key_key_id, status,
    user_agent, header_rules, concurrency_limit, rpm_limit, daily_revenue_cap_nano,
    ttft_timeout_ms, total_timeout_ms, cooldown_failures, cooldown_seconds
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
`

type InsertChannelParams struct {
	ID                  string
	OwnerID             string
	Name                string
	BaseUrl             string
	ApiKeyCiphertext    []byte
	ApiKeyNonce         []byte
	ApiKeyKeyID         string
	Status              string
	UserAgent           *string
	HeaderRules         []byte
	ConcurrencyLimit    *int32
	RpmLimit            *int32
	DailyRevenueCapNano *money.Amount
	TtftTimeoutMs       *int32
	TotalTimeoutMs      *int32
	CooldownFailures    *int32
	CooldownSeconds     *int32
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) error {
	_, err := q.db.Exec(ctx, insertChannel,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyCiphertext,
		arg.ApiKeyNonce,
		arg.ApiKeyKeyID,
		arg.Status,
		arg.UserAgent,
		arg.HeaderRules,
		arg.ConcurrencyLimit,
		arg.RpmLimit,
		arg.DailyRevenueCapNano,
		arg.TtftTimeoutMs,
		arg.TotalTimeoutMs,
		arg.CooldownFailures,
		arg.CooldownSeconds,
	)
	return err
}

const insertChannelEvent = `-- name: InsertChannelEvent :exec
INSERT INTO channel_events (channel_id, kind, reason) VALUES ($1, $2, $3)
`

type InsertChannelEventParams struct {
	ChannelID string
	Kind      string
	Reason    string
}

func (q *Queries) InsertChannelEvent(ctx context.Context, arg InsertChannelEventParams) error {
	_, err := q.db.Exec(ctx, insertChannelEvent, arg.ChannelID, arg.Kind, arg.Reason)
	return err
}

const insertChannelModel = `-- name: InsertChannelModel :exec
INSERT INTO channel_models (channel_id, model_id, upstream_model, multiplier_nano, formats, format_tests, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertChannelModelParams struct {
	ChannelID      string
	ModelID        string
	UpstreamModel  string
	MultiplierNano int64
	Formats        []string
	FormatTests    []byte
	Enabled        bool
}

func (q *Queries) InsertChannelModel(ctx context.Context, arg InsertChannelModelParams) error {
	_, err := q.db.Exec(ctx, insertChannelModel,
		arg.ChannelID,
		arg.ModelID,
		arg.UpstreamModel,
		arg.MultiplierNano,
		arg.Formats,
		arg.FormatTests,
		arg.Enabled,
	)
	return err
}

const listAdminChannels = `-- name: ListAdminChannels :many
SELECT c.id, c.owner_id, c.name, c.base_url, c.status, c.suspended_reason, c.user_agent, c.header_rules,
       c.concurrency_limit, c.rpm_limit, c.daily_revenue_cap_nano, c.ttft_timeout_ms, c.total_timeout_ms,
       c.cooldown_failures, c.cooldown_seconds, c.created_at, c.updated_at,
       a.username AS owner_username, a.display_name AS owner_display_name
FROM channels c
JOIN accounts a ON a.id = c.owner_id
WHERE c.deleted_at IS NULL
  AND ($1::text = '' OR c.status = $1)
  AND ($2::text = '' OR c.owner_id::text = $2)
  AND ($3::text = '' OR c.name ILIKE '%' || $3 || '%'
       OR a.username ILIKE '%' || $3 || '%' OR a.display_name ILIKE '%' || $3 || '%')
  AND ($4::timestamptz IS NULL
       OR (c.created_at, c.id) < ($4::timestamptz, $5::uuid))
ORDER BY c.created_at DESC, c.id DESC
LIMIT $6
`

type ListAdminChannelsParams struct {
	Status     string
	OwnerID    string
	Query      string
	BeforeTime *time.Time
	BeforeID   string
	RowLimit   int32
}

type ListAdminChannelsRow struct {
	ID                  string
	OwnerID             string
	Name                string
	BaseUrl             string
	Status              string
	SuspendedReason     *string
	UserAgent           *string
	HeaderRules         []byte
	ConcurrencyLimit    *int32
	RpmLimit            *int32
	DailyRevenueCapNano *money.Amount
	TtftTimeoutMs       *int32
	TotalTimeoutMs      *int32
	CooldownFailures    *int32
	CooldownSeconds     *int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	OwnerUsername       string
	OwnerDisplayName    string
}

func (q *Queries) ListAdminChannels(ctx context.Context, arg ListAdminChannelsParams) ([]ListAdminChannelsRow, error) {
	rows, err := q.db.Query(ctx, listAdminChannels,
		arg.Status,
		arg.OwnerID,
		arg.Query,
		arg.BeforeTime,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminChannelsRow
	for rows.Next() {
		var i ListAdminChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.BaseUrl,
			&i.Status,
			&i.SuspendedReason,
			&i.UserAgent,
			&i.HeaderRules,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.DailyRevenueCapNano,
			&i.TtftTimeoutMs,
			&i.TotalTimeoutMs,
			&i.CooldownFailures,
			&i.CooldownSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUsername,
			&i.OwnerDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelEvents = `-- name: ListChannelEvents :many
SELECT id, kind, reason, created_at FROM channel_events WHERE channel_id = $1 ORDER BY id DESC LIMIT $2
`

type ListChannelEventsParams struct {
	ChannelID string
	RowLimit  int32
}

type ListChannelEventsRow struct {
	ID        int64
	Kind      string
	Reason    string
	CreatedAt time.Time
}

func (q *Queries) ListChannelEvents(ctx context.Context, arg ListChannelEventsParams) ([]ListChannelEventsRow, error) {
	rows, err := q.db.Query(ctx, listChannelEvents, arg.ChannelID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelEventsRow
	for rows.Next() {
		var i ListChannelEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsOfChannels = `-- name: ListModelsOfChannels :many
SELECT cm.channel_id, cm.model_id, cm.upstream_model, cm.multiplier_nano, cm.formats, cm.format_tests, cm.enabled
FROM channel_models cm
WHERE cm.channel_id = ANY($1::uuid[])
ORDER BY cm.channel_id, cm.model_id
`

func (q *Queries) ListModelsOfChannels(ctx context.Context, channelIds []string) ([]ChannelModel, error) {
	rows, err := q.db.Query(ctx, listModelsOfChannels, channelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelModel
	for rows.Next() {
		var i ChannelModel
		if err := rows.Scan(
			&i.ChannelID,
			&i.ModelID,
			&i.UpstreamModel,
			&i.MultiplierNano,
			&i.Formats,
			&i.FormatTests,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerChannels = `-- name: ListOwnerChannels :many
SELECT c.id, c.owner_id, c.name, c.base_url, c.status, c.suspended_reason, c.user_agent, c.header_rules,
       c.concurrency_limit, c.rpm_limit, c.daily_revenue_cap_nano, c.ttft_timeout_ms, c.total_timeout_ms,
       c.cooldown_failures, c.cooldown_seconds, c.created_at, c.updated_at,
       a.username AS owner_username, a.display_name AS owner_display_name
FROM channels c
JOIN accounts a ON a.id = c.owner_id
WHERE c.owner_id = $1 AND c.deleted_at IS NULL
ORDER BY c.created_at DESC, c.id DESC
`

type ListOwnerChannelsRow struct {
	ID                  string
	OwnerID             string
	Name                string
	BaseUrl             string
	Status              string
	SuspendedReason     *string
	UserAgent           *string
	HeaderRules         []byte
	ConcurrencyLimit    *int32
	RpmLimit            *int32
	DailyRevenueCapNano *money.Amount
	TtftTimeoutMs       *int32
	TotalTimeoutMs      *int32
	CooldownFailures    *int32
	CooldownSeconds     *int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	OwnerUsername       string
	OwnerDisplayName    string
}

func (q *Queries) ListOwnerChannels(ctx context.Context, ownerID string) ([]ListOwnerChannelsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerChannels, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerChannelsRow
	for rows.Next() {
		var i ListOwnerChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.BaseUrl,
			&i.Status,
			&i.SuspendedReason,
			&i.UserAgent,
			&i.HeaderRules,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.DailyRevenueCapNano,
			&i.TtftTimeoutMs,
			&i.TotalTimeoutMs,
			&i.CooldownFailures,
			&i.CooldownSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUsername,
			&i.OwnerDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelModelTests = `-- name: SetChannelModelTests :exec
UPDATE channel_models SET format_tests = $3, formats = $4 WHERE channel_id = $1 AND model_id = $2
`

type SetChannelModelTestsParams struct {
	ChannelID   string
	ModelID     string
	FormatTests []byte
	Formats     []string
}

func (q *Queries) SetChannelModelTests(ctx context.Context, arg SetChannelModelTestsParams) error {
	_, err := q.db.Exec(ctx, setChannelModelTests,
		arg.ChannelID,
		arg.ModelID,
		arg.FormatTests,
		arg.Formats,
	)
	return err
}

const softDeleteChannel = `-- name: SoftDeleteChannel :execrows
UPDATE channels SET deleted_at = now(), status = CASE WHEN status = 'suspended' THEN status ELSE 'unlisted' END, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteChannel(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suspendChannel = `-- name: SuspendChannel :exec
UPDATE channels SET status = 'suspended', suspended_reason = $2, updated_at = now() WHERE id = $1
`

type SuspendChannelParams struct {
	ID              string
	SuspendedReason *string
}

func (q *Queries) SuspendChannel(ctx context.Context, arg SuspendChannelParams) error {
	_, err := q.db.Exec(ctx, suspendChannel, arg.ID, arg.SuspendedReason)
	return err
}

const unsuspendChannel = `-- name: UnsuspendChannel :exec
UPDATE channels SET status = 'listed', suspended_reason = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) UnsuspendChannel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unsuspendChannel, id)
	return err
}

const updateChannelAdvanced = `-- name: UpdateChannelAdvanced :exec
UPDATE channels SET
    user_agent = $2, header_rules = $3, concurrency_limit = $4, rpm_limit = $5, daily_revenue_cap_nano = $6,
    ttft_timeout_ms = $7, total_timeout_ms = $8, cooldown_failures = $9, cooldown_seconds = $10, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateChannelAdvancedParams struct {
	ID                  string
	UserAgent           *string
	HeaderRules         []byte
	ConcurrencyLimit    *int32
	RpmLimit            *int32
	DailyRevenueCapNano *money.Amount
	TtftTimeoutMs       *int32
	TotalTimeoutMs      *int32
	CooldownFailures    *int32
	CooldownSeconds     *int32
}

func (q *Queries) UpdateChannelAdvanced(ctx context.Context, arg UpdateChannelAdvancedParams) error {
	_, err := q.db.Exec(ctx, updateChannelAdvanced,
		arg.ID,
		arg.UserAgent,
		arg.HeaderRules,
		arg.ConcurrencyLimit,
		arg.RpmLimit,
		arg.DailyRevenueCapNano,
		arg.TtftTimeoutMs,
		arg.TotalTimeoutMs,
		arg.CooldownFailures,
		arg.CooldownSeconds,
	)
	return err
}

const updateChannelCredential = `-- name: UpdateChannelCredential :exec
UPDATE channels SET api_key_ciphertext = $2, api_key_nonce = $3, api_key_key_id = $4, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateChannelCredentialParams struct {
	ID               string
	ApiKeyCiphertext []byte
	ApiKeyNonce      []byte
	ApiKeyKeyID      string
}

func (q *Queries) UpdateChannelCredential(ctx context.Context, arg UpdateChannelCredentialParams) error {
	_, err := q.db.Exec(ctx, updateChannelCredential,
		arg.ID,
		arg.ApiKeyCiphertext,
		arg.ApiKeyNonce,
		arg.ApiKeyKeyID,
	)
	return err
}

const updateChannelFields = `-- name: UpdateChannelFields :exec
UPDATE channels SET
    name = coalesce($2, name),
    base_url = coalesce($3, base_url),
    status = coalesce($4, status),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateChannelFieldsParams struct {
	ID      string
	Name    *string
	BaseUrl *string
	Status  *string
}

func (q *Queries) UpdateChannelFields(ctx context.Context, arg UpdateChannelFieldsParams) error {
	_, err := q.db.Exec(ctx, updateChannelFields,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.Status,
	)
	return err
}
