// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitypg

import (
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

type Account struct {
	ID                  string
	Username            string
	DisplayName         string
	PasswordHash        string
	PasswordVersion     int64
	MustChangePassword  bool
	IsAdmin             bool
	Status              string
	CreditLimitNano     money.Amount
	DefaultKeyCreatedAt *time.Time
	PasswordChangedAt   *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
