// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package identitypg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const countActiveAdministrators = `-- name: CountActiveAdministrators :one
SELECT count(*) FROM accounts WHERE is_admin AND status = 'active'
`

func (q *Queries) CountActiveAdministrators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdministrators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const defaultCreditLimit = `-- name: DefaultCreditLimit :one
SELECT default_credit_limit_nano FROM settings
`

func (q *Queries) DefaultCreditLimit(ctx context.Context) (money.Amount, error) {
	row := q.db.QueryRow(ctx, defaultCreditLimit)
	var default_credit_limit_nano money.Amount
	err := row.Scan(&default_credit_limit_nano)
	return default_credit_limit_nano, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsByAccount = `-- name: DeleteSessionsByAccount :exec
DELETE FROM sessions WHERE account_id = $1
`

func (q *Queries) DeleteSessionsByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, deleteSessionsByAccount, accountID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, display_name, password_hash, password_version, must_change_password, is_admin, status, credit_limit_nano, default_key_created_at, password_changed_at, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.MustChangePassword,
		&i.IsAdmin,
		&i.Status,
		&i.CreditLimitNano,
		&i.DefaultKeyCreatedAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountBySession = `-- name: GetAccountBySession :one
SELECT a.id, a.username, a.display_name, a.password_hash, a.password_version, a.must_change_password, a.is_admin, a.status, a.credit_limit_nano, a.default_key_created_at, a.password_changed_at, a.created_at, a.updated_at
FROM sessions s
JOIN accounts a ON a.id = s.account_id
WHERE s.token_hash = $1
  AND s.expires_at > $2::timestamptz
  AND s.password_version = a.password_version
  AND a.status = 'active'
`

type GetAccountBySessionParams struct {
	TokenHash []byte
	Now       time.Time
}

func (q *Queries) GetAccountBySession(ctx context.Context, arg GetAccountBySessionParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountBySession, arg.TokenHash, arg.Now)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.MustChangePassword,
		&i.IsAdmin,
		&i.Status,
		&i.CreditLimitNano,
		&i.DefaultKeyCreatedAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, display_name, password_hash, password_version, must_change_password, is_admin, status, credit_limit_nano, default_key_created_at, password_changed_at, created_at, updated_at FROM accounts WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.MustChangePassword,
		&i.IsAdmin,
		&i.Status,
		&i.CreditLimitNano,
		&i.DefaultKeyCreatedAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminAccount = `-- name: GetAdminAccount :one
SELECT a.id, a.username, a.display_name, a.password_hash, a.password_version, a.must_change_password, a.is_admin, a.status, a.credit_limit_nano, a.default_key_created_at, a.password_changed_at, a.created_at, a.updated_at, coalesce(l.balance_nano, 0)::bigint AS balance_nano
FROM accounts a
LEFT JOIN ledger_accounts l ON l.account_id = a.id
WHERE a.id = $1
`

type GetAdminAccountRow struct {
	Account     Account
	BalanceNano int64
}

func (q *Queries) GetAdminAccount(ctx context.Context, id string) (GetAdminAccountRow, error) {
	row := q.db.QueryRow(ctx, getAdminAccount, id)
	var i GetAdminAccountRow
	err := row.Scan(
		&i.Account.ID,
		&i.Account.Username,
		&i.Account.DisplayName,
		&i.Account.PasswordHash,
		&i.Account.PasswordVersion,
		&i.Account.MustChangePassword,
		&i.Account.IsAdmin,
		&i.Account.Status,
		&i.Account.CreditLimitNano,
		&i.Account.DefaultKeyCreatedAt,
		&i.Account.PasswordChangedAt,
		&i.Account.CreatedAt,
		&i.Account.UpdatedAt,
		&i.BalanceNano,
	)
	return i, err
}

const hasAdministrator = `-- name: HasAdministrator :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE is_admin) AS has_administrator
`

func (q *Queries) HasAdministrator(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAdministrator)
	var has_administrator bool
	err := row.Scan(&has_administrator)
	return has_administrator, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (username, display_name, password_hash, is_admin, must_change_password, credit_limit_nano)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, display_name, password_hash, password_version, must_change_password, is_admin, status, credit_limit_nano, default_key_created_at, password_changed_at, created_at, updated_at
`

type InsertAccountParams struct {
	Username           string
	DisplayName        string
	PasswordHash       string
	IsAdmin            bool
	MustChangePassword bool
	CreditLimitNano    money.Amount
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.MustChangePassword,
		arg.CreditLimitNano,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.MustChangePassword,
		&i.IsAdmin,
		&i.Status,
		&i.CreditLimitNano,
		&i.DefaultKeyCreatedAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (token_hash, account_id, password_version, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	TokenHash       []byte
	AccountID       string
	PasswordVersion int64
	ExpiresAt       time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.TokenHash,
		arg.AccountID,
		arg.PasswordVersion,
		arg.ExpiresAt,
	)
	return err
}

const listAdminAccounts = `-- name: ListAdminAccounts :many
SELECT a.id, a.username, a.display_name, a.password_hash, a.password_version, a.must_change_password, a.is_admin, a.status, a.credit_limit_nano, a.default_key_created_at, a.password_changed_at, a.created_at, a.updated_at, coalesce(l.balance_nano, 0)::bigint AS balance_nano
FROM accounts a
LEFT JOIN ledger_accounts l ON l.account_id = a.id
WHERE ($1::text = '' OR a.username ILIKE '%' || $1 || '%' OR a.display_name ILIKE '%' || $1 || '%' OR a.id::text = $1)
  AND ($2::text = '' OR a.status = $2)
  AND a.username > $3::text
ORDER BY a.username
LIMIT $4
`

type ListAdminAccountsParams struct {
	Query         string
	Status        string
	AfterUsername string
	RowLimit      int32
}

type ListAdminAccountsRow struct {
	Account     Account
	BalanceNano int64
}

func (q *Queries) ListAdminAccounts(ctx context.Context, arg ListAdminAccountsParams) ([]ListAdminAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAdminAccounts,
		arg.Query,
		arg.Status,
		arg.AfterUsername,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminAccountsRow
	for rows.Next() {
		var i ListAdminAccountsRow
		if err := rows.Scan(
			&i.Account.ID,
			&i.Account.Username,
			&i.Account.DisplayName,
			&i.Account.PasswordHash,
			&i.Account.PasswordVersion,
			&i.Account.MustChangePassword,
			&i.Account.IsAdmin,
			&i.Account.Status,
			&i.Account.CreditLimitNano,
			&i.Account.DefaultKeyCreatedAt,
			&i.Account.PasswordChangedAt,
			&i.Account.CreatedAt,
			&i.Account.UpdatedAt,
			&i.BalanceNano,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccount = `-- name: LockAccount :one
SELECT id, username, display_name, password_hash, password_version, must_change_password, is_admin, status, credit_limit_nano, default_key_created_at, password_changed_at, created_at, updated_at FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, lockAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.MustChangePassword,
		&i.IsAdmin,
		&i.Status,
		&i.CreditLimitNano,
		&i.DefaultKeyCreatedAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockActiveAdministrators = `-- name: LockActiveAdministrators :exec
SELECT pg_advisory_xact_lock(hashtext('oh-my-aihub:active-administrators'))
`

func (q *Queries) LockActiveAdministrators(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockActiveAdministrators)
	return err
}

const lockBootstrap = `-- name: LockBootstrap :exec
SELECT pg_advisory_xact_lock(hashtext('oh-my-aihub:bootstrap-admin'))
`

func (q *Queries) LockBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockBootstrap)
	return err
}

const replacePassword = `-- name: ReplacePassword :execrows
UPDATE accounts
SET password_hash = $1,
    password_version = password_version + 1,
    must_change_password = $2,
    password_changed_at = $3,
    updated_at = $3
WHERE id = $4
  AND password_version = $5
`

type ReplacePasswordParams struct {
	PasswordHash            string
	MustChangePassword      bool
	ChangedAt               *time.Time
	ID                      string
	ExpectedPasswordVersion int64
}

func (q *Queries) ReplacePassword(ctx context.Context, arg ReplacePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, replacePassword,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.ChangedAt,
		arg.ID,
		arg.ExpectedPasswordVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET display_name = $2, status = $3, credit_limit_nano = $4, is_admin = $5, updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, password_hash, password_version, must_change_password, is_admin, status, credit_limit_nano, default_key_created_at, password_changed_at, created_at, updated_at
`

type UpdateAccountParams struct {
	ID              string
	DisplayName     string
	Status          string
	CreditLimitNano money.Amount
	IsAdmin         bool
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.DisplayName,
		arg.Status,
		arg.CreditLimitNano,
		arg.IsAdmin,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.MustChangePassword,
		&i.IsAdmin,
		&i.Status,
		&i.CreditLimitNano,
		&i.DefaultKeyCreatedAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
