// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package identitypg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const administratorExists = `-- name: AdministratorExists :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE is_admin)
`

func (q *Queries) AdministratorExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, administratorExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActiveAdministrators = `-- name: CountActiveAdministrators :one
SELECT count(*) FROM accounts WHERE is_admin AND status = 'active'
`

func (q *Queries) CountActiveAdministrators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdministrators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsByAccount = `-- name: DeleteSessionsByAccount :exec
DELETE FROM sessions WHERE account_id = $1
`

func (q *Queries) DeleteSessionsByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, deleteSessionsByAccount, accountID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one

SELECT a.id, a.username, a.display_name, a.password_hash, a.password_version, a.version, a.must_change_password, a.is_admin, a.status, a.credit_limit_nano, a.password_changed_at, a.disabled_at, a.created_by, a.created_at, a.updated_at, a.credit_frozen, la.id, la.identity_account_id, la.kind, la.system_code, la.posted_balance_nano, la.asset_reserved_nano, la.spend_authorized_nano, la.version, la.created_at, la.updated_at
FROM accounts a JOIN ledger_accounts la ON la.identity_account_id = a.id
WHERE a.id = $1
`

type GetAccountByIDRow struct {
	Account       Account
	LedgerAccount LedgerAccount
}

// 账户与其账本余额投影总是成对读取：sqlc.embed 让所有查询共享同一映射函数。
func (q *Queries) GetAccountByID(ctx context.Context, id string) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.Account.ID,
		&i.Account.Username,
		&i.Account.DisplayName,
		&i.Account.PasswordHash,
		&i.Account.PasswordVersion,
		&i.Account.Version,
		&i.Account.MustChangePassword,
		&i.Account.IsAdmin,
		&i.Account.Status,
		&i.Account.CreditLimitNano,
		&i.Account.PasswordChangedAt,
		&i.Account.DisabledAt,
		&i.Account.CreatedBy,
		&i.Account.CreatedAt,
		&i.Account.UpdatedAt,
		&i.Account.CreditFrozen,
		&i.LedgerAccount.ID,
		&i.LedgerAccount.IdentityAccountID,
		&i.LedgerAccount.Kind,
		&i.LedgerAccount.SystemCode,
		&i.LedgerAccount.PostedBalanceNano,
		&i.LedgerAccount.AssetReservedNano,
		&i.LedgerAccount.SpendAuthorizedNano,
		&i.LedgerAccount.Version,
		&i.LedgerAccount.CreatedAt,
		&i.LedgerAccount.UpdatedAt,
	)
	return i, err
}

const getAccountBySession = `-- name: GetAccountBySession :one
SELECT a.id, a.username, a.display_name, a.password_hash, a.password_version, a.version, a.must_change_password, a.is_admin, a.status, a.credit_limit_nano, a.password_changed_at, a.disabled_at, a.created_by, a.created_at, a.updated_at, a.credit_frozen, la.id, la.identity_account_id, la.kind, la.system_code, la.posted_balance_nano, la.asset_reserved_nano, la.spend_authorized_nano, la.version, la.created_at, la.updated_at
FROM accounts a
JOIN sessions s ON s.account_id = a.id
JOIN ledger_accounts la ON la.identity_account_id = a.id
WHERE s.token_hash = $1
	AND s.expires_at > $2
	AND s.password_version = a.password_version
	AND a.status = 'active'
`

type GetAccountBySessionParams struct {
	TokenHash []byte
	Now       time.Time
}

type GetAccountBySessionRow struct {
	Account       Account
	LedgerAccount LedgerAccount
}

func (q *Queries) GetAccountBySession(ctx context.Context, arg GetAccountBySessionParams) (GetAccountBySessionRow, error) {
	row := q.db.QueryRow(ctx, getAccountBySession, arg.TokenHash, arg.Now)
	var i GetAccountBySessionRow
	err := row.Scan(
		&i.Account.ID,
		&i.Account.Username,
		&i.Account.DisplayName,
		&i.Account.PasswordHash,
		&i.Account.PasswordVersion,
		&i.Account.Version,
		&i.Account.MustChangePassword,
		&i.Account.IsAdmin,
		&i.Account.Status,
		&i.Account.CreditLimitNano,
		&i.Account.PasswordChangedAt,
		&i.Account.DisabledAt,
		&i.Account.CreatedBy,
		&i.Account.CreatedAt,
		&i.Account.UpdatedAt,
		&i.Account.CreditFrozen,
		&i.LedgerAccount.ID,
		&i.LedgerAccount.IdentityAccountID,
		&i.LedgerAccount.Kind,
		&i.LedgerAccount.SystemCode,
		&i.LedgerAccount.PostedBalanceNano,
		&i.LedgerAccount.AssetReservedNano,
		&i.LedgerAccount.SpendAuthorizedNano,
		&i.LedgerAccount.Version,
		&i.LedgerAccount.CreatedAt,
		&i.LedgerAccount.UpdatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT a.id, a.username, a.display_name, a.password_hash, a.password_version, a.version, a.must_change_password, a.is_admin, a.status, a.credit_limit_nano, a.password_changed_at, a.disabled_at, a.created_by, a.created_at, a.updated_at, a.credit_frozen, la.id, la.identity_account_id, la.kind, la.system_code, la.posted_balance_nano, la.asset_reserved_nano, la.spend_authorized_nano, la.version, la.created_at, la.updated_at
FROM accounts a JOIN ledger_accounts la ON la.identity_account_id = a.id
WHERE a.username = $1
`

type GetAccountByUsernameRow struct {
	Account       Account
	LedgerAccount LedgerAccount
}

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (GetAccountByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i GetAccountByUsernameRow
	err := row.Scan(
		&i.Account.ID,
		&i.Account.Username,
		&i.Account.DisplayName,
		&i.Account.PasswordHash,
		&i.Account.PasswordVersion,
		&i.Account.Version,
		&i.Account.MustChangePassword,
		&i.Account.IsAdmin,
		&i.Account.Status,
		&i.Account.CreditLimitNano,
		&i.Account.PasswordChangedAt,
		&i.Account.DisabledAt,
		&i.Account.CreatedBy,
		&i.Account.CreatedAt,
		&i.Account.UpdatedAt,
		&i.Account.CreditFrozen,
		&i.LedgerAccount.ID,
		&i.LedgerAccount.IdentityAccountID,
		&i.LedgerAccount.Kind,
		&i.LedgerAccount.SystemCode,
		&i.LedgerAccount.PostedBalanceNano,
		&i.LedgerAccount.AssetReservedNano,
		&i.LedgerAccount.SpendAuthorizedNano,
		&i.LedgerAccount.Version,
		&i.LedgerAccount.CreatedAt,
		&i.LedgerAccount.UpdatedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (
	username, display_name, password_hash, must_change_password,
	is_admin, status, disabled_at, credit_limit_nano, created_by
) VALUES (
	$1, $2, $3, $4,
	$5, $6::text, CASE WHEN $6::text = 'disabled' THEN now() END,
	$7, $8
)
RETURNING id
`

type InsertAccountParams struct {
	Username           string
	DisplayName        string
	PasswordHash       string
	MustChangePassword bool
	IsAdmin            bool
	Status             string
	CreditLimitNano    money.Amount
	CreatedBy          *string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (string, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.IsAdmin,
		arg.Status,
		arg.CreditLimitNano,
		arg.CreatedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertBootstrapAdmin = `-- name: InsertBootstrapAdmin :one
INSERT INTO accounts (
	username, display_name, password_hash, must_change_password,
	is_admin, status, credit_limit_nano
) VALUES ($1, $2, $3, $4, true, $5, 0)
RETURNING id
`

type InsertBootstrapAdminParams struct {
	Username           string
	DisplayName        string
	PasswordHash       string
	MustChangePassword bool
	Status             string
}

func (q *Queries) InsertBootstrapAdmin(ctx context.Context, arg InsertBootstrapAdminParams) (string, error) {
	row := q.db.QueryRow(ctx, insertBootstrapAdmin,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.Status,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (token_hash, account_id, password_version, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	TokenHash       []byte
	AccountID       string
	PasswordVersion int64
	ExpiresAt       time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.TokenHash,
		arg.AccountID,
		arg.PasswordVersion,
		arg.ExpiresAt,
	)
	return err
}

const insertUserLedgerAccount = `-- name: InsertUserLedgerAccount :exec
INSERT INTO ledger_accounts (identity_account_id, kind) VALUES ($1::uuid, 'user')
`

func (q *Queries) InsertUserLedgerAccount(ctx context.Context, identityAccountID string) error {
	_, err := q.db.Exec(ctx, insertUserLedgerAccount, identityAccountID)
	return err
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.username, a.display_name, a.password_hash, a.password_version, a.version, a.must_change_password, a.is_admin, a.status, a.credit_limit_nano, a.password_changed_at, a.disabled_at, a.created_by, a.created_at, a.updated_at, a.credit_frozen, la.id, la.identity_account_id, la.kind, la.system_code, la.posted_balance_nano, la.asset_reserved_nano, la.spend_authorized_nano, la.version, la.created_at, la.updated_at
FROM accounts a JOIN ledger_accounts la ON la.identity_account_id = a.id
WHERE $1::text = '' OR a.id::text = $1::text
	OR a.username ILIKE '%' || $1::text || '%'
	OR a.display_name ILIKE '%' || $1::text || '%'
ORDER BY a.created_at DESC
`

type ListAccountsRow struct {
	Account       Account
	LedgerAccount LedgerAccount
}

func (q *Queries) ListAccounts(ctx context.Context, query string) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.Account.ID,
			&i.Account.Username,
			&i.Account.DisplayName,
			&i.Account.PasswordHash,
			&i.Account.PasswordVersion,
			&i.Account.Version,
			&i.Account.MustChangePassword,
			&i.Account.IsAdmin,
			&i.Account.Status,
			&i.Account.CreditLimitNano,
			&i.Account.PasswordChangedAt,
			&i.Account.DisabledAt,
			&i.Account.CreatedBy,
			&i.Account.CreatedAt,
			&i.Account.UpdatedAt,
			&i.Account.CreditFrozen,
			&i.LedgerAccount.ID,
			&i.LedgerAccount.IdentityAccountID,
			&i.LedgerAccount.Kind,
			&i.LedgerAccount.SystemCode,
			&i.LedgerAccount.PostedBalanceNano,
			&i.LedgerAccount.AssetReservedNano,
			&i.LedgerAccount.SpendAuthorizedNano,
			&i.LedgerAccount.Version,
			&i.LedgerAccount.CreatedAt,
			&i.LedgerAccount.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccount = `-- name: LockAccount :exec
SELECT pg_advisory_xact_lock(hashtextextended('oh-my-aihub-account:' || $1::text, 0))
`

// Account policy changes and C2C commands share this stable per-account
// serialization key before taking ledger, identity, order, or hold rows.
func (q *Queries) LockAccount(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, lockAccount, accountID)
	return err
}

const lockAccountForUpdate = `-- name: LockAccountForUpdate :one
SELECT is_admin, status, version FROM accounts WHERE id = $1 FOR UPDATE
`

type LockAccountForUpdateRow struct {
	IsAdmin bool
	Status  string
	Version int64
}

func (q *Queries) LockAccountForUpdate(ctx context.Context, id string) (LockAccountForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockAccountForUpdate, id)
	var i LockAccountForUpdateRow
	err := row.Scan(&i.IsAdmin, &i.Status, &i.Version)
	return i, err
}

const lockAdministratorMembership = `-- name: LockAdministratorMembership :exec
SELECT pg_advisory_xact_lock(hashtext('oh-my-aihub-administrator-membership'))
`

func (q *Queries) LockAdministratorMembership(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAdministratorMembership)
	return err
}

const lockBootstrapAdmin = `-- name: LockBootstrapAdmin :exec
SELECT pg_advisory_xact_lock(hashtext('oh-my-aihub-bootstrap-admin'))
`

func (q *Queries) LockBootstrapAdmin(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockBootstrapAdmin)
	return err
}

const lockLedgerAccountByIdentity = `-- name: LockLedgerAccountByIdentity :one
SELECT 1::int FROM ledger_accounts WHERE identity_account_id = $1::uuid FOR UPDATE
`

// Ledger mutations lock this same row before consulting credit policy.
func (q *Queries) LockLedgerAccountByIdentity(ctx context.Context, identityAccountID string) (int32, error) {
	row := q.db.QueryRow(ctx, lockLedgerAccountByIdentity, identityAccountID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const replaceActivePassword = `-- name: ReplaceActivePassword :execrows
UPDATE accounts
SET password_hash = $1,
	must_change_password = false,
	password_version = password_version + 1,
	password_changed_at = $2::timestamptz,
	updated_at = $2::timestamptz
WHERE id = $3 AND status = 'active' AND password_version = $4
`

type ReplaceActivePasswordParams struct {
	PasswordHash            string
	ChangedAt               time.Time
	ID                      string
	ExpectedPasswordVersion int64
}

func (q *Queries) ReplaceActivePassword(ctx context.Context, arg ReplaceActivePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceActivePassword,
		arg.PasswordHash,
		arg.ChangedAt,
		arg.ID,
		arg.ExpectedPasswordVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetPassword = `-- name: ResetPassword :execrows
UPDATE accounts
SET password_hash = $1,
	must_change_password = true,
	password_version = password_version + 1,
	password_changed_at = $2::timestamptz,
	updated_at = $2::timestamptz
WHERE id = $3 AND password_version = $4
`

type ResetPasswordParams struct {
	PasswordHash            string
	ChangedAt               time.Time
	ID                      string
	ExpectedPasswordVersion int64
}

func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetPassword,
		arg.PasswordHash,
		arg.ChangedAt,
		arg.ID,
		arg.ExpectedPasswordVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccountPolicy = `-- name: UpdateAccountPolicy :execrows
UPDATE accounts
SET status = COALESCE($1::text, status),
	credit_limit_nano = COALESCE($2::bigint, credit_limit_nano),
	is_admin = COALESCE($3::boolean, is_admin),
	credit_frozen = COALESCE($4::boolean, credit_frozen),
	version = version + 1,
	disabled_at = CASE
		WHEN $1::text = 'disabled' AND status <> 'disabled' THEN now()
		WHEN $1::text = 'active' THEN NULL
		ELSE disabled_at
	END,
	updated_at = now()
WHERE id = $5 AND version = $6
`

type UpdateAccountPolicyParams struct {
	Status          *string
	CreditLimitNano *int64
	IsAdmin         *bool
	CreditFrozen    *bool
	ID              string
	ExpectedVersion int64
}

func (q *Queries) UpdateAccountPolicy(ctx context.Context, arg UpdateAccountPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccountPolicy,
		arg.Status,
		arg.CreditLimitNano,
		arg.IsAdmin,
		arg.CreditFrozen,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
