// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package keypg

import (
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

type ApiKey struct {
	ID                string
	OwnerID           string
	Name              string
	Prefix            string
	KeyHash           []byte
	KeyCiphertext     []byte
	KeyNonce          []byte
	KeyKeyID          string
	Status            string
	ExpiresAt         *time.Time
	AllowedModels     []string
	BudgetDailyNano   *money.Amount
	BudgetMonthlyNano *money.Amount
	BudgetTotalNano   *money.Amount
	ModelAliases      []byte
	LastUsedAt        *time.Time
	DeletedAt         *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type RoutePrefChannel struct {
	RoutePrefID string
	ChannelID   string
	Position    int32
	Excluded    bool
}
