// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package keypg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const clearRoutePrefChannels = `-- name: ClearRoutePrefChannels :exec
DELETE FROM route_pref_channels WHERE route_pref_id = $1
`

func (q *Queries) ClearRoutePrefChannels(ctx context.Context, routePrefID string) error {
	_, err := q.db.Exec(ctx, clearRoutePrefChannels, routePrefID)
	return err
}

const countOwnerKeys = `-- name: CountOwnerKeys :one
SELECT count(*)::int FROM api_keys WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountOwnerKeys(ctx context.Context, ownerID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOwnerKeys, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteKeyRoutes = `-- name: DeleteKeyRoutes :exec
DELETE FROM route_prefs WHERE api_key_id = $1
`

func (q *Queries) DeleteKeyRoutes(ctx context.Context, apiKeyID *string) error {
	_, err := q.db.Exec(ctx, deleteKeyRoutes, apiKeyID)
	return err
}

const deleteRoutePref = `-- name: DeleteRoutePref :execrows
DELETE FROM route_prefs
WHERE account_id = $1 AND api_key_id IS NOT DISTINCT FROM $3 AND model_id = $2
`

type DeleteRoutePrefParams struct {
	AccountID string
	ModelID   string
	ApiKeyID  *string
}

func (q *Queries) DeleteRoutePref(ctx context.Context, arg DeleteRoutePrefParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoutePref, arg.AccountID, arg.ModelID, arg.ApiKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getKeyCredential = `-- name: GetKeyCredential :one
SELECT key_ciphertext, key_nonce, key_key_id FROM api_keys WHERE owner_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetKeyCredentialParams struct {
	OwnerID string
	ID      string
}

type GetKeyCredentialRow struct {
	KeyCiphertext []byte
	KeyNonce      []byte
	KeyKeyID      string
}

func (q *Queries) GetKeyCredential(ctx context.Context, arg GetKeyCredentialParams) (GetKeyCredentialRow, error) {
	row := q.db.QueryRow(ctx, getKeyCredential, arg.OwnerID, arg.ID)
	var i GetKeyCredentialRow
	err := row.Scan(&i.KeyCiphertext, &i.KeyNonce, &i.KeyKeyID)
	return i, err
}

const getOwnerKey = `-- name: GetOwnerKey :one
SELECT id, owner_id, name, prefix, key_hash, key_ciphertext, key_nonce, key_key_id, status, expires_at, allowed_models, budget_daily_nano, budget_monthly_nano, budget_total_nano, model_aliases, last_used_at, deleted_at, created_at, updated_at FROM api_keys WHERE owner_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetOwnerKeyParams struct {
	OwnerID string
	ID      string
}

func (q *Queries) GetOwnerKey(ctx context.Context, arg GetOwnerKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getOwnerKey, arg.OwnerID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.KeyCiphertext,
		&i.KeyNonce,
		&i.KeyKeyID,
		&i.Status,
		&i.ExpiresAt,
		&i.AllowedModels,
		&i.BudgetDailyNano,
		&i.BudgetMonthlyNano,
		&i.BudgetTotalNano,
		&i.ModelAliases,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnerKeyForUpdate = `-- name: GetOwnerKeyForUpdate :one
SELECT id, owner_id, name, prefix, key_hash, key_ciphertext, key_nonce, key_key_id, status, expires_at, allowed_models, budget_daily_nano, budget_monthly_nano, budget_total_nano, model_aliases, last_used_at, deleted_at, created_at, updated_at FROM api_keys WHERE owner_id = $1 AND id = $2 AND deleted_at IS NULL FOR UPDATE
`

type GetOwnerKeyForUpdateParams struct {
	OwnerID string
	ID      string
}

func (q *Queries) GetOwnerKeyForUpdate(ctx context.Context, arg GetOwnerKeyForUpdateParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getOwnerKeyForUpdate, arg.OwnerID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.KeyCiphertext,
		&i.KeyNonce,
		&i.KeyKeyID,
		&i.Status,
		&i.ExpiresAt,
		&i.AllowedModels,
		&i.BudgetDailyNano,
		&i.BudgetMonthlyNano,
		&i.BudgetTotalNano,
		&i.ModelAliases,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertKey = `-- name: InsertKey :exec
INSERT INTO api_keys (
    id, owner_id, name, prefix, key_hash, key_ciphertext, key_nonce, key_key_id, status, expires_at,
    allowed_models, budget_daily_nano, budget_monthly_nano, budget_total_nano, model_aliases
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertKeyParams struct {
	ID                string
	OwnerID           string
	Name              string
	Prefix            string
	KeyHash           []byte
	KeyCiphertext     []byte
	KeyNonce          []byte
	KeyKeyID          string
	Status            string
	ExpiresAt         *time.Time
	AllowedModels     []string
	BudgetDailyNano   *money.Amount
	BudgetMonthlyNano *money.Amount
	BudgetTotalNano   *money.Amount
	ModelAliases      []byte
}

func (q *Queries) InsertKey(ctx context.Context, arg InsertKeyParams) error {
	_, err := q.db.Exec(ctx, insertKey,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.KeyCiphertext,
		arg.KeyNonce,
		arg.KeyKeyID,
		arg.Status,
		arg.ExpiresAt,
		arg.AllowedModels,
		arg.BudgetDailyNano,
		arg.BudgetMonthlyNano,
		arg.BudgetTotalNano,
		arg.ModelAliases,
	)
	return err
}

const insertRoutePrefChannel = `-- name: InsertRoutePrefChannel :exec
INSERT INTO route_pref_channels (route_pref_id, channel_id, position, excluded) VALUES ($1, $2, $3, $4)
`

type InsertRoutePrefChannelParams struct {
	RoutePrefID string
	ChannelID   string
	Position    int32
	Excluded    bool
}

func (q *Queries) InsertRoutePrefChannel(ctx context.Context, arg InsertRoutePrefChannelParams) error {
	_, err := q.db.Exec(ctx, insertRoutePrefChannel,
		arg.RoutePrefID,
		arg.ChannelID,
		arg.Position,
		arg.Excluded,
	)
	return err
}

const keyRoutedModels = `-- name: KeyRoutedModels :many
SELECT api_key_id, model_id FROM route_prefs WHERE api_key_id = ANY($1::uuid[]) ORDER BY model_id
`

type KeyRoutedModelsRow struct {
	ApiKeyID *string
	ModelID  string
}

func (q *Queries) KeyRoutedModels(ctx context.Context, keyIds []string) ([]KeyRoutedModelsRow, error) {
	rows, err := q.db.Query(ctx, keyRoutedModels, keyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeyRoutedModelsRow
	for rows.Next() {
		var i KeyRoutedModelsRow
		if err := rows.Scan(&i.ApiKeyID, &i.ModelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const keySpend = `-- name: KeySpend :many
SELECT api_key_id,
       coalesce(sum(cost_nano + fee_nano) FILTER (WHERE created_at >= $1), 0)::bigint AS today_nano,
       coalesce(sum(cost_nano + fee_nano) FILTER (WHERE created_at >= $2), 0)::bigint AS month_nano,
       coalesce(sum(cost_nano + fee_nano), 0)::bigint AS total_nano
FROM calls
WHERE api_key_id = ANY($3::uuid[])
GROUP BY api_key_id
`

type KeySpendParams struct {
	DayStart   time.Time
	MonthStart time.Time
	KeyIds     []string
}

type KeySpendRow struct {
	ApiKeyID  *string
	TodayNano int64
	MonthNano int64
	TotalNano int64
}

func (q *Queries) KeySpend(ctx context.Context, arg KeySpendParams) ([]KeySpendRow, error) {
	rows, err := q.db.Query(ctx, keySpend, arg.DayStart, arg.MonthStart, arg.KeyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeySpendRow
	for rows.Next() {
		var i KeySpendRow
		if err := rows.Scan(
			&i.ApiKeyID,
			&i.TodayNano,
			&i.MonthNano,
			&i.TotalNano,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerKeys = `-- name: ListOwnerKeys :many
SELECT id, owner_id, name, prefix, key_hash, key_ciphertext, key_nonce, key_key_id, status, expires_at, allowed_models, budget_daily_nano, budget_monthly_nano, budget_total_nano, model_aliases, last_used_at, deleted_at, created_at, updated_at FROM api_keys WHERE owner_id = $1 AND deleted_at IS NULL ORDER BY created_at, id
`

func (q *Queries) ListOwnerKeys(ctx context.Context, ownerID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listOwnerKeys, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.KeyCiphertext,
			&i.KeyNonce,
			&i.KeyKeyID,
			&i.Status,
			&i.ExpiresAt,
			&i.AllowedModels,
			&i.BudgetDailyNano,
			&i.BudgetMonthlyNano,
			&i.BudgetTotalNano,
			&i.ModelAliases,
			&i.LastUsedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutePrefChannels = `-- name: ListRoutePrefChannels :many
SELECT route_pref_id, channel_id, position, excluded
FROM route_pref_channels
WHERE route_pref_id = ANY($1::uuid[])
ORDER BY route_pref_id, position
`

func (q *Queries) ListRoutePrefChannels(ctx context.Context, prefIds []string) ([]RoutePrefChannel, error) {
	rows, err := q.db.Query(ctx, listRoutePrefChannels, prefIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoutePrefChannel
	for rows.Next() {
		var i RoutePrefChannel
		if err := rows.Scan(
			&i.RoutePrefID,
			&i.ChannelID,
			&i.Position,
			&i.Excluded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutePrefs = `-- name: ListRoutePrefs :many
SELECT id, model_id, mode, max_attempts, ttft_timeout_ms, updated_at, api_key_id
FROM route_prefs
WHERE account_id = $1 AND api_key_id IS NOT DISTINCT FROM $2
  AND ($3::text = '' OR model_id = $3)
ORDER BY model_id
`

type ListRoutePrefsParams struct {
	AccountID string
	ApiKeyID  *string
	ModelID   string
}

type ListRoutePrefsRow struct {
	ID            string
	ModelID       string
	Mode          string
	MaxAttempts   *int32
	TtftTimeoutMs *int32
	UpdatedAt     time.Time
	ApiKeyID      *string
}

// Scope-exact lookups: key-level rows when api_key_id is given, account-level rows otherwise.
func (q *Queries) ListRoutePrefs(ctx context.Context, arg ListRoutePrefsParams) ([]ListRoutePrefsRow, error) {
	rows, err := q.db.Query(ctx, listRoutePrefs, arg.AccountID, arg.ApiKeyID, arg.ModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutePrefsRow
	for rows.Next() {
		var i ListRoutePrefsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.Mode,
			&i.MaxAttempts,
			&i.TtftTimeoutMs,
			&i.UpdatedAt,
			&i.ApiKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccount = `-- name: LockAccount :exec
SELECT id FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAccount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, lockAccount, id)
	return err
}

const markDefaultKeyCreated = `-- name: MarkDefaultKeyCreated :one
UPDATE accounts SET default_key_created_at = now()
WHERE id = $1 AND default_key_created_at IS NULL
RETURNING id
`

// Sets the default-key marker once; returns a row only for the first caller.
func (q *Queries) MarkDefaultKeyCreated(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, markDefaultKeyCreated, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const softDeleteKey = `-- name: SoftDeleteKey :execrows
UPDATE api_keys SET deleted_at = now(), status = 'disabled', updated_at = now()
WHERE owner_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteKeyParams struct {
	OwnerID string
	ID      string
}

func (q *Queries) SoftDeleteKey(ctx context.Context, arg SoftDeleteKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteKey, arg.OwnerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateKey = `-- name: UpdateKey :exec
UPDATE api_keys SET
    name = $3, status = $4, expires_at = $5, allowed_models = $6,
    budget_daily_nano = $7, budget_monthly_nano = $8, budget_total_nano = $9,
    model_aliases = $10, updated_at = now()
WHERE owner_id = $1 AND id = $2 AND deleted_at IS NULL
`

type UpdateKeyParams struct {
	OwnerID           string
	ID                string
	Name              string
	Status            string
	ExpiresAt         *time.Time
	AllowedModels     []string
	BudgetDailyNano   *money.Amount
	BudgetMonthlyNano *money.Amount
	BudgetTotalNano   *money.Amount
	ModelAliases      []byte
}

func (q *Queries) UpdateKey(ctx context.Context, arg UpdateKeyParams) error {
	_, err := q.db.Exec(ctx, updateKey,
		arg.OwnerID,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.ExpiresAt,
		arg.AllowedModels,
		arg.BudgetDailyNano,
		arg.BudgetMonthlyNano,
		arg.BudgetTotalNano,
		arg.ModelAliases,
	)
	return err
}

const upsertRoutePref = `-- name: UpsertRoutePref :one
INSERT INTO route_prefs (account_id, api_key_id, model_id, mode, max_attempts, ttft_timeout_ms)
VALUES ($1, $6, $2, $3, $4, $5)
ON CONFLICT (account_id, api_key_id, model_id)
DO UPDATE SET mode = EXCLUDED.mode, max_attempts = EXCLUDED.max_attempts,
              ttft_timeout_ms = EXCLUDED.ttft_timeout_ms, updated_at = now()
RETURNING id, updated_at
`

type UpsertRoutePrefParams struct {
	AccountID     string
	ModelID       string
	Mode          string
	MaxAttempts   *int32
	TtftTimeoutMs *int32
	ApiKeyID      *string
}

type UpsertRoutePrefRow struct {
	ID        string
	UpdatedAt time.Time
}

func (q *Queries) UpsertRoutePref(ctx context.Context, arg UpsertRoutePrefParams) (UpsertRoutePrefRow, error) {
	row := q.db.QueryRow(ctx, upsertRoutePref,
		arg.AccountID,
		arg.ModelID,
		arg.Mode,
		arg.MaxAttempts,
		arg.TtftTimeoutMs,
		arg.ApiKeyID,
	)
	var i UpsertRoutePrefRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}
