// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ledgerpg

import (
	"time"
)

type LedgerTransaction struct {
	ID             string
	Type           string
	IdempotencyKey string
	RelatedType    *string
	RelatedID      *string
	ActorID        *string
	Reason         string
	CreatedAt      time.Time
}
