// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package ledgerpg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const getPoints = `-- name: GetPoints :one
SELECT l.balance_nano, a.credit_limit_nano, l.updated_at
FROM ledger_accounts l
JOIN accounts a ON a.id = l.account_id
WHERE l.account_id = $1
`

type GetPointsRow struct {
	BalanceNano     money.Amount
	CreditLimitNano money.Amount
	UpdatedAt       time.Time
}

func (q *Queries) GetPoints(ctx context.Context, accountID *string) (GetPointsRow, error) {
	row := q.db.QueryRow(ctx, getPoints, accountID)
	var i GetPointsRow
	err := row.Scan(&i.BalanceNano, &i.CreditLimitNano, &i.UpdatedAt)
	return i, err
}

const getTransactionByKey = `-- name: GetTransactionByKey :one
SELECT id, type, idempotency_key, related_type, related_id, actor_id, reason, created_at FROM ledger_transactions WHERE idempotency_key = $1
`

func (q *Queries) GetTransactionByKey(ctx context.Context, idempotencyKey string) (LedgerTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByKey, idempotencyKey)
	var i LedgerTransaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.IdempotencyKey,
		&i.RelatedType,
		&i.RelatedID,
		&i.ActorID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO ledger_entries (transaction_id, ledger_account_id, amount_nano, balance_after_nano)
VALUES ($1, $2, $3, $4)
`

type InsertEntryParams struct {
	TransactionID    string
	LedgerAccountID  string
	AmountNano       money.Amount
	BalanceAfterNano money.Amount
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.Exec(ctx, insertEntry,
		arg.TransactionID,
		arg.LedgerAccountID,
		arg.AmountNano,
		arg.BalanceAfterNano,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO ledger_transactions (type, idempotency_key, related_type, related_id, actor_id, reason)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, created_at
`

type InsertTransactionParams struct {
	Type           string
	IdempotencyKey string
	RelatedType    *string
	RelatedID      *string
	ActorID        *string
	Reason         string
}

type InsertTransactionRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (InsertTransactionRow, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.Type,
		arg.IdempotencyKey,
		arg.RelatedType,
		arg.RelatedID,
		arg.ActorID,
		arg.Reason,
	)
	var i InsertTransactionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertUserLedgerAccount = `-- name: InsertUserLedgerAccount :exec
INSERT INTO ledger_accounts (kind, account_id) VALUES ('user', $1)
`

func (q *Queries) InsertUserLedgerAccount(ctx context.Context, accountID *string) error {
	_, err := q.db.Exec(ctx, insertUserLedgerAccount, accountID)
	return err
}

const listTransactionEntries = `-- name: ListTransactionEntries :many
SELECT e.ledger_account_id, l.account_id, l.system_code, e.amount_nano, e.balance_after_nano
FROM ledger_entries e
JOIN ledger_accounts l ON l.id = e.ledger_account_id
WHERE e.transaction_id = $1
ORDER BY e.id
`

type ListTransactionEntriesRow struct {
	LedgerAccountID  string
	AccountID        *string
	SystemCode       *string
	AmountNano       money.Amount
	BalanceAfterNano money.Amount
}

func (q *Queries) ListTransactionEntries(ctx context.Context, transactionID string) ([]ListTransactionEntriesRow, error) {
	rows, err := q.db.Query(ctx, listTransactionEntries, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionEntriesRow
	for rows.Next() {
		var i ListTransactionEntriesRow
		if err := rows.Scan(
			&i.LedgerAccountID,
			&i.AccountID,
			&i.SystemCode,
			&i.AmountNano,
			&i.BalanceAfterNano,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEntries = `-- name: ListUserEntries :many
SELECT e.id, e.transaction_id, t.type, t.reason, t.related_type, t.related_id,
       e.amount_nano, e.balance_after_nano, c.api_key_id, k.name AS api_key_name, e.created_at
FROM ledger_entries e
JOIN ledger_accounts l ON l.id = e.ledger_account_id
JOIN ledger_transactions t ON t.id = e.transaction_id
LEFT JOIN calls c ON t.related_type = 'call' AND c.id = t.related_id
LEFT JOIN api_keys k ON k.id = c.api_key_id
WHERE l.account_id = $1
  AND ($2::text = '' OR t.type = $2)
  AND ($3::text = '' OR c.api_key_id::text = $3)
  AND ($4::timestamptz IS NULL OR e.created_at >= $4)
  AND ($5::timestamptz IS NULL OR e.created_at < $5)
  AND ($6::bigint = 0 OR e.id < $6)
ORDER BY e.id DESC
LIMIT $7
`

type ListUserEntriesParams struct {
	AccountID *string
	Type      string
	ApiKeyID  string
	FromTime  *time.Time
	ToTime    *time.Time
	BeforeID  int64
	RowLimit  int32
}

type ListUserEntriesRow struct {
	ID               int64
	TransactionID    string
	Type             string
	Reason           string
	RelatedType      *string
	RelatedID        *string
	AmountNano       money.Amount
	BalanceAfterNano money.Amount
	ApiKeyID         *string
	ApiKeyName       *string
	CreatedAt        time.Time
}

func (q *Queries) ListUserEntries(ctx context.Context, arg ListUserEntriesParams) ([]ListUserEntriesRow, error) {
	rows, err := q.db.Query(ctx, listUserEntries,
		arg.AccountID,
		arg.Type,
		arg.ApiKeyID,
		arg.FromTime,
		arg.ToTime,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserEntriesRow
	for rows.Next() {
		var i ListUserEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Type,
			&i.Reason,
			&i.RelatedType,
			&i.RelatedID,
			&i.AmountNano,
			&i.BalanceAfterNano,
			&i.ApiKeyID,
			&i.ApiKeyName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLedgerAccounts = `-- name: LockLedgerAccounts :many
SELECT id, account_id, system_code, balance_nano
FROM ledger_accounts
WHERE account_id = ANY($1::uuid[])
   OR system_code = ANY($2::text[])
ORDER BY id
FOR UPDATE
`

type LockLedgerAccountsParams struct {
	UserIds     []string
	SystemCodes []string
}

type LockLedgerAccountsRow struct {
	ID          string
	AccountID   *string
	SystemCode  *string
	BalanceNano money.Amount
}

// Resolves and locks the ledger accounts of one posting in id order, so
// concurrent postings over overlapping accounts cannot deadlock.
func (q *Queries) LockLedgerAccounts(ctx context.Context, arg LockLedgerAccountsParams) ([]LockLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, lockLedgerAccounts, arg.UserIds, arg.SystemCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockLedgerAccountsRow
	for rows.Next() {
		var i LockLedgerAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.SystemCode,
			&i.BalanceNano,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLedgerBalance = `-- name: UpdateLedgerBalance :exec
UPDATE ledger_accounts SET balance_nano = $2, updated_at = now() WHERE id = $1
`

type UpdateLedgerBalanceParams struct {
	ID          string
	BalanceNano money.Amount
}

func (q *Queries) UpdateLedgerBalance(ctx context.Context, arg UpdateLedgerBalanceParams) error {
	_, err := q.db.Exec(ctx, updateLedgerBalance, arg.ID, arg.BalanceNano)
	return err
}
