// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gatewaypg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const authenticateAPIKey = `-- name: AuthenticateAPIKey :one
SELECT k.id, k.owner_account_id, k.generation, k.key_hash
FROM api_keys k
JOIN accounts a ON a.id = k.owner_account_id
WHERE k.key_hash = $1 AND k.status = 'active'
	AND a.status = 'active' AND NOT a.must_change_password
`

type AuthenticateAPIKeyRow struct {
	ID             string
	OwnerAccountID string
	Generation     int64
	KeyHash        []byte
}

func (q *Queries) AuthenticateAPIKey(ctx context.Context, keyHash []byte) (AuthenticateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, authenticateAPIKey, keyHash)
	var i AuthenticateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.Generation,
		&i.KeyHash,
	)
	return i, err
}

const bumpPoolVersion = `-- name: BumpPoolVersion :exec
UPDATE api_model_pools SET version = version + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) BumpPoolVersion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpPoolVersion, id)
	return err
}

const createdAPIKeyMatches = `-- name: CreatedAPIKeyMatches :one
SELECT EXISTS (
	SELECT 1 FROM api_keys
	WHERE id = $1 AND owner_account_id = $2 AND display_name = $3
		AND key_prefix = $4 AND key_hash = $5 AND generation = 1 AND version = 1
)::boolean
`

type CreatedAPIKeyMatchesParams struct {
	ID             string
	OwnerAccountID string
	DisplayName    string
	KeyPrefix      string
	KeyHash        []byte
}

// 提交确认丢失后重读不可变事实：创建与轮换各自核对写入的内容。
func (q *Queries) CreatedAPIKeyMatches(ctx context.Context, arg CreatedAPIKeyMatchesParams) (bool, error) {
	row := q.db.QueryRow(ctx, createdAPIKeyMatches,
		arg.ID,
		arg.OwnerAccountID,
		arg.DisplayName,
		arg.KeyPrefix,
		arg.KeyHash,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const deletePoolMembers = `-- name: DeletePoolMembers :exec
DELETE FROM api_pool_members WHERE pool_id = $1
`

func (q *Queries) DeletePoolMembers(ctx context.Context, poolID string) error {
	_, err := q.db.Exec(ctx, deletePoolMembers, poolID)
	return err
}

const deleteStalePools = `-- name: DeleteStalePools :exec
UPDATE api_model_pools SET status = 'deleted', deleted_at = now(), version = version + 1, updated_at = now()
WHERE api_key_id = $1 AND status = 'active' AND NOT (id = ANY($2::uuid[]))
`

type DeleteStalePoolsParams struct {
	ApiKeyID    string
	KeepPoolIds []string
}

func (q *Queries) DeleteStalePools(ctx context.Context, arg DeleteStalePoolsParams) error {
	_, err := q.db.Exec(ctx, deleteStalePools, arg.ApiKeyID, arg.KeepPoolIds)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, owner_account_id, display_name, key_prefix, generation, status, version,
	last_used_at, created_at, updated_at
FROM api_keys
WHERE id = $1 AND owner_account_id = $2 AND status <> 'deleted'
`

type GetAPIKeyParams struct {
	ID             string
	OwnerAccountID string
}

type GetAPIKeyRow struct {
	ID             string
	OwnerAccountID string
	DisplayName    string
	KeyPrefix      string
	Generation     int64
	Status         string
	Version        int64
	LastUsedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (GetAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.ID, arg.OwnerAccountID)
	var i GetAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.DisplayName,
		&i.KeyPrefix,
		&i.Generation,
		&i.Status,
		&i.Version,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one

INSERT INTO api_keys (owner_account_id, display_name, key_prefix, key_hash)
SELECT a.id, $1, $2, $3
FROM accounts a
WHERE a.id = $4 AND a.status = 'active' AND NOT a.must_change_password
RETURNING id
`

type InsertAPIKeyParams struct {
	DisplayName    string
	KeyPrefix      string
	KeyHash        []byte
	OwnerAccountID string
}

// 网关领域全部 SQL：平台 Key、模型池、调用快照、尝试、终结与结算事实。
// 事务边界、隔离级别（BeginCall 为 REPEATABLE READ，终结类为 SERIALIZABLE）与保存点
// 由 store.go / calls.go 的调用顺序决定，本文件只描述单条语句。
func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.DisplayName,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.OwnerAccountID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertPool = `-- name: InsertPool :one
INSERT INTO api_model_pools (api_key_id, canonical_model_id, protocol)
VALUES ($1, $2, $3) RETURNING id
`

type InsertPoolParams struct {
	ApiKeyID         string
	CanonicalModelID string
	Protocol         string
}

func (q *Queries) InsertPool(ctx context.Context, arg InsertPoolParams) (string, error) {
	row := q.db.QueryRow(ctx, insertPool, arg.ApiKeyID, arg.CanonicalModelID, arg.Protocol)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertPoolMember = `-- name: InsertPoolMember :exec
INSERT INTO api_pool_members (pool_id, offer_id, priority, added_validation_version)
VALUES ($1, $2, $3, $4)
`

type InsertPoolMemberParams struct {
	PoolID                 string
	OfferID                string
	Priority               int32
	AddedValidationVersion int64
}

func (q *Queries) InsertPoolMember(ctx context.Context, arg InsertPoolMemberParams) error {
	_, err := q.db.Exec(ctx, insertPoolMember,
		arg.PoolID,
		arg.OfferID,
		arg.Priority,
		arg.AddedValidationVersion,
	)
	return err
}

const listAPIKeyIDs = `-- name: ListAPIKeyIDs :many
SELECT id FROM api_keys
WHERE owner_account_id = $1 AND status <> 'deleted'
ORDER BY updated_at DESC, id
`

func (q *Queries) ListAPIKeyIDs(ctx context.Context, ownerAccountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAPIKeyIDs, ownerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeyPools = `-- name: ListAPIKeyPools :many
SELECT pool.id, pool.canonical_model_id, model.name AS model_name, pool.protocol, pool.version,
	pool.created_at, pool.updated_at
FROM api_model_pools pool
JOIN models model ON model.id = pool.canonical_model_id
WHERE pool.api_key_id = $1 AND pool.status = 'active'
ORDER BY pool.created_at, pool.id
`

type ListAPIKeyPoolsRow struct {
	ID               string
	CanonicalModelID string
	ModelName        string
	Protocol         string
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListAPIKeyPools(ctx context.Context, apiKeyID string) ([]ListAPIKeyPoolsRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeyPools, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeyPoolsRow
	for rows.Next() {
		var i ListAPIKeyPoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalModelID,
			&i.ModelName,
			&i.Protocol,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingPoolOffers = `-- name: ListExistingPoolOffers :many
SELECT member.offer_id, member.added_validation_version
FROM api_pool_members member
JOIN api_model_pools pool ON pool.id = member.pool_id
WHERE pool.api_key_id = $1 AND pool.status = 'active'
`

type ListExistingPoolOffersRow struct {
	OfferID                string
	AddedValidationVersion int64
}

func (q *Queries) ListExistingPoolOffers(ctx context.Context, apiKeyID string) ([]ListExistingPoolOffersRow, error) {
	rows, err := q.db.Query(ctx, listExistingPoolOffers, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExistingPoolOffersRow
	for rows.Next() {
		var i ListExistingPoolOffersRow
		if err := rows.Scan(&i.OfferID, &i.AddedValidationVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolMembers = `-- name: ListPoolMembers :many
WITH pool_offers AS (
	SELECT offer_id FROM api_pool_members WHERE pool_id = $1
), metrics AS (
	SELECT attempt.offer_id,
		round((count(*) FILTER (WHERE attempt.status = 'succeeded'))::numeric /
			NULLIF(count(*) FILTER (WHERE attempt.status IN ('succeeded', 'failed', 'cancelled', 'incomplete')), 0), 4)::text AS success_rate,
		round(avg(attempt.ttft_milliseconds) FILTER (WHERE attempt.status = 'succeeded'))::bigint AS ttft_milliseconds,
		round((avg(attempt.tokens_per_second_nano) FILTER (WHERE attempt.status = 'succeeded'))::numeric / 1000000000, 3)::text AS tokens_per_second
	FROM api_call_attempts attempt
	WHERE attempt.offer_id IN (SELECT offer_id FROM pool_offers)
	GROUP BY attempt.offer_id
)
SELECT member.priority, member.offer_id, cm.channel_id, c.display_name AS channel_display_name,
	owner.display_name AS owner_display_name,
	member.added_validation_version, offer.validation_version AS current_validation_version,
	model.context_window, cm.model_id, cm.multiplier_nano,
	owner.status AS owner_status, owner.must_change_password AS owner_must_change_password,
	c.status AS channel_status, model.status AS model_status, offer.status AS offer_status,
	latest.status AS validation_status, (credential.channel_id IS NOT NULL)::boolean AS credential_configured,
	NULLIF(CASE WHEN model.input_price_nano_per_million BETWEEN 0 AND 100000000000000
		THEN ceil(model.input_price_nano_per_million::numeric * cm.multiplier_nano::numeric / 1000000000)::bigint ELSE -1 END, -1)::bigint AS input_price,
	NULLIF(CASE WHEN model.output_price_nano_per_million BETWEEN 0 AND 100000000000000
		THEN ceil(model.output_price_nano_per_million::numeric * cm.multiplier_nano::numeric / 1000000000)::bigint ELSE -1 END, -1)::bigint AS output_price,
	NULLIF(CASE WHEN model.cache_write_price_nano_per_million BETWEEN 0 AND 100000000000000
		THEN ceil(model.cache_write_price_nano_per_million::numeric * cm.multiplier_nano::numeric / 1000000000)::bigint ELSE -1 END, -1)::bigint AS cache_write_price,
	NULLIF(CASE WHEN model.cache_read_price_nano_per_million BETWEEN 0 AND 100000000000000
		THEN ceil(model.cache_read_price_nano_per_million::numeric * cm.multiplier_nano::numeric / 1000000000)::bigint ELSE -1 END, -1)::bigint AS cache_read_price,
	metrics.success_rate, metrics.ttft_milliseconds, metrics.tokens_per_second
FROM api_pool_members member
JOIN channel_offers offer ON offer.id = member.offer_id
JOIN channel_models cm ON cm.id = offer.channel_model_id
JOIN channels c ON c.id = cm.channel_id
JOIN accounts owner ON owner.id = c.owner_account_id
JOIN models model ON model.id = cm.model_id
LEFT JOIN channel_credentials credential ON credential.channel_id = c.id AND credential.credential_version = c.credential_version
LEFT JOIN channel_validation_attempts latest ON latest.offer_id = offer.id
	AND latest.validation_version = offer.validation_version AND latest.attempt_seq = offer.validation_attempt_seq
LEFT JOIN metrics ON metrics.offer_id = offer.id
WHERE member.pool_id = $1
ORDER BY member.priority
`

type ListPoolMembersRow struct {
	Priority                 int32
	OfferID                  string
	ChannelID                string
	ChannelDisplayName       string
	OwnerDisplayName         string
	AddedValidationVersion   int64
	CurrentValidationVersion int64
	ContextWindow            int64
	ModelID                  string
	MultiplierNano           money.Amount
	OwnerStatus              string
	OwnerMustChangePassword  bool
	ChannelStatus            string
	ModelStatus              string
	OfferStatus              string
	ValidationStatus         *string
	CredentialConfigured     bool
	InputPrice               int64
	OutputPrice              int64
	CacheWritePrice          int64
	CacheReadPrice           int64
	SuccessRate              *string
	TtftMilliseconds         *int64
	TokensPerSecond          *string
}

// 池成员展示：路由资格、报价与近期指标。价格仅在可表示范围内计算，否则为 NULL；
// NULLIF(... ELSE -1, -1) 让 sqlc 把这些列生成为可空（合法价格恒 >= 0，哨兵值不会冲突）。
func (q *Queries) ListPoolMembers(ctx context.Context, poolID string) ([]ListPoolMembersRow, error) {
	rows, err := q.db.Query(ctx, listPoolMembers, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolMembersRow
	for rows.Next() {
		var i ListPoolMembersRow
		if err := rows.Scan(
			&i.Priority,
			&i.OfferID,
			&i.ChannelID,
			&i.ChannelDisplayName,
			&i.OwnerDisplayName,
			&i.AddedValidationVersion,
			&i.CurrentValidationVersion,
			&i.ContextWindow,
			&i.ModelID,
			&i.MultiplierNano,
			&i.OwnerStatus,
			&i.OwnerMustChangePassword,
			&i.ChannelStatus,
			&i.ModelStatus,
			&i.OfferStatus,
			&i.ValidationStatus,
			&i.CredentialConfigured,
			&i.InputPrice,
			&i.OutputPrice,
			&i.CacheWritePrice,
			&i.CacheReadPrice,
			&i.SuccessRate,
			&i.TtftMilliseconds,
			&i.TokensPerSecond,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolOfferReferences = `-- name: ListPoolOfferReferences :many
SELECT offer_id, added_validation_version FROM api_pool_members WHERE pool_id = $1 ORDER BY priority
`

type ListPoolOfferReferencesRow struct {
	OfferID                string
	AddedValidationVersion int64
}

func (q *Queries) ListPoolOfferReferences(ctx context.Context, poolID string) ([]ListPoolOfferReferencesRow, error) {
	rows, err := q.db.Query(ctx, listPoolOfferReferences, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolOfferReferencesRow
	for rows.Next() {
		var i ListPoolOfferReferencesRow
		if err := rows.Scan(&i.OfferID, &i.AddedValidationVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAPIKey = `-- name: LockAPIKey :one
SELECT version, status FROM api_keys
WHERE id = $1 AND owner_account_id = $2 FOR UPDATE
`

type LockAPIKeyParams struct {
	ID             string
	OwnerAccountID string
}

type LockAPIKeyRow struct {
	Version int64
	Status  string
}

func (q *Queries) LockAPIKey(ctx context.Context, arg LockAPIKeyParams) (LockAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, lockAPIKey, arg.ID, arg.OwnerAccountID)
	var i LockAPIKeyRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const lockAPIKeyAtVersion = `-- name: LockAPIKeyAtVersion :one
SELECT status FROM api_keys
WHERE id = $1 AND owner_account_id = $2 AND version = $3 FOR UPDATE
`

type LockAPIKeyAtVersionParams struct {
	ID             string
	OwnerAccountID string
	Version        int64
}

func (q *Queries) LockAPIKeyAtVersion(ctx context.Context, arg LockAPIKeyAtVersionParams) (string, error) {
	row := q.db.QueryRow(ctx, lockAPIKeyAtVersion, arg.ID, arg.OwnerAccountID, arg.Version)
	var status string
	err := row.Scan(&status)
	return status, err
}

const lockActivePool = `-- name: LockActivePool :one
SELECT id FROM api_model_pools
WHERE api_key_id = $1 AND canonical_model_id = $2 AND protocol = $3 AND status = 'active'
FOR UPDATE
`

type LockActivePoolParams struct {
	ApiKeyID         string
	CanonicalModelID string
	Protocol         string
}

func (q *Queries) LockActivePool(ctx context.Context, arg LockActivePoolParams) (string, error) {
	row := q.db.QueryRow(ctx, lockActivePool, arg.ApiKeyID, arg.CanonicalModelID, arg.Protocol)
	var id string
	err := row.Scan(&id)
	return id, err
}

const renameAPIKey = `-- name: RenameAPIKey :exec
UPDATE api_keys SET display_name = $1, version = version + 1, updated_at = now()
WHERE id = $2 AND owner_account_id = $3
`

type RenameAPIKeyParams struct {
	DisplayName    string
	ID             string
	OwnerAccountID string
}

func (q *Queries) RenameAPIKey(ctx context.Context, arg RenameAPIKeyParams) error {
	_, err := q.db.Exec(ctx, renameAPIKey, arg.DisplayName, arg.ID, arg.OwnerAccountID)
	return err
}

const rotateAPIKey = `-- name: RotateAPIKey :execrows
UPDATE api_keys
SET key_prefix = $1, key_hash = $2, generation = generation + 1,
	version = version + 1, updated_at = now()
WHERE id = $3 AND owner_account_id = $4 AND version = $5 AND status <> 'deleted'
`

type RotateAPIKeyParams struct {
	KeyPrefix       string
	KeyHash         []byte
	ID              string
	OwnerAccountID  string
	ExpectedVersion int64
}

func (q *Queries) RotateAPIKey(ctx context.Context, arg RotateAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateAPIKey,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.ID,
		arg.OwnerAccountID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotatedAPIKeyMatches = `-- name: RotatedAPIKeyMatches :one
SELECT EXISTS (
	SELECT 1 FROM api_keys
	WHERE id = $1 AND owner_account_id = $2 AND key_prefix = $3
		AND key_hash = $4 AND version = $5AND generation > 1 AND status <> 'deleted'
)::boolean
`

type RotatedAPIKeyMatchesParams struct {
	ID                           string
	OwnerAccountID               string
	KeyPrefix                    string
	KeyHash                      []byte
	ExpectedVersionpgCatalogint8 int64
}

func (q *Queries) RotatedAPIKeyMatches(ctx context.Context, arg RotatedAPIKeyMatchesParams) (bool, error) {
	row := q.db.QueryRow(ctx, rotatedAPIKeyMatches,
		arg.ID,
		arg.OwnerAccountID,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.ExpectedVersionpgCatalogint8,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setAPIKeyStatus = `-- name: SetAPIKeyStatus :execrows
UPDATE api_keys
SET status = $1::text, version = version + 1, updated_at = now(),
	deleted_at = CASE WHEN $1::text = 'deleted' THEN now() ELSE NULL END
WHERE id = $2 AND owner_account_id = $3 AND version = $4
`

type SetAPIKeyStatusParams struct {
	Status          string
	ID              string
	OwnerAccountID  string
	ExpectedVersion int64
}

func (q *Queries) SetAPIKeyStatus(ctx context.Context, arg SetAPIKeyStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAPIKeyStatus,
		arg.Status,
		arg.ID,
		arg.OwnerAccountID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
