// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gatewaypg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const channelRevenue = `-- name: ChannelRevenue :one
SELECT coalesce(sum(cost_nano), 0)::bigint FROM calls WHERE final_channel_id = $1 AND created_at >= $2
`

type ChannelRevenueParams struct {
	FinalChannelID *string
	CreatedAt      time.Time
}

func (q *Queries) ChannelRevenue(ctx context.Context, arg ChannelRevenueParams) (int64, error) {
	row := q.db.QueryRow(ctx, channelRevenue, arg.FinalChannelID, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const channelStats24h = `-- name: ChannelStats24h :many
SELECT (att->'channel'->>'id')::uuid AS channel_id,
       count(*)::bigint AS attempts,
       count(*) FILTER (WHERE att->>'end_reason' = 'completed')::bigint AS successes,
       coalesce(percentile_cont(0.5) WITHIN GROUP (ORDER BY (att->>'ttft_ms')::double precision)
            FILTER (WHERE att->>'end_reason' = 'completed' AND att->>'ttft_ms' IS NOT NULL), -1)::double precision AS ttft_p50_ms
FROM calls c
CROSS JOIN LATERAL jsonb_array_elements(c.attempts) AS att
WHERE c.created_at >= now() - interval '24 hours'
  AND att->'channel' IS NOT NULL AND jsonb_typeof(att->'channel') = 'object'
  AND att->>'end_reason' NOT IN ('client_disconnected', 'client_error')
GROUP BY 1
`

type ChannelStats24hRow struct {
	ChannelID string
	Attempts  int64
	Successes int64
	TtftP50Ms float64
}

// Health of channels over the last 24 hours, from the attempts of every call.
// Attempts the client abandoned or that were rejected as the request's own fault
// say nothing about the channel and are left out.
func (q *Queries) ChannelStats24h(ctx context.Context) ([]ChannelStats24hRow, error) {
	rows, err := q.db.Query(ctx, channelStats24h)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelStats24hRow
	for rows.Next() {
		var i ChannelStats24hRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Attempts,
			&i.Successes,
			&i.TtftP50Ms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishCall = `-- name: FinishCall :execrows
UPDATE calls SET
    outcome = $1, model_id = $2, final_channel_id = $3,
    routing_mode = $4, routing_source = $5,
    attempts = $6, input_tokens = $7, output_tokens = $8,
    cache_write_tokens = $9, cache_read_tokens = $10,
    price_snapshot = $11, cost_nano = $12, fee_nano = $13,
    ttft_ms = $14, duration_ms = $15, output_tokens_per_second = $16,
    inter_token_p50_ms = $17, inter_token_p95_ms = $18,
    response_bytes = $19, upstream_response_id = $20,
    completed_at = now()
WHERE id = $21 AND outcome = 'in_progress'
`

type FinishCallParams struct {
	Outcome            string
	ModelID            *string
	ChannelID          *string
	RoutingMode        *string
	RoutingSource      *string
	Attempts           []byte
	InputTokens        int64
	OutputTokens       int64
	CacheWriteTokens   int64
	CacheReadTokens    int64
	PriceSnapshot      []byte
	CostNano           money.Amount
	FeeNano            money.Amount
	TtftMs             *int32
	DurationMs         *int32
	TokensPerSecond    *float64
	InterTokenP50Ms    *int32
	InterTokenP95Ms    *int32
	ResponseBytes      *int64
	UpstreamResponseID *string
	ID                 string
}

// Closes a call exactly once: a call already out of in_progress is left alone.
func (q *Queries) FinishCall(ctx context.Context, arg FinishCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishCall,
		arg.Outcome,
		arg.ModelID,
		arg.ChannelID,
		arg.RoutingMode,
		arg.RoutingSource,
		arg.Attempts,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheWriteTokens,
		arg.CacheReadTokens,
		arg.PriceSnapshot,
		arg.CostNano,
		arg.FeeNano,
		arg.TtftMs,
		arg.DurationMs,
		arg.TokensPerSecond,
		arg.InterTokenP50Ms,
		arg.InterTokenP95Ms,
		arg.ResponseBytes,
		arg.UpstreamResponseID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const homeChannels = `-- name: HomeChannels :one
SELECT count(*) FILTER (WHERE status = 'listed')::bigint AS online, count(*)::bigint AS total
FROM channels WHERE owner_id = $1 AND deleted_at IS NULL
`

type HomeChannelsRow struct {
	Online int64
	Total  int64
}

func (q *Queries) HomeChannels(ctx context.Context, ownerID string) (HomeChannelsRow, error) {
	row := q.db.QueryRow(ctx, homeChannels, ownerID)
	var i HomeChannelsRow
	err := row.Scan(&i.Online, &i.Total)
	return i, err
}

const homePendingTrades = `-- name: HomePendingTrades :one
SELECT count(*)::bigint FROM c2c_trades
WHERE (buyer_id = $1 AND status = 'awaiting_payment') OR (seller_id = $1 AND status = 'paid')
`

func (q *Queries) HomePendingTrades(ctx context.Context, buyerID string) (int64, error) {
	row := q.db.QueryRow(ctx, homePendingTrades, buyerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const homeRevenue = `-- name: HomeRevenue :one
SELECT coalesce(sum(c.cost_nano), 0)::bigint
FROM calls c JOIN channels ch ON ch.id = c.final_channel_id
WHERE ch.owner_id = $1 AND c.created_at >= $2
`

type HomeRevenueParams struct {
	OwnerID   string
	CreatedAt time.Time
}

func (q *Queries) HomeRevenue(ctx context.Context, arg HomeRevenueParams) (int64, error) {
	row := q.db.QueryRow(ctx, homeRevenue, arg.OwnerID, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const homeToday = `-- name: HomeToday :one
SELECT coalesce(sum(cost_nano + fee_nano), 0)::bigint AS spend_nano,
       count(*)::bigint AS calls,
       count(*) FILTER (WHERE outcome IN ('succeeded', 'succeeded_unbilled'))::bigint AS succeeded
FROM calls WHERE account_id = $1 AND created_at >= $2
`

type HomeTodayParams struct {
	AccountID string
	CreatedAt time.Time
}

type HomeTodayRow struct {
	SpendNano int64
	Calls     int64
	Succeeded int64
}

func (q *Queries) HomeToday(ctx context.Context, arg HomeTodayParams) (HomeTodayRow, error) {
	row := q.db.QueryRow(ctx, homeToday, arg.AccountID, arg.CreatedAt)
	var i HomeTodayRow
	err := row.Scan(&i.SpendNano, &i.Calls, &i.Succeeded)
	return i, err
}

const insertCall = `-- name: InsertCall :one
INSERT INTO calls (account_id, api_key_id, requested_model, format, stream, tag, client_user_agent, outcome, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8::text,
        CASE WHEN $8::text = 'in_progress' THEN NULL ELSE now() END)
RETURNING id
`

type InsertCallParams struct {
	AccountID       string
	ApiKeyID        *string
	RequestedModel  string
	Format          string
	Stream          bool
	Tag             *string
	ClientUserAgent *string
	Outcome         string
}

func (q *Queries) InsertCall(ctx context.Context, arg InsertCallParams) (string, error) {
	row := q.db.QueryRow(ctx, insertCall,
		arg.AccountID,
		arg.ApiKeyID,
		arg.RequestedModel,
		arg.Format,
		arg.Stream,
		arg.Tag,
		arg.ClientUserAgent,
		arg.Outcome,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const keySpend = `-- name: KeySpend :one
SELECT coalesce(sum(cost_nano + fee_nano) FILTER (WHERE created_at >= $1), 0)::bigint AS today_nano,
       coalesce(sum(cost_nano + fee_nano) FILTER (WHERE created_at >= $2), 0)::bigint AS month_nano,
       coalesce(sum(cost_nano + fee_nano), 0)::bigint AS total_nano
FROM calls
WHERE api_key_id = $3
`

type KeySpendParams struct {
	DayStart   time.Time
	MonthStart time.Time
	KeyID      *string
}

type KeySpendRow struct {
	TodayNano int64
	MonthNano int64
	TotalNano int64
}

func (q *Queries) KeySpend(ctx context.Context, arg KeySpendParams) (KeySpendRow, error) {
	row := q.db.QueryRow(ctx, keySpend, arg.DayStart, arg.MonthStart, arg.KeyID)
	var i KeySpendRow
	err := row.Scan(&i.TodayNano, &i.MonthNano, &i.TotalNano)
	return i, err
}

const listCandidates = `-- name: ListCandidates :many
SELECT c.id, c.owner_id, c.name, c.base_url, c.api_key_ciphertext, c.api_key_nonce, c.api_key_key_id,
       c.user_agent, c.header_rules, c.concurrency_limit, c.rpm_limit, c.daily_revenue_cap_nano,
       c.ttft_timeout_ms, c.total_timeout_ms, c.cooldown_failures, c.cooldown_seconds,
       cm.upstream_model, cm.multiplier_nano
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
JOIN accounts a ON a.id = c.owner_id
WHERE cm.model_id = $1 AND cm.enabled AND $2::text = ANY(cm.formats)
  AND c.status = 'listed' AND c.deleted_at IS NULL AND a.status = 'active'
ORDER BY c.id
`

type ListCandidatesParams struct {
	ModelID string
	Format  string
}

type ListCandidatesRow struct {
	ID                  string
	OwnerID             string
	Name                string
	BaseUrl             string
	ApiKeyCiphertext    []byte
	ApiKeyNonce         []byte
	ApiKeyKeyID         string
	UserAgent           *string
	HeaderRules         []byte
	ConcurrencyLimit    *int32
	RpmLimit            *int32
	DailyRevenueCapNano *money.Amount
	TtftTimeoutMs       *int32
	TotalTimeoutMs      *int32
	CooldownFailures    *int32
	CooldownSeconds     *int32
	UpstreamModel       string
	MultiplierNano      int64
}

func (q *Queries) ListCandidates(ctx context.Context, arg ListCandidatesParams) ([]ListCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCandidates, arg.ModelID, arg.Format)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesRow
	for rows.Next() {
		var i ListCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyCiphertext,
			&i.ApiKeyNonce,
			&i.ApiKeyKeyID,
			&i.UserAgent,
			&i.HeaderRules,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.DailyRevenueCapNano,
			&i.TtftTimeoutMs,
			&i.TotalTimeoutMs,
			&i.CooldownFailures,
			&i.CooldownSeconds,
			&i.UpstreamModel,
			&i.MultiplierNano,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnlineChannelModels = `-- name: ListOnlineChannelModels :many
SELECT cm.model_id, c.id AS channel_id, c.name AS channel_name, c.owner_id, a.display_name AS owner_name,
       cm.formats, cm.multiplier_nano, c.concurrency_limit, c.rpm_limit, c.daily_revenue_cap_nano,
       c.cooldown_failures, c.cooldown_seconds
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
JOIN accounts a ON a.id = c.owner_id
WHERE cm.enabled AND c.status = 'listed' AND c.deleted_at IS NULL AND a.status = 'active'
ORDER BY cm.model_id, c.id
`

type ListOnlineChannelModelsRow struct {
	ModelID             string
	ChannelID           string
	ChannelName         string
	OwnerID             string
	OwnerName           string
	Formats             []string
	MultiplierNano      int64
	ConcurrencyLimit    *int32
	RpmLimit            *int32
	DailyRevenueCapNano *money.Amount
	CooldownFailures    *int32
	CooldownSeconds     *int32
}

func (q *Queries) ListOnlineChannelModels(ctx context.Context) ([]ListOnlineChannelModelsRow, error) {
	rows, err := q.db.Query(ctx, listOnlineChannelModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOnlineChannelModelsRow
	for rows.Next() {
		var i ListOnlineChannelModelsRow
		if err := rows.Scan(
			&i.ModelID,
			&i.ChannelID,
			&i.ChannelName,
			&i.OwnerID,
			&i.OwnerName,
			&i.Formats,
			&i.MultiplierNano,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.DailyRevenueCapNano,
			&i.CooldownFailures,
			&i.CooldownSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnlineModels = `-- name: ListOnlineModels :many
SELECT DISTINCT cm.model_id
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
JOIN accounts a ON a.id = c.owner_id
WHERE cm.enabled AND c.status = 'listed' AND c.deleted_at IS NULL AND a.status = 'active'
ORDER BY cm.model_id
`

func (q *Queries) ListOnlineModels(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listOnlineModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var model_id string
		if err := rows.Scan(&model_id); err != nil {
			return nil, err
		}
		items = append(items, model_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCalls = `-- name: ListRecentCalls :many
SELECT c.id, c.created_at, c.completed_at, c.model_id, c.requested_model, c.format, c.stream, c.tag,
       c.api_key_id, k.name AS key_name, c.outcome, c.final_channel_id, ch.name AS channel_name,
       c.input_tokens, c.output_tokens, c.cache_write_tokens, c.cache_read_tokens,
       c.cost_nano, c.fee_nano, c.ttft_ms, c.duration_ms
FROM calls c
LEFT JOIN api_keys k ON k.id = c.api_key_id
LEFT JOIN channels ch ON ch.id = c.final_channel_id
WHERE c.account_id = $1
ORDER BY c.created_at DESC, c.id DESC
LIMIT $2
`

type ListRecentCallsParams struct {
	AccountID string
	RowLimit  int32
}

type ListRecentCallsRow struct {
	ID               string
	CreatedAt        time.Time
	CompletedAt      *time.Time
	ModelID          *string
	RequestedModel   string
	Format           string
	Stream           bool
	Tag              *string
	ApiKeyID         *string
	KeyName          *string
	Outcome          string
	FinalChannelID   *string
	ChannelName      *string
	InputTokens      int64
	OutputTokens     int64
	CacheWriteTokens int64
	CacheReadTokens  int64
	CostNano         money.Amount
	FeeNano          money.Amount
	TtftMs           *int32
	DurationMs       *int32
}

func (q *Queries) ListRecentCalls(ctx context.Context, arg ListRecentCallsParams) ([]ListRecentCallsRow, error) {
	rows, err := q.db.Query(ctx, listRecentCalls, arg.AccountID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentCallsRow
	for rows.Next() {
		var i ListRecentCallsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ModelID,
			&i.RequestedModel,
			&i.Format,
			&i.Stream,
			&i.Tag,
			&i.ApiKeyID,
			&i.KeyName,
			&i.Outcome,
			&i.FinalChannelID,
			&i.ChannelName,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheReadTokens,
			&i.CostNano,
			&i.FeeNano,
			&i.TtftMs,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupKey = `-- name: LookupKey :one
SELECT k.id, k.owner_id, k.name, k.prefix, k.status, k.expires_at, k.allowed_models,
       k.budget_daily_nano, k.budget_monthly_nano, k.budget_total_nano, k.model_aliases,
       a.status AS account_status
FROM api_keys k
JOIN accounts a ON a.id = k.owner_id
WHERE k.key_hash = $1 AND k.deleted_at IS NULL
`

type LookupKeyRow struct {
	ID                string
	OwnerID           string
	Name              string
	Prefix            string
	Status            string
	ExpiresAt         *time.Time
	AllowedModels     []string
	BudgetDailyNano   *money.Amount
	BudgetMonthlyNano *money.Amount
	BudgetTotalNano   *money.Amount
	ModelAliases      []byte
	AccountStatus     string
}

func (q *Queries) LookupKey(ctx context.Context, keyHash []byte) (LookupKeyRow, error) {
	row := q.db.QueryRow(ctx, lookupKey, keyHash)
	var i LookupKeyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Prefix,
		&i.Status,
		&i.ExpiresAt,
		&i.AllowedModels,
		&i.BudgetDailyNano,
		&i.BudgetMonthlyNano,
		&i.BudgetTotalNano,
		&i.ModelAliases,
		&i.AccountStatus,
	)
	return i, err
}

const responseChannel = `-- name: ResponseChannel :one
SELECT final_channel_id FROM calls
WHERE upstream_response_id = $1 AND account_id = $2 AND final_channel_id IS NOT NULL
ORDER BY created_at DESC LIMIT 1
`

type ResponseChannelParams struct {
	UpstreamResponseID *string
	AccountID          string
}

func (q *Queries) ResponseChannel(ctx context.Context, arg ResponseChannelParams) (*string, error) {
	row := q.db.QueryRow(ctx, responseChannel, arg.UpstreamResponseID, arg.AccountID)
	var final_channel_id *string
	err := row.Scan(&final_channel_id)
	return final_channel_id, err
}

const setCallLedgerTx = `-- name: SetCallLedgerTx :exec
UPDATE calls SET ledger_tx_id = $2 WHERE id = $1
`

type SetCallLedgerTxParams struct {
	ID         string
	LedgerTxID *string
}

func (q *Queries) SetCallLedgerTx(ctx context.Context, arg SetCallLedgerTxParams) error {
	_, err := q.db.Exec(ctx, setCallLedgerTx, arg.ID, arg.LedgerTxID)
	return err
}

const sweepStaleCalls = `-- name: SweepStaleCalls :execrows
UPDATE calls SET outcome = 'interrupted', completed_at = now()
WHERE outcome = 'in_progress' AND created_at < $1
`

func (q *Queries) SweepStaleCalls(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepStaleCalls, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchKey = `-- name: TouchKey :exec
UPDATE api_keys SET last_used_at = $2 WHERE id = $1
`

type TouchKeyParams struct {
	ID         string
	LastUsedAt *time.Time
}

func (q *Queries) TouchKey(ctx context.Context, arg TouchKeyParams) error {
	_, err := q.db.Exec(ctx, touchKey, arg.ID, arg.LastUsedAt)
	return err
}
