// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gatewaypg

import (
	"context"
	"time"

	"github.com/NexusAgentX/Oh-My-AIHub/backend/internal/money"
)

const allocateUUID = `-- name: AllocateUUID :one
SELECT gen_random_uuid()::text
`

func (q *Queries) AllocateUUID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, allocateUUID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const attemptStats = `-- name: AttemptStats :one
SELECT (count(*) FILTER (WHERE status <> 'in_progress'))::bigint AS completed_attempts,
	(count(*) FILTER (WHERE status = 'in_progress'))::bigint AS in_progress_attempts,
	COALESCE(bool_or(semantic_committed), false)::boolean AS any_committed,
	COALESCE(bool_or(status = 'succeeded'), false)::boolean AS any_succeeded
FROM api_call_attempts WHERE call_id = $1
`

type AttemptStatsRow struct {
	CompletedAttempts  int64
	InProgressAttempts int64
	AnyCommitted       bool
	AnySucceeded       bool
}

func (q *Queries) AttemptStats(ctx context.Context, callID string) (AttemptStatsRow, error) {
	row := q.db.QueryRow(ctx, attemptStats, callID)
	var i AttemptStatsRow
	err := row.Scan(
		&i.CompletedAttempts,
		&i.InProgressAttempts,
		&i.AnyCommitted,
		&i.AnySucceeded,
	)
	return i, err
}

const authenticateAPIKey = `-- name: AuthenticateAPIKey :one
SELECT k.id, k.owner_account_id, k.generation, k.key_hash
FROM api_keys k
JOIN accounts a ON a.id = k.owner_account_id
WHERE k.key_hash = $1 AND k.status = 'active'
	AND a.status = 'active' AND NOT a.must_change_password
`

type AuthenticateAPIKeyRow struct {
	ID             string
	OwnerAccountID string
	Generation     int64
	KeyHash        []byte
}

func (q *Queries) AuthenticateAPIKey(ctx context.Context, keyHash []byte) (AuthenticateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, authenticateAPIKey, keyHash)
	var i AuthenticateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.Generation,
		&i.KeyHash,
	)
	return i, err
}

const bumpAttemptCount = `-- name: BumpAttemptCount :exec
UPDATE api_calls SET upstream_attempt_count = upstream_attempt_count + 1,
	heartbeat_at = now(), lease_expires_at = now() + $1::interval
WHERE id = $2 AND lease_generation = $3
`

type BumpAttemptCountParams struct {
	LeaseDuration   time.Duration
	ID              string
	LeaseGeneration int64
}

func (q *Queries) BumpAttemptCount(ctx context.Context, arg BumpAttemptCountParams) error {
	_, err := q.db.Exec(ctx, bumpAttemptCount, arg.LeaseDuration, arg.ID, arg.LeaseGeneration)
	return err
}

const bumpLeaseGeneration = `-- name: BumpLeaseGeneration :one
UPDATE api_calls
SET lease_generation = lease_generation + 1,
	heartbeat_at = now(), lease_expires_at = now() + $1::interval
WHERE id = $2 AND status = $3::text
RETURNING lease_generation
`

type BumpLeaseGenerationParams struct {
	LeaseDuration time.Duration
	ID            string
	Status        string
}

func (q *Queries) BumpLeaseGeneration(ctx context.Context, arg BumpLeaseGenerationParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpLeaseGeneration, arg.LeaseDuration, arg.ID, arg.Status)
	var lease_generation int64
	err := row.Scan(&lease_generation)
	return lease_generation, err
}

const bumpPoolVersion = `-- name: BumpPoolVersion :exec
UPDATE api_model_pools SET version = version + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) BumpPoolVersion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpPoolVersion, id)
	return err
}

const claimOrphanCalls = `-- name: ClaimOrphanCalls :many

SELECT id, status FROM api_calls
WHERE status IN ('in_progress', 'pending_delivery') AND (heartbeat_at < $1::timestamptz OR lease_expires_at < now())
ORDER BY heartbeat_at NULLS FIRST
FOR UPDATE SKIP LOCKED LIMIT $2::bigint
`

type ClaimOrphanCallsParams struct {
	Cutoff  time.Time
	MaxRows int64
}

type ClaimOrphanCallsRow struct {
	ID     string
	Status string
}

// 孤儿恢复
func (q *Queries) ClaimOrphanCalls(ctx context.Context, arg ClaimOrphanCallsParams) ([]ClaimOrphanCallsRow, error) {
	rows, err := q.db.Query(ctx, claimOrphanCalls, arg.Cutoff, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOrphanCallsRow
	for rows.Next() {
		var i ClaimOrphanCallsRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeAttempt = `-- name: CompleteAttempt :one
UPDATE api_call_attempts
SET status = $1::text, http_status = NULLIF($2::integer, 0), error_code = $3,
	raw_error = $4, raw_error_truncated = $5,
	semantic_committed = semantic_committed OR $6::boolean,
	ttft_milliseconds = $7, duration_milliseconds = $8,
	input_tokens = $9, output_tokens = $10,
	cache_write_tokens = $11, cache_read_tokens = $12,
	tokens_per_second_nano = NULLIF($13::bigint, 0::bigint),
	completed_at = CASE WHEN $1::text = 'pending_delivery' THEN NULL ELSE now() END
WHERE id = $14 AND status = 'in_progress'
RETURNING id, call_id, sequence, offer_id, provider_account_id,
	status, http_status, error_code, raw_error, raw_error_truncated, semantic_committed,
	ttft_milliseconds, duration_milliseconds, tokens_per_second_nano, started_at, completed_at
`

type CompleteAttemptParams struct {
	Status               string
	HttpStatus           int32
	ErrorCode            string
	RawError             string
	RawErrorTruncated    bool
	SemanticCommitted    bool
	TtftMilliseconds     *int64
	DurationMilliseconds *int64
	InputTokens          *int64
	OutputTokens         *int64
	CacheWriteTokens     *int64
	CacheReadTokens      *int64
	TokensPerSecondNano  int64
	ID                   string
}

type CompleteAttemptRow struct {
	ID                   string
	CallID               string
	Sequence             int32
	OfferID              string
	ProviderAccountID    string
	Status               string
	HttpStatus           *int32
	ErrorCode            string
	RawError             string
	RawErrorTruncated    bool
	SemanticCommitted    bool
	TtftMilliseconds     *int64
	DurationMilliseconds *int64
	TokensPerSecondNano  *int64
	StartedAt            time.Time
	CompletedAt          *time.Time
}

func (q *Queries) CompleteAttempt(ctx context.Context, arg CompleteAttemptParams) (CompleteAttemptRow, error) {
	row := q.db.QueryRow(ctx, completeAttempt,
		arg.Status,
		arg.HttpStatus,
		arg.ErrorCode,
		arg.RawError,
		arg.RawErrorTruncated,
		arg.SemanticCommitted,
		arg.TtftMilliseconds,
		arg.DurationMilliseconds,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheWriteTokens,
		arg.CacheReadTokens,
		arg.TokensPerSecondNano,
		arg.ID,
	)
	var i CompleteAttemptRow
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Sequence,
		&i.OfferID,
		&i.ProviderAccountID,
		&i.Status,
		&i.HttpStatus,
		&i.ErrorCode,
		&i.RawError,
		&i.RawErrorTruncated,
		&i.SemanticCommitted,
		&i.TtftMilliseconds,
		&i.DurationMilliseconds,
		&i.TokensPerSecondNano,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const confirmPendingAttempt = `-- name: ConfirmPendingAttempt :execrows
UPDATE api_call_attempts
SET status = 'succeeded', semantic_committed = true, completed_at = now()
WHERE call_id = $1 AND status = 'pending_delivery'
`

func (q *Queries) ConfirmPendingAttempt(ctx context.Context, callID string) (int64, error) {
	result, err := q.db.Exec(ctx, confirmPendingAttempt, callID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmPendingCall = `-- name: ConfirmPendingCall :execrows
UPDATE api_calls
SET status = 'succeeded', heartbeat_at = NULL, lease_expires_at = NULL, completed_at = now()
WHERE id = $1 AND status = 'pending_delivery' AND lease_generation = $2
`

type ConfirmPendingCallParams struct {
	ID              string
	LeaseGeneration int64
}

func (q *Queries) ConfirmPendingCall(ctx context.Context, arg ConfirmPendingCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmPendingCall, arg.ID, arg.LeaseGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createdAPIKeyMatches = `-- name: CreatedAPIKeyMatches :one
SELECT EXISTS (
	SELECT 1 FROM api_keys
	WHERE id = $1 AND owner_account_id = $2 AND display_name = $3
		AND key_prefix = $4 AND key_hash = $5 AND generation = 1 AND version = 1
)::boolean
`

type CreatedAPIKeyMatchesParams struct {
	ID             string
	OwnerAccountID string
	DisplayName    string
	KeyPrefix      string
	KeyHash        []byte
}

// 提交确认丢失后重读不可变事实：创建与轮换各自核对写入的内容。
func (q *Queries) CreatedAPIKeyMatches(ctx context.Context, arg CreatedAPIKeyMatchesParams) (bool, error) {
	row := q.db.QueryRow(ctx, createdAPIKeyMatches,
		arg.ID,
		arg.OwnerAccountID,
		arg.DisplayName,
		arg.KeyPrefix,
		arg.KeyHash,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const dashboardTotals = `-- name: DashboardTotals :one
SELECT
	COALESCE((SELECT sum(call.provider_charge_nano + call.platform_fee_nano)
		FROM api_calls call
		JOIN api_call_candidates candidate ON candidate.call_id = call.id AND candidate.offer_id = call.final_offer_id
		WHERE call.consumer_account_id = $1 AND call.status = 'succeeded'), 0)::bigint AS consumer_spent,
	COALESCE((SELECT sum(call.provider_charge_nano)
		FROM api_calls call
		JOIN api_call_candidates candidate ON candidate.call_id = call.id AND candidate.offer_id = call.final_offer_id
		WHERE candidate.provider_account_id = $1 AND call.status = 'succeeded'), 0)::bigint AS provider_income,
	COALESCE((SELECT sum(call.provider_charge_nano + call.platform_fee_nano)
		FROM api_calls call
		JOIN api_call_candidates candidate ON candidate.call_id = call.id AND candidate.offer_id = call.final_offer_id
		WHERE call.consumer_account_id = $1 AND call.status = 'succeeded'
			AND call.created_at >= date_trunc('day', timezone('UTC', now()))), 0)::bigint AS today_spent,
	COALESCE((SELECT count(*)
		FROM api_calls call
		WHERE call.consumer_account_id = $1 AND call.status = 'succeeded'
			AND call.created_at >= date_trunc('day', timezone('UTC', now()))), 0)::bigint AS today_succeeded_calls,
	COALESCE((SELECT sum(call.provider_charge_nano)
		FROM api_calls call
		JOIN api_call_candidates candidate ON candidate.call_id = call.id AND candidate.offer_id = call.final_offer_id
		WHERE candidate.provider_account_id = $1 AND call.status = 'succeeded'
			AND call.consumer_account_id <> $1
			AND call.created_at >= date_trunc('day', timezone('UTC', now()))), 0)::bigint AS today_external_income,
	(SELECT count(*) FROM api_keys WHERE owner_account_id = $1 AND status = 'active')::bigint AS active_key_count,
	(SELECT count(*) FROM api_model_pools pool JOIN api_keys key ON key.id = pool.api_key_id
		WHERE key.owner_account_id = $1 AND key.status <> 'deleted' AND pool.status = 'active')::bigint AS pool_count,
	(SELECT count(*) FROM channel_offers offer
		JOIN channel_models model ON model.id = offer.channel_model_id
		JOIN channels channel ON channel.id = model.channel_id
		LEFT JOIN channel_validation_attempts attempt ON attempt.offer_id = offer.id
			AND attempt.validation_version = offer.validation_version AND attempt.attempt_seq = offer.validation_attempt_seq
		WHERE channel.owner_account_id = $1 AND channel.status = 'published' AND offer.status = 'active' AND attempt.status = 'passed')::bigint AS healthy_offer_count,
	(SELECT count(*) FROM channel_offers offer
		JOIN channel_models model ON model.id = offer.channel_model_id
		JOIN channels channel ON channel.id = model.channel_id
		LEFT JOIN channel_validation_attempts attempt ON attempt.offer_id = offer.id
			AND attempt.validation_version = offer.validation_version AND attempt.attempt_seq = offer.validation_attempt_seq
		WHERE channel.owner_account_id = $1 AND offer.status <> 'deleted'
			AND NOT (channel.status = 'published' AND offer.status = 'active' AND attempt.status = 'passed'))::bigint AS unhealthy_offer_count
`

type DashboardTotalsRow struct {
	ConsumerSpent       int64
	ProviderIncome      int64
	TodaySpent          int64
	TodaySucceededCalls int64
	TodayExternalIncome int64
	ActiveKeyCount      int64
	PoolCount           int64
	HealthyOfferCount   int64
	UnhealthyOfferCount int64
}

func (q *Queries) DashboardTotals(ctx context.Context, accountID string) (DashboardTotalsRow, error) {
	row := q.db.QueryRow(ctx, dashboardTotals, accountID)
	var i DashboardTotalsRow
	err := row.Scan(
		&i.ConsumerSpent,
		&i.ProviderIncome,
		&i.TodaySpent,
		&i.TodaySucceededCalls,
		&i.TodayExternalIncome,
		&i.ActiveKeyCount,
		&i.PoolCount,
		&i.HealthyOfferCount,
		&i.UnhealthyOfferCount,
	)
	return i, err
}

const deletePoolMembers = `-- name: DeletePoolMembers :exec
DELETE FROM api_pool_members WHERE pool_id = $1
`

func (q *Queries) DeletePoolMembers(ctx context.Context, poolID string) error {
	_, err := q.db.Exec(ctx, deletePoolMembers, poolID)
	return err
}

const deleteStalePools = `-- name: DeleteStalePools :exec
UPDATE api_model_pools SET status = 'deleted', deleted_at = now(), version = version + 1, updated_at = now()
WHERE api_key_id = $1 AND status = 'active' AND NOT (id = ANY($2::uuid[]))
`

type DeleteStalePoolsParams struct {
	ApiKeyID    string
	KeepPoolIds []string
}

func (q *Queries) DeleteStalePools(ctx context.Context, arg DeleteStalePoolsParams) error {
	_, err := q.db.Exec(ctx, deleteStalePools, arg.ApiKeyID, arg.KeepPoolIds)
	return err
}

const finalizeCall = `-- name: FinalizeCall :exec
UPDATE api_calls SET status = $1::text, decision_code = $2::text,
	final_offer_id = NULLIF($3::text, '')::uuid,
	completion_reason = $2::text, input_tokens = $4, output_tokens = $5,
	cache_write_tokens = $6, cache_read_tokens = $7,
	provider_charge_nano = $8, platform_fee_nano = $9,
	final_http_status = NULLIF($10::integer, 0),
	settled_price_tier_seq = $11,
	heartbeat_at = CASE WHEN $1::text = 'pending_delivery' THEN now() ELSE NULL END,
	lease_expires_at = CASE WHEN $1::text = 'pending_delivery' THEN now() + $12::interval ELSE NULL END,
	finalizer_payload_hash = $13, completed_at = $14
WHERE id = $15 AND status = 'in_progress' AND lease_generation = $16
`

type FinalizeCallParams struct {
	Status               string
	Reason               string
	FinalOfferID         string
	InputTokens          *int64
	OutputTokens         *int64
	CacheWriteTokens     *int64
	CacheReadTokens      *int64
	ProviderChargeNano   money.Amount
	PlatformFeeNano      money.Amount
	FinalHttpStatus      int32
	SettledPriceTierSeq  int32
	LeaseDuration        time.Duration
	FinalizerPayloadHash []byte
	CompletedAt          *time.Time
	ID                   string
	LeaseGeneration      int64
}

func (q *Queries) FinalizeCall(ctx context.Context, arg FinalizeCallParams) error {
	_, err := q.db.Exec(ctx, finalizeCall,
		arg.Status,
		arg.Reason,
		arg.FinalOfferID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheWriteTokens,
		arg.CacheReadTokens,
		arg.ProviderChargeNano,
		arg.PlatformFeeNano,
		arg.FinalHttpStatus,
		arg.SettledPriceTierSeq,
		arg.LeaseDuration,
		arg.FinalizerPayloadHash,
		arg.CompletedAt,
		arg.ID,
		arg.LeaseGeneration,
	)
	return err
}

const findActivePool = `-- name: FindActivePool :one
SELECT id, version FROM api_model_pools
WHERE api_key_id = $1 AND canonical_model_id = $2 AND protocol = $3 AND status = 'active'
`

type FindActivePoolParams struct {
	ApiKeyID         string
	CanonicalModelID string
	Protocol         string
}

type FindActivePoolRow struct {
	ID      string
	Version int64
}

func (q *Queries) FindActivePool(ctx context.Context, arg FindActivePoolParams) (FindActivePoolRow, error) {
	row := q.db.QueryRow(ctx, findActivePool, arg.ApiKeyID, arg.CanonicalModelID, arg.Protocol)
	var i FindActivePoolRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, owner_account_id, display_name, key_prefix, generation, status, version,
	last_used_at, created_at, updated_at
FROM api_keys
WHERE id = $1 AND owner_account_id = $2 AND status <> 'deleted'
`

type GetAPIKeyParams struct {
	ID             string
	OwnerAccountID string
}

type GetAPIKeyRow struct {
	ID             string
	OwnerAccountID string
	DisplayName    string
	KeyPrefix      string
	Generation     int64
	Status         string
	Version        int64
	LastUsedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (GetAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.ID, arg.OwnerAccountID)
	var i GetAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.DisplayName,
		&i.KeyPrefix,
		&i.Generation,
		&i.Status,
		&i.Version,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttemptReplayFacts = `-- name: GetAttemptReplayFacts :one
SELECT call_id, offer_id, status, http_status, error_code, raw_error,
	semantic_committed, ttft_milliseconds, duration_milliseconds,
	input_tokens, output_tokens, cache_write_tokens, cache_read_tokens,
	tokens_per_second_nano
FROM api_call_attempts WHERE id = $1
`

type GetAttemptReplayFactsRow struct {
	CallID               string
	OfferID              string
	Status               string
	HttpStatus           *int32
	ErrorCode            string
	RawError             string
	SemanticCommitted    bool
	TtftMilliseconds     *int64
	DurationMilliseconds *int64
	InputTokens          *int64
	OutputTokens         *int64
	CacheWriteTokens     *int64
	CacheReadTokens      *int64
	TokensPerSecondNano  *int64
}

func (q *Queries) GetAttemptReplayFacts(ctx context.Context, id string) (GetAttemptReplayFactsRow, error) {
	row := q.db.QueryRow(ctx, getAttemptReplayFacts, id)
	var i GetAttemptReplayFactsRow
	err := row.Scan(
		&i.CallID,
		&i.OfferID,
		&i.Status,
		&i.HttpStatus,
		&i.ErrorCode,
		&i.RawError,
		&i.SemanticCommitted,
		&i.TtftMilliseconds,
		&i.DurationMilliseconds,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheWriteTokens,
		&i.CacheReadTokens,
		&i.TokensPerSecondNano,
	)
	return i, err
}

const getCall = `-- name: GetCall :one

SELECT call.id, call.consumer_account_id, call.api_key_id, call.key_prefix,
	call.key_generation, call.pool_id, call.pool_version, call.canonical_model_id, call.protocol,
	call.status, call.decision_code, call.candidate_count, call.upstream_attempt_count,
	call.hold_id, call.preauthorized_nano, call.zero_hold_reason,
	call.fee_rate_version, call.fee_rate_nano, call.lease_generation, call.final_offer_id,
	final_channel.display_name AS final_channel_name, call.completion_reason,
	call.input_tokens, call.output_tokens, call.cache_write_tokens, call.cache_read_tokens,
	call.provider_charge_nano, call.platform_fee_nano, call.final_http_status,
	call.settled_price_tier_seq,
	call.created_at, call.completed_at
FROM api_calls call
LEFT JOIN channel_offers final_offer ON final_offer.id = call.final_offer_id
LEFT JOIN channel_models final_model ON final_model.id = final_offer.channel_model_id
LEFT JOIN channels final_channel ON final_channel.id = final_model.channel_id
WHERE call.id = $1 AND ($2::boolean OR call.consumer_account_id = $3::uuid OR EXISTS (
	SELECT 1 FROM api_call_attempts attempt
	WHERE attempt.call_id = call.id AND attempt.provider_account_id = $3::uuid
))
`

type GetCallParams struct {
	ID            string
	Administrator bool
	ViewerID      string
}

type GetCallRow struct {
	ID                   string
	ConsumerAccountID    string
	ApiKeyID             string
	KeyPrefix            string
	KeyGeneration        int64
	PoolID               *string
	PoolVersion          *int64
	CanonicalModelID     string
	Protocol             string
	Status               string
	DecisionCode         string
	CandidateCount       int32
	UpstreamAttemptCount int32
	HoldID               *string
	PreauthorizedNano    money.Amount
	ZeroHoldReason       string
	FeeRateVersion       int64
	FeeRateNano          money.Amount
	LeaseGeneration      int64
	FinalOfferID         *string
	FinalChannelName     *string
	CompletionReason     string
	InputTokens          *int64
	OutputTokens         *int64
	CacheWriteTokens     *int64
	CacheReadTokens      *int64
	ProviderChargeNano   money.Amount
	PlatformFeeNano      money.Amount
	FinalHttpStatus      *int32
	SettledPriceTierSeq  int32
	CreatedAt            time.Time
	CompletedAt          *time.Time
}

// 调用读取
func (q *Queries) GetCall(ctx context.Context, arg GetCallParams) (GetCallRow, error) {
	row := q.db.QueryRow(ctx, getCall, arg.ID, arg.Administrator, arg.ViewerID)
	var i GetCallRow
	err := row.Scan(
		&i.ID,
		&i.ConsumerAccountID,
		&i.ApiKeyID,
		&i.KeyPrefix,
		&i.KeyGeneration,
		&i.PoolID,
		&i.PoolVersion,
		&i.CanonicalModelID,
		&i.Protocol,
		&i.Status,
		&i.DecisionCode,
		&i.CandidateCount,
		&i.UpstreamAttemptCount,
		&i.HoldID,
		&i.PreauthorizedNano,
		&i.ZeroHoldReason,
		&i.FeeRateVersion,
		&i.FeeRateNano,
		&i.LeaseGeneration,
		&i.FinalOfferID,
		&i.FinalChannelName,
		&i.CompletionReason,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheWriteTokens,
		&i.CacheReadTokens,
		&i.ProviderChargeNano,
		&i.PlatformFeeNano,
		&i.FinalHttpStatus,
		&i.SettledPriceTierSeq,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCallFinalizerState = `-- name: GetCallFinalizerState :one
SELECT status, lease_generation, finalizer_payload_hash FROM api_calls WHERE id = $1
`

type GetCallFinalizerStateRow struct {
	Status               string
	LeaseGeneration      int64
	FinalizerPayloadHash []byte
}

func (q *Queries) GetCallFinalizerState(ctx context.Context, id string) (GetCallFinalizerStateRow, error) {
	row := q.db.QueryRow(ctx, getCallFinalizerState, id)
	var i GetCallFinalizerStateRow
	err := row.Scan(&i.Status, &i.LeaseGeneration, &i.FinalizerPayloadHash)
	return i, err
}

const getCandidateByOffer = `-- name: GetCandidateByOffer :one
SELECT offer_id, channel_id, provider_account_id,
	validation_version, credential_version, upstream_model_id, context_window,
	input_price_nano, output_price_nano, cache_write_price_nano, cache_read_price_nano,
	multiplier_nano, self_channel
FROM api_call_candidates WHERE call_id = $1 AND offer_id = $2
`

type GetCandidateByOfferParams struct {
	CallID  string
	OfferID string
}

type GetCandidateByOfferRow struct {
	OfferID             string
	ChannelID           string
	ProviderAccountID   string
	ValidationVersion   int64
	CredentialVersion   int64
	UpstreamModelID     string
	ContextWindow       int64
	InputPriceNano      money.Amount
	OutputPriceNano     money.Amount
	CacheWritePriceNano money.Amount
	CacheReadPriceNano  money.Amount
	MultiplierNano      money.Amount
	SelfChannel         bool
}

func (q *Queries) GetCandidateByOffer(ctx context.Context, arg GetCandidateByOfferParams) (GetCandidateByOfferRow, error) {
	row := q.db.QueryRow(ctx, getCandidateByOffer, arg.CallID, arg.OfferID)
	var i GetCandidateByOfferRow
	err := row.Scan(
		&i.OfferID,
		&i.ChannelID,
		&i.ProviderAccountID,
		&i.ValidationVersion,
		&i.CredentialVersion,
		&i.UpstreamModelID,
		&i.ContextWindow,
		&i.InputPriceNano,
		&i.OutputPriceNano,
		&i.CacheWritePriceNano,
		&i.CacheReadPriceNano,
		&i.MultiplierNano,
		&i.SelfChannel,
	)
	return i, err
}

const getCandidateProvider = `-- name: GetCandidateProvider :one
SELECT provider_account_id FROM api_call_candidates
WHERE call_id = $1 AND priority = $2 AND offer_id = $3
`

type GetCandidateProviderParams struct {
	CallID   string
	Priority int32
	OfferID  string
}

func (q *Queries) GetCandidateProvider(ctx context.Context, arg GetCandidateProviderParams) (string, error) {
	row := q.db.QueryRow(ctx, getCandidateProvider, arg.CallID, arg.Priority, arg.OfferID)
	var provider_account_id string
	err := row.Scan(&provider_account_id)
	return provider_account_id, err
}

const getCompensatedCallReason = `-- name: GetCompensatedCallReason :one
SELECT compensation.reason
FROM api_calls call
JOIN api_call_compensations compensation ON compensation.call_id = call.id
WHERE call.id = $1 AND call.status = 'incomplete' AND call.lease_generation = $2
`

type GetCompensatedCallReasonParams struct {
	ID              string
	LeaseGeneration int64
}

func (q *Queries) GetCompensatedCallReason(ctx context.Context, arg GetCompensatedCallReasonParams) (string, error) {
	row := q.db.QueryRow(ctx, getCompensatedCallReason, arg.ID, arg.LeaseGeneration)
	var reason string
	err := row.Scan(&reason)
	return reason, err
}

const getCompensationReason = `-- name: GetCompensationReason :one
SELECT reason FROM api_call_compensations WHERE call_id = $1
`

func (q *Queries) GetCompensationReason(ctx context.Context, callID string) (string, error) {
	row := q.db.QueryRow(ctx, getCompensationReason, callID)
	var reason string
	err := row.Scan(&reason)
	return reason, err
}

const getHoldFacts = `-- name: GetHoldFacts :one

SELECT status, amount_nano, remaining_nano, captured_nano, released_nano
FROM ledger_holds WHERE id = $1
`

type GetHoldFactsRow struct {
	Status        string
	AmountNano    money.Amount
	RemainingNano money.Amount
	CapturedNano  money.Amount
	ReleasedNano  money.Amount
}

// 提交确认丢失后的恢复读取
func (q *Queries) GetHoldFacts(ctx context.Context, id string) (GetHoldFactsRow, error) {
	row := q.db.QueryRow(ctx, getHoldFacts, id)
	var i GetHoldFactsRow
	err := row.Scan(
		&i.Status,
		&i.AmountNano,
		&i.RemainingNano,
		&i.CapturedNano,
		&i.ReleasedNano,
	)
	return i, err
}

const getKeyForCall = `-- name: GetKeyForCall :one

SELECT key.owner_account_id, ledger_account.id AS ledger_account_id, key.key_prefix, key.generation
FROM api_keys key
JOIN accounts owner ON owner.id = key.owner_account_id
JOIN ledger_accounts ledger_account ON ledger_account.identity_account_id = owner.id
WHERE key.id = $1 AND key.key_hash = $2 AND key.generation = $3 AND key.status = 'active'
	AND owner.status = 'active' AND NOT owner.must_change_password
`

type GetKeyForCallParams struct {
	ID         string
	KeyHash    []byte
	Generation int64
}

type GetKeyForCallRow struct {
	OwnerAccountID  string
	LedgerAccountID string
	KeyPrefix       string
	Generation      int64
}

// 调用：BeginCall（REPEATABLE READ 快照）
func (q *Queries) GetKeyForCall(ctx context.Context, arg GetKeyForCallParams) (GetKeyForCallRow, error) {
	row := q.db.QueryRow(ctx, getKeyForCall, arg.ID, arg.KeyHash, arg.Generation)
	var i GetKeyForCallRow
	err := row.Scan(
		&i.OwnerAccountID,
		&i.LedgerAccountID,
		&i.KeyPrefix,
		&i.Generation,
	)
	return i, err
}

const heartbeatCall = `-- name: HeartbeatCall :execrows

UPDATE api_calls SET heartbeat_at = now(), lease_expires_at = now() + $1::interval
WHERE id = $2 AND status IN ('in_progress', 'pending_delivery') AND lease_generation = $3
`

type HeartbeatCallParams struct {
	LeaseDuration   time.Duration
	ID              string
	LeaseGeneration int64
}

// 心跳与终结
func (q *Queries) HeartbeatCall(ctx context.Context, arg HeartbeatCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatCall, arg.LeaseDuration, arg.ID, arg.LeaseGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAPIKey = `-- name: InsertAPIKey :one

INSERT INTO api_keys (owner_account_id, display_name, key_prefix, key_hash)
SELECT a.id, $1, $2, $3
FROM accounts a
WHERE a.id = $4 AND a.status = 'active' AND NOT a.must_change_password
RETURNING id
`

type InsertAPIKeyParams struct {
	DisplayName    string
	KeyPrefix      string
	KeyHash        []byte
	OwnerAccountID string
}

// 网关领域全部 SQL：平台 Key、模型池、调用快照、尝试、终结与结算事实。
// 事务边界、隔离级别（BeginCall 为 REPEATABLE READ，终结类为 SERIALIZABLE）与保存点
// 由 store.go / calls.go 的调用顺序决定，本文件只描述单条语句。
func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.DisplayName,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.OwnerAccountID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertAttempt = `-- name: InsertAttempt :one
WITH next_sequence AS (
	SELECT (COALESCE(max(sequence), 0) + 1)::integer AS value FROM api_call_attempts WHERE call_id = $1::uuid
)
INSERT INTO api_call_attempts (call_id, sequence, offer_id, provider_account_id, status)
SELECT $1::uuid, value, $2::uuid, $3::uuid, 'in_progress' FROM next_sequence
RETURNING id, call_id, sequence, offer_id, provider_account_id, status, started_at
`

type InsertAttemptParams struct {
	CallID            string
	OfferID           string
	ProviderAccountID string
}

type InsertAttemptRow struct {
	ID                string
	CallID            string
	Sequence          int32
	OfferID           string
	ProviderAccountID string
	Status            string
	StartedAt         time.Time
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) (InsertAttemptRow, error) {
	row := q.db.QueryRow(ctx, insertAttempt, arg.CallID, arg.OfferID, arg.ProviderAccountID)
	var i InsertAttemptRow
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Sequence,
		&i.OfferID,
		&i.ProviderAccountID,
		&i.Status,
		&i.StartedAt,
	)
	return i, err
}

const insertAuthorizedCall = `-- name: InsertAuthorizedCall :exec
INSERT INTO api_calls (
	id, consumer_account_id, consumer_ledger_account_id, api_key_id, key_prefix, key_generation,
	pool_id, pool_version, canonical_model_id, protocol, status, decision_code,
	candidate_count, hold_id, preauthorized_nano, zero_hold_reason,
	fee_rate_version, fee_rate_nano, formula_version, lease_expires_at, heartbeat_at
) VALUES ($1, $2, $3, $4, $5, $6,
	$7, $8, $9, $10, 'in_progress', 'authorized',
	$11, NULLIF($12::text, '')::uuid, $13, $14,
	$15, $16, 'formula-v2', now() + $17::interval, now())
`

type InsertAuthorizedCallParams struct {
	ID                      string
	ConsumerAccountID       string
	ConsumerLedgerAccountID string
	ApiKeyID                string
	KeyPrefix               string
	KeyGeneration           int64
	PoolID                  *string
	PoolVersion             *int64
	CanonicalModelID        string
	Protocol                string
	CandidateCount          int32
	HoldID                  string
	PreauthorizedNano       money.Amount
	ZeroHoldReason          string
	FeeRateVersion          int64
	FeeRateNano             money.Amount
	LeaseDuration           time.Duration
}

func (q *Queries) InsertAuthorizedCall(ctx context.Context, arg InsertAuthorizedCallParams) error {
	_, err := q.db.Exec(ctx, insertAuthorizedCall,
		arg.ID,
		arg.ConsumerAccountID,
		arg.ConsumerLedgerAccountID,
		arg.ApiKeyID,
		arg.KeyPrefix,
		arg.KeyGeneration,
		arg.PoolID,
		arg.PoolVersion,
		arg.CanonicalModelID,
		arg.Protocol,
		arg.CandidateCount,
		arg.HoldID,
		arg.PreauthorizedNano,
		arg.ZeroHoldReason,
		arg.FeeRateVersion,
		arg.FeeRateNano,
		arg.LeaseDuration,
	)
	return err
}

const insertCallPriceTier = `-- name: InsertCallPriceTier :exec
INSERT INTO api_call_price_tiers (
	call_id, seq, name, min_prompt_tokens, max_prompt_tokens, timezone, weekdays,
	start_minute_of_day, end_minute_of_day,
	input_price_nano, output_price_nano, cache_write_price_nano, cache_read_price_nano
) VALUES ($1, $2, $3, $4, $5, $6, $7,
	$8, $9,
	$10, $11, $12, $13)
`

type InsertCallPriceTierParams struct {
	CallID              string
	Seq                 int32
	Name                string
	MinPromptTokens     *int64
	MaxPromptTokens     *int64
	Timezone            string
	Weekdays            []int16
	StartMinuteOfDay    *int16
	EndMinuteOfDay      *int16
	InputPriceNano      money.Amount
	OutputPriceNano     money.Amount
	CacheWritePriceNano money.Amount
	CacheReadPriceNano  money.Amount
}

func (q *Queries) InsertCallPriceTier(ctx context.Context, arg InsertCallPriceTierParams) error {
	_, err := q.db.Exec(ctx, insertCallPriceTier,
		arg.CallID,
		arg.Seq,
		arg.Name,
		arg.MinPromptTokens,
		arg.MaxPromptTokens,
		arg.Timezone,
		arg.Weekdays,
		arg.StartMinuteOfDay,
		arg.EndMinuteOfDay,
		arg.InputPriceNano,
		arg.OutputPriceNano,
		arg.CacheWritePriceNano,
		arg.CacheReadPriceNano,
	)
	return err
}

const insertCandidate = `-- name: InsertCandidate :exec
INSERT INTO api_call_candidates (
	call_id, priority, offer_id, channel_id, provider_account_id,
	validation_version, credential_version, upstream_model_id, context_window,
	input_price_nano, output_price_nano, cache_write_price_nano, cache_read_price_nano,
	multiplier_nano, self_channel, net_debit_upper_bound_nano
) VALUES ($1, $2, $3, $4, $5,
	$6, $7, $8, $9,
	$10, $11, $12, $13,
	$14, $15, $16)
`

type InsertCandidateParams struct {
	CallID                 string
	Priority               int32
	OfferID                string
	ChannelID              string
	ProviderAccountID      string
	ValidationVersion      int64
	CredentialVersion      int64
	UpstreamModelID        string
	ContextWindow          int64
	InputPriceNano         money.Amount
	OutputPriceNano        money.Amount
	CacheWritePriceNano    money.Amount
	CacheReadPriceNano     money.Amount
	MultiplierNano         money.Amount
	SelfChannel            bool
	NetDebitUpperBoundNano money.Amount
}

func (q *Queries) InsertCandidate(ctx context.Context, arg InsertCandidateParams) error {
	_, err := q.db.Exec(ctx, insertCandidate,
		arg.CallID,
		arg.Priority,
		arg.OfferID,
		arg.ChannelID,
		arg.ProviderAccountID,
		arg.ValidationVersion,
		arg.CredentialVersion,
		arg.UpstreamModelID,
		arg.ContextWindow,
		arg.InputPriceNano,
		arg.OutputPriceNano,
		arg.CacheWritePriceNano,
		arg.CacheReadPriceNano,
		arg.MultiplierNano,
		arg.SelfChannel,
		arg.NetDebitUpperBoundNano,
	)
	return err
}

const insertCompensation = `-- name: InsertCompensation :exec
INSERT INTO api_call_compensations (
	call_id, reason, original_transaction_id, reversal_transaction_id,
	provider_charge_reversed_nano, platform_fee_reversed_nano
) VALUES ($1, $2, NULLIF($3::text, '')::uuid, NULLIF($4::text, '')::uuid,
	$5, $6)
`

type InsertCompensationParams struct {
	CallID                     string
	Reason                     string
	OriginalTransactionID      string
	ReversalTransactionID      string
	ProviderChargeReversedNano money.Amount
	PlatformFeeReversedNano    money.Amount
}

func (q *Queries) InsertCompensation(ctx context.Context, arg InsertCompensationParams) error {
	_, err := q.db.Exec(ctx, insertCompensation,
		arg.CallID,
		arg.Reason,
		arg.OriginalTransactionID,
		arg.ReversalTransactionID,
		arg.ProviderChargeReversedNano,
		arg.PlatformFeeReversedNano,
	)
	return err
}

const insertPool = `-- name: InsertPool :one
INSERT INTO api_model_pools (api_key_id, canonical_model_id, protocol)
VALUES ($1, $2, $3) RETURNING id
`

type InsertPoolParams struct {
	ApiKeyID         string
	CanonicalModelID string
	Protocol         string
}

func (q *Queries) InsertPool(ctx context.Context, arg InsertPoolParams) (string, error) {
	row := q.db.QueryRow(ctx, insertPool, arg.ApiKeyID, arg.CanonicalModelID, arg.Protocol)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertPoolMember = `-- name: InsertPoolMember :exec
INSERT INTO api_pool_members (pool_id, offer_id, priority, added_validation_version)
VALUES ($1, $2, $3, $4)
`

type InsertPoolMemberParams struct {
	PoolID                 string
	OfferID                string
	Priority               int32
	AddedValidationVersion int64
}

func (q *Queries) InsertPoolMember(ctx context.Context, arg InsertPoolMemberParams) error {
	_, err := q.db.Exec(ctx, insertPoolMember,
		arg.PoolID,
		arg.OfferID,
		arg.Priority,
		arg.AddedValidationVersion,
	)
	return err
}

const insertRejectedCall = `-- name: InsertRejectedCall :exec
INSERT INTO api_calls (
	id, consumer_account_id, consumer_ledger_account_id, api_key_id, key_prefix, key_generation,
	canonical_model_id, protocol, status, decision_code, candidate_count,
	upstream_attempt_count, preauthorized_nano, zero_hold_reason,
	fee_rate_version, fee_rate_nano, completion_reason, completed_at
) VALUES ($1, $2, $3, $4, $5, $6,
	$7, $8, 'rejected', $9::text, 0, 0, 0,
	'business_precheck_rejected', $10, $11, $9::text, now())
`

type InsertRejectedCallParams struct {
	ID                      string
	ConsumerAccountID       string
	ConsumerLedgerAccountID string
	ApiKeyID                string
	KeyPrefix               string
	KeyGeneration           int64
	CanonicalModelID        string
	Protocol                string
	DecisionCode            string
	FeeRateVersion          int64
	FeeRateNano             money.Amount
}

func (q *Queries) InsertRejectedCall(ctx context.Context, arg InsertRejectedCallParams) error {
	_, err := q.db.Exec(ctx, insertRejectedCall,
		arg.ID,
		arg.ConsumerAccountID,
		arg.ConsumerLedgerAccountID,
		arg.ApiKeyID,
		arg.KeyPrefix,
		arg.KeyGeneration,
		arg.CanonicalModelID,
		arg.Protocol,
		arg.DecisionCode,
		arg.FeeRateVersion,
		arg.FeeRateNano,
	)
	return err
}

const insertSettlement = `-- name: InsertSettlement :exec
INSERT INTO api_call_settlements (
	call_id, kind, provider_account_id, provider_charge_nano, platform_fee_nano,
	capture_transaction_id, self_transaction_id, hold_id
) VALUES ($1, $2, NULLIF($3::text, '')::uuid, $4, $5,
	NULLIF($6::text, '')::uuid, NULLIF($7::text, '')::uuid, NULLIF($8::text, '')::uuid)
`

type InsertSettlementParams struct {
	CallID               string
	Kind                 string
	ProviderAccountID    string
	ProviderChargeNano   money.Amount
	PlatformFeeNano      money.Amount
	CaptureTransactionID string
	SelfTransactionID    string
	HoldID               string
}

func (q *Queries) InsertSettlement(ctx context.Context, arg InsertSettlementParams) error {
	_, err := q.db.Exec(ctx, insertSettlement,
		arg.CallID,
		arg.Kind,
		arg.ProviderAccountID,
		arg.ProviderChargeNano,
		arg.PlatformFeeNano,
		arg.CaptureTransactionID,
		arg.SelfTransactionID,
		arg.HoldID,
	)
	return err
}

const latestFeeRate = `-- name: LatestFeeRate :one
SELECT version, fee_rate_nano FROM api_fee_rates ORDER BY version DESC LIMIT 1
`

type LatestFeeRateRow struct {
	Version     int64
	FeeRateNano money.Amount
}

func (q *Queries) LatestFeeRate(ctx context.Context) (LatestFeeRateRow, error) {
	row := q.db.QueryRow(ctx, latestFeeRate)
	var i LatestFeeRateRow
	err := row.Scan(&i.Version, &i.FeeRateNano)
	return i, err
}

const listAPIKeyIDs = `-- name: ListAPIKeyIDs :many
SELECT id FROM api_keys
WHERE owner_account_id = $1 AND status <> 'deleted'
ORDER BY updated_at DESC, id
`

func (q *Queries) ListAPIKeyIDs(ctx context.Context, ownerAccountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAPIKeyIDs, ownerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeyPools = `-- name: ListAPIKeyPools :many
SELECT pool.id, pool.canonical_model_id, model.name AS model_name, pool.protocol, pool.version,
	pool.created_at, pool.updated_at
FROM api_model_pools pool
JOIN models model ON model.id = pool.canonical_model_id
WHERE pool.api_key_id = $1 AND pool.status = 'active'
ORDER BY pool.created_at, pool.id
`

type ListAPIKeyPoolsRow struct {
	ID               string
	CanonicalModelID string
	ModelName        string
	Protocol         string
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListAPIKeyPools(ctx context.Context, apiKeyID string) ([]ListAPIKeyPoolsRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeyPools, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeyPoolsRow
	for rows.Next() {
		var i ListAPIKeyPoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalModelID,
			&i.ModelName,
			&i.Protocol,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsForFinalization = `-- name: ListAttemptsForFinalization :many
SELECT id, status, offer_id, COALESCE(http_status, 0)::integer AS http_status, error_code,
	semantic_committed, input_tokens, output_tokens, cache_write_tokens, cache_read_tokens
FROM api_call_attempts WHERE call_id = $1 ORDER BY sequence
`

type ListAttemptsForFinalizationRow struct {
	ID                string
	Status            string
	OfferID           string
	HttpStatus        int32
	ErrorCode         string
	SemanticCommitted bool
	InputTokens       *int64
	OutputTokens      *int64
	CacheWriteTokens  *int64
	CacheReadTokens   *int64
}

func (q *Queries) ListAttemptsForFinalization(ctx context.Context, callID string) ([]ListAttemptsForFinalizationRow, error) {
	rows, err := q.db.Query(ctx, listAttemptsForFinalization, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttemptsForFinalizationRow
	for rows.Next() {
		var i ListAttemptsForFinalizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.OfferID,
			&i.HttpStatus,
			&i.ErrorCode,
			&i.SemanticCommitted,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheReadTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallAttempts = `-- name: ListCallAttempts :many
SELECT attempt.id, attempt.call_id, attempt.sequence, attempt.offer_id,
	channel.display_name AS channel_display_name, attempt.provider_account_id, attempt.status,
	attempt.http_status, attempt.error_code,
	CASE WHEN $1::boolean OR $2::boolean OR attempt.provider_account_id = $3::uuid THEN attempt.raw_error ELSE '' END::text AS raw_error,
	CASE WHEN $1::boolean OR $2::boolean OR attempt.provider_account_id = $3::uuid THEN attempt.raw_error_truncated ELSE false END::boolean AS raw_error_truncated,
	attempt.semantic_committed, attempt.ttft_milliseconds, attempt.duration_milliseconds,
	attempt.input_tokens, attempt.output_tokens, attempt.cache_write_tokens, attempt.cache_read_tokens,
	attempt.tokens_per_second_nano, call.lease_generation, attempt.started_at, attempt.completed_at
FROM api_call_attempts attempt
JOIN api_calls call ON call.id = attempt.call_id
JOIN channel_offers offer ON offer.id = attempt.offer_id
JOIN channel_models model ON model.id = offer.channel_model_id
JOIN channels channel ON channel.id = model.channel_id
WHERE attempt.call_id = $4 AND ($1::boolean OR $2::boolean OR attempt.provider_account_id = $3::uuid)
ORDER BY attempt.sequence
`

type ListCallAttemptsParams struct {
	Administrator bool
	Consumer      bool
	ViewerID      string
	CallID        string
}

type ListCallAttemptsRow struct {
	ID                   string
	CallID               string
	Sequence             int32
	OfferID              string
	ChannelDisplayName   string
	ProviderAccountID    string
	Status               string
	HttpStatus           *int32
	ErrorCode            string
	RawError             string
	RawErrorTruncated    bool
	SemanticCommitted    bool
	TtftMilliseconds     *int64
	DurationMilliseconds *int64
	InputTokens          *int64
	OutputTokens         *int64
	CacheWriteTokens     *int64
	CacheReadTokens      *int64
	TokensPerSecondNano  *int64
	LeaseGeneration      int64
	StartedAt            time.Time
	CompletedAt          *time.Time
}

func (q *Queries) ListCallAttempts(ctx context.Context, arg ListCallAttemptsParams) ([]ListCallAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listCallAttempts,
		arg.Administrator,
		arg.Consumer,
		arg.ViewerID,
		arg.CallID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCallAttemptsRow
	for rows.Next() {
		var i ListCallAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.Sequence,
			&i.OfferID,
			&i.ChannelDisplayName,
			&i.ProviderAccountID,
			&i.Status,
			&i.HttpStatus,
			&i.ErrorCode,
			&i.RawError,
			&i.RawErrorTruncated,
			&i.SemanticCommitted,
			&i.TtftMilliseconds,
			&i.DurationMilliseconds,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheReadTokens,
			&i.TokensPerSecondNano,
			&i.LeaseGeneration,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallCandidates = `-- name: ListCallCandidates :many
SELECT priority, offer_id, channel_id, provider_account_id,
	validation_version, credential_version, upstream_model_id, context_window,
	input_price_nano, output_price_nano, cache_write_price_nano, cache_read_price_nano,
	multiplier_nano, self_channel, net_debit_upper_bound_nano
FROM api_call_candidates WHERE call_id = $1 ORDER BY priority
`

type ListCallCandidatesRow struct {
	Priority               int32
	OfferID                string
	ChannelID              string
	ProviderAccountID      string
	ValidationVersion      int64
	CredentialVersion      int64
	UpstreamModelID        string
	ContextWindow          int64
	InputPriceNano         money.Amount
	OutputPriceNano        money.Amount
	CacheWritePriceNano    money.Amount
	CacheReadPriceNano     money.Amount
	MultiplierNano         money.Amount
	SelfChannel            bool
	NetDebitUpperBoundNano money.Amount
}

func (q *Queries) ListCallCandidates(ctx context.Context, callID string) ([]ListCallCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCallCandidates, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCallCandidatesRow
	for rows.Next() {
		var i ListCallCandidatesRow
		if err := rows.Scan(
			&i.Priority,
			&i.OfferID,
			&i.ChannelID,
			&i.ProviderAccountID,
			&i.ValidationVersion,
			&i.CredentialVersion,
			&i.UpstreamModelID,
			&i.ContextWindow,
			&i.InputPriceNano,
			&i.OutputPriceNano,
			&i.CacheWritePriceNano,
			&i.CacheReadPriceNano,
			&i.MultiplierNano,
			&i.SelfChannel,
			&i.NetDebitUpperBoundNano,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallPriceTiers = `-- name: ListCallPriceTiers :many
SELECT name, min_prompt_tokens, max_prompt_tokens, timezone, weekdays,
	start_minute_of_day, end_minute_of_day,
	input_price_nano, output_price_nano, cache_write_price_nano, cache_read_price_nano
FROM api_call_price_tiers WHERE call_id = $1 ORDER BY seq
`

type ListCallPriceTiersRow struct {
	Name                string
	MinPromptTokens     *int64
	MaxPromptTokens     *int64
	Timezone            string
	Weekdays            []int16
	StartMinuteOfDay    *int16
	EndMinuteOfDay      *int16
	InputPriceNano      money.Amount
	OutputPriceNano     money.Amount
	CacheWritePriceNano money.Amount
	CacheReadPriceNano  money.Amount
}

func (q *Queries) ListCallPriceTiers(ctx context.Context, callID string) ([]ListCallPriceTiersRow, error) {
	rows, err := q.db.Query(ctx, listCallPriceTiers, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCallPriceTiersRow
	for rows.Next() {
		var i ListCallPriceTiersRow
		if err := rows.Scan(
			&i.Name,
			&i.MinPromptTokens,
			&i.MaxPromptTokens,
			&i.Timezone,
			&i.Weekdays,
			&i.StartMinuteOfDay,
			&i.EndMinuteOfDay,
			&i.InputPriceNano,
			&i.OutputPriceNano,
			&i.CacheWritePriceNano,
			&i.CacheReadPriceNano,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingPoolOffers = `-- name: ListExistingPoolOffers :many
SELECT member.offer_id, member.added_validation_version
FROM api_pool_members member
JOIN api_model_pools pool ON pool.id = member.pool_id
WHERE pool.api_key_id = $1 AND pool.status = 'active'
`

type ListExistingPoolOffersRow struct {
	OfferID                string
	AddedValidationVersion int64
}

func (q *Queries) ListExistingPoolOffers(ctx context.Context, apiKeyID string) ([]ListExistingPoolOffersRow, error) {
	rows, err := q.db.Query(ctx, listExistingPoolOffers, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExistingPoolOffersRow
	for rows.Next() {
		var i ListExistingPoolOffersRow
		if err := rows.Scan(&i.OfferID, &i.AddedValidationVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolMembers = `-- name: ListPoolMembers :many
WITH pool_offers AS (
	SELECT offer_id FROM api_pool_members WHERE pool_id = $1
), member_prices AS (
	SELECT offer.id AS offer_id,
		CASE WHEN model.input_price_nano_per_million BETWEEN 0 AND 100000000000000
			THEN ceil(model.input_price_nano_per_million::numeric * cm.multiplier_nano::numeric / 1000000000)::bigint END::bigint AS input_price,
		CASE WHEN model.output_price_nano_per_million BETWEEN 0 AND 100000000000000
			THEN ceil(model.output_price_nano_per_million::numeric * cm.multiplier_nano::numeric / 1000000000)::bigint END::bigint AS output_price,
		CASE WHEN model.cache_write_price_nano_per_million BETWEEN 0 AND 100000000000000
			THEN ceil(model.cache_write_price_nano_per_million::numeric * cm.multiplier_nano::numeric / 1000000000)::bigint END::bigint AS cache_write_price,
		CASE WHEN model.cache_read_price_nano_per_million BETWEEN 0 AND 100000000000000
			THEN ceil(model.cache_read_price_nano_per_million::numeric * cm.multiplier_nano::numeric / 1000000000)::bigint END::bigint AS cache_read_price
	FROM channel_offers offer
	JOIN channel_models cm ON cm.id = offer.channel_model_id
	JOIN models model ON model.id = cm.model_id
	WHERE offer.id IN (SELECT offer_id FROM pool_offers)
), metrics AS (
	SELECT attempt.offer_id,
		round((count(*) FILTER (WHERE attempt.status = 'succeeded'))::numeric /
			NULLIF(count(*) FILTER (WHERE attempt.status IN ('succeeded', 'failed', 'cancelled', 'incomplete')), 0), 4)::text AS success_rate,
		round(avg(attempt.ttft_milliseconds) FILTER (WHERE attempt.status = 'succeeded'))::bigint AS ttft_milliseconds,
		round((avg(attempt.tokens_per_second_nano) FILTER (WHERE attempt.status = 'succeeded'))::numeric / 1000000000, 3)::text AS tokens_per_second
	FROM api_call_attempts attempt
	WHERE attempt.offer_id IN (SELECT offer_id FROM pool_offers)
	GROUP BY attempt.offer_id
)
SELECT member.priority, member.offer_id, cm.channel_id, c.display_name AS channel_display_name,
	owner.display_name AS owner_display_name,
	member.added_validation_version, offer.validation_version AS current_validation_version,
	model.context_window, cm.model_id, cm.multiplier_nano,
	owner.status AS owner_status, owner.must_change_password AS owner_must_change_password,
	c.status AS channel_status, model.status AS model_status, offer.status AS offer_status,
	latest.status AS validation_status, (credential.channel_id IS NOT NULL)::boolean AS credential_configured,
	price.input_price, price.output_price, price.cache_write_price, price.cache_read_price,
	metrics.success_rate, metrics.ttft_milliseconds, metrics.tokens_per_second
FROM api_pool_members member
JOIN channel_offers offer ON offer.id = member.offer_id
JOIN channel_models cm ON cm.id = offer.channel_model_id
JOIN channels c ON c.id = cm.channel_id
JOIN accounts owner ON owner.id = c.owner_account_id
JOIN models model ON model.id = cm.model_id
LEFT JOIN channel_credentials credential ON credential.channel_id = c.id AND credential.credential_version = c.credential_version
LEFT JOIN channel_validation_attempts latest ON latest.offer_id = offer.id
	AND latest.validation_version = offer.validation_version AND latest.attempt_seq = offer.validation_attempt_seq
LEFT JOIN member_prices price ON price.offer_id = offer.id
LEFT JOIN metrics ON metrics.offer_id = offer.id
WHERE member.pool_id = $1
ORDER BY member.priority
`

type ListPoolMembersRow struct {
	Priority                 int32
	OfferID                  string
	ChannelID                string
	ChannelDisplayName       string
	OwnerDisplayName         string
	AddedValidationVersion   int64
	CurrentValidationVersion int64
	ContextWindow            int64
	ModelID                  string
	MultiplierNano           money.Amount
	OwnerStatus              string
	OwnerMustChangePassword  bool
	ChannelStatus            string
	ModelStatus              string
	OfferStatus              string
	ValidationStatus         *string
	CredentialConfigured     bool
	InputPrice               *int64
	OutputPrice              *int64
	CacheWritePrice          *int64
	CacheReadPrice           *int64
	SuccessRate              *string
	TtftMilliseconds         *int64
	TokensPerSecond          *string
}

// 池成员展示：路由资格、报价与近期指标。价格仅在可表示范围内计算，否则为 NULL；
// 价格与指标放进 CTE 再 LEFT JOIN，sqlc 才会把这些列生成为可空。
func (q *Queries) ListPoolMembers(ctx context.Context, poolID string) ([]ListPoolMembersRow, error) {
	rows, err := q.db.Query(ctx, listPoolMembers, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolMembersRow
	for rows.Next() {
		var i ListPoolMembersRow
		if err := rows.Scan(
			&i.Priority,
			&i.OfferID,
			&i.ChannelID,
			&i.ChannelDisplayName,
			&i.OwnerDisplayName,
			&i.AddedValidationVersion,
			&i.CurrentValidationVersion,
			&i.ContextWindow,
			&i.ModelID,
			&i.MultiplierNano,
			&i.OwnerStatus,
			&i.OwnerMustChangePassword,
			&i.ChannelStatus,
			&i.ModelStatus,
			&i.OfferStatus,
			&i.ValidationStatus,
			&i.CredentialConfigured,
			&i.InputPrice,
			&i.OutputPrice,
			&i.CacheWritePrice,
			&i.CacheReadPrice,
			&i.SuccessRate,
			&i.TtftMilliseconds,
			&i.TokensPerSecond,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolOfferReferences = `-- name: ListPoolOfferReferences :many
SELECT offer_id, added_validation_version FROM api_pool_members WHERE pool_id = $1 ORDER BY priority
`

type ListPoolOfferReferencesRow struct {
	OfferID                string
	AddedValidationVersion int64
}

func (q *Queries) ListPoolOfferReferences(ctx context.Context, poolID string) ([]ListPoolOfferReferencesRow, error) {
	rows, err := q.db.Query(ctx, listPoolOfferReferences, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolOfferReferencesRow
	for rows.Next() {
		var i ListPoolOfferReferencesRow
		if err := rows.Scan(&i.OfferID, &i.AddedValidationVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleCallIDs = `-- name: ListVisibleCallIDs :many
SELECT DISTINCT call.id::text AS id, call.created_at
FROM api_calls call
LEFT JOIN api_call_attempts attempt ON attempt.call_id = call.id
WHERE $1::boolean OR call.consumer_account_id = $2::uuid OR attempt.provider_account_id = $2::uuid
ORDER BY call.created_at DESC, call.id::text DESC LIMIT $3::bigint
`

type ListVisibleCallIDsParams struct {
	Administrator bool
	ViewerID      string
	MaxRows       int64
}

type ListVisibleCallIDsRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) ListVisibleCallIDs(ctx context.Context, arg ListVisibleCallIDsParams) ([]ListVisibleCallIDsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleCallIDs, arg.Administrator, arg.ViewerID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisibleCallIDsRow
	for rows.Next() {
		var i ListVisibleCallIDsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAPIKey = `-- name: LockAPIKey :one
SELECT version, status FROM api_keys
WHERE id = $1 AND owner_account_id = $2 FOR UPDATE
`

type LockAPIKeyParams struct {
	ID             string
	OwnerAccountID string
}

type LockAPIKeyRow struct {
	Version int64
	Status  string
}

func (q *Queries) LockAPIKey(ctx context.Context, arg LockAPIKeyParams) (LockAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, lockAPIKey, arg.ID, arg.OwnerAccountID)
	var i LockAPIKeyRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const lockAPIKeyAtVersion = `-- name: LockAPIKeyAtVersion :one
SELECT status FROM api_keys
WHERE id = $1 AND owner_account_id = $2 AND version = $3 FOR UPDATE
`

type LockAPIKeyAtVersionParams struct {
	ID             string
	OwnerAccountID string
	Version        int64
}

func (q *Queries) LockAPIKeyAtVersion(ctx context.Context, arg LockAPIKeyAtVersionParams) (string, error) {
	row := q.db.QueryRow(ctx, lockAPIKeyAtVersion, arg.ID, arg.OwnerAccountID, arg.Version)
	var status string
	err := row.Scan(&status)
	return status, err
}

const lockActivePool = `-- name: LockActivePool :one
SELECT id FROM api_model_pools
WHERE api_key_id = $1 AND canonical_model_id = $2 AND protocol = $3 AND status = 'active'
FOR UPDATE
`

type LockActivePoolParams struct {
	ApiKeyID         string
	CanonicalModelID string
	Protocol         string
}

func (q *Queries) LockActivePool(ctx context.Context, arg LockActivePoolParams) (string, error) {
	row := q.db.QueryRow(ctx, lockActivePool, arg.ApiKeyID, arg.CanonicalModelID, arg.Protocol)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockAttemptCommitState = `-- name: LockAttemptCommitState :one
SELECT call.status AS call_status, attempt.status AS attempt_status, call.lease_generation,
	attempt.semantic_committed, attempt.output_tokens
FROM api_call_attempts attempt JOIN api_calls call ON call.id = attempt.call_id
WHERE attempt.id = $1 FOR UPDATE OF call, attempt
`

type LockAttemptCommitStateRow struct {
	CallStatus        string
	AttemptStatus     string
	LeaseGeneration   int64
	SemanticCommitted bool
	OutputTokens      *int64
}

func (q *Queries) LockAttemptCommitState(ctx context.Context, id string) (LockAttemptCommitStateRow, error) {
	row := q.db.QueryRow(ctx, lockAttemptCommitState, id)
	var i LockAttemptCommitStateRow
	err := row.Scan(
		&i.CallStatus,
		&i.AttemptStatus,
		&i.LeaseGeneration,
		&i.SemanticCommitted,
		&i.OutputTokens,
	)
	return i, err
}

const lockAttemptWithCall = `-- name: LockAttemptWithCall :one
SELECT attempt.call_id, call.status AS call_status, attempt.status AS attempt_status, call.lease_generation
FROM api_call_attempts attempt
JOIN api_calls call ON call.id = attempt.call_id
WHERE attempt.id = $1 FOR UPDATE OF call, attempt
`

type LockAttemptWithCallRow struct {
	CallID          string
	CallStatus      string
	AttemptStatus   string
	LeaseGeneration int64
}

func (q *Queries) LockAttemptWithCall(ctx context.Context, id string) (LockAttemptWithCallRow, error) {
	row := q.db.QueryRow(ctx, lockAttemptWithCall, id)
	var i LockAttemptWithCallRow
	err := row.Scan(
		&i.CallID,
		&i.CallStatus,
		&i.AttemptStatus,
		&i.LeaseGeneration,
	)
	return i, err
}

const lockCallForAttempt = `-- name: LockCallForAttempt :one

SELECT status, lease_generation FROM api_calls WHERE id = $1 FOR UPDATE
`

type LockCallForAttemptRow struct {
	Status          string
	LeaseGeneration int64
}

// 尝试
func (q *Queries) LockCallForAttempt(ctx context.Context, id string) (LockCallForAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockCallForAttempt, id)
	var i LockCallForAttemptRow
	err := row.Scan(&i.Status, &i.LeaseGeneration)
	return i, err
}

const lockCallForCompensation = `-- name: LockCallForCompensation :one
SELECT consumer_account_id, status, lease_generation,
	COALESCE(final_offer_id::text, '')::text AS final_offer_id, COALESCE(final_http_status, 0)::integer AS final_http_status
FROM api_calls WHERE id = $1 FOR UPDATE
`

type LockCallForCompensationRow struct {
	ConsumerAccountID string
	Status            string
	LeaseGeneration   int64
	FinalOfferID      string
	FinalHttpStatus   int32
}

func (q *Queries) LockCallForCompensation(ctx context.Context, id string) (LockCallForCompensationRow, error) {
	row := q.db.QueryRow(ctx, lockCallForCompensation, id)
	var i LockCallForCompensationRow
	err := row.Scan(
		&i.ConsumerAccountID,
		&i.Status,
		&i.LeaseGeneration,
		&i.FinalOfferID,
		&i.FinalHttpStatus,
	)
	return i, err
}

const lockCallForDelivery = `-- name: LockCallForDelivery :one

SELECT consumer_account_id, status, lease_generation FROM api_calls WHERE id = $1 FOR UPDATE
`

type LockCallForDeliveryRow struct {
	ConsumerAccountID string
	Status            string
	LeaseGeneration   int64
}

// 送达确认与补偿
func (q *Queries) LockCallForDelivery(ctx context.Context, id string) (LockCallForDeliveryRow, error) {
	row := q.db.QueryRow(ctx, lockCallForDelivery, id)
	var i LockCallForDeliveryRow
	err := row.Scan(&i.ConsumerAccountID, &i.Status, &i.LeaseGeneration)
	return i, err
}

const lockCallForFinalize = `-- name: LockCallForFinalize :one
SELECT consumer_account_id, hold_id, preauthorized_nano, status, lease_generation,
	finalizer_payload_hash, formula_version, created_at, fee_rate_nano
FROM api_calls WHERE id = $1 FOR UPDATE
`

type LockCallForFinalizeRow struct {
	ConsumerAccountID    string
	HoldID               *string
	PreauthorizedNano    money.Amount
	Status               string
	LeaseGeneration      int64
	FinalizerPayloadHash []byte
	FormulaVersion       string
	CreatedAt            time.Time
	FeeRateNano          money.Amount
}

func (q *Queries) LockCallForFinalize(ctx context.Context, id string) (LockCallForFinalizeRow, error) {
	row := q.db.QueryRow(ctx, lockCallForFinalize, id)
	var i LockCallForFinalizeRow
	err := row.Scan(
		&i.ConsumerAccountID,
		&i.HoldID,
		&i.PreauthorizedNano,
		&i.Status,
		&i.LeaseGeneration,
		&i.FinalizerPayloadHash,
		&i.FormulaVersion,
		&i.CreatedAt,
		&i.FeeRateNano,
	)
	return i, err
}

const lockSettlement = `-- name: LockSettlement :one
SELECT provider_charge_nano, platform_fee_nano, capture_transaction_id, self_transaction_id
FROM api_call_settlements WHERE call_id = $1 FOR UPDATE
`

type LockSettlementRow struct {
	ProviderChargeNano   money.Amount
	PlatformFeeNano      money.Amount
	CaptureTransactionID *string
	SelfTransactionID    *string
}

func (q *Queries) LockSettlement(ctx context.Context, callID string) (LockSettlementRow, error) {
	row := q.db.QueryRow(ctx, lockSettlement, callID)
	var i LockSettlementRow
	err := row.Scan(
		&i.ProviderChargeNano,
		&i.PlatformFeeNano,
		&i.CaptureTransactionID,
		&i.SelfTransactionID,
	)
	return i, err
}

const markAttemptCommitted = `-- name: MarkAttemptCommitted :exec
UPDATE api_call_attempts SET semantic_committed = true WHERE id = $1 AND NOT semantic_committed
`

func (q *Queries) MarkAttemptCommitted(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markAttemptCommitted, id)
	return err
}

const markOrphanAttemptIncomplete = `-- name: MarkOrphanAttemptIncomplete :exec
UPDATE api_call_attempts
SET status = 'incomplete', error_code = $1, raw_error = $2,
	raw_error_truncated = false, completed_at = now()
WHERE id = $3 AND status = 'in_progress'
`

type MarkOrphanAttemptIncompleteParams struct {
	ErrorCode string
	RawError  string
	ID        string
}

func (q *Queries) MarkOrphanAttemptIncomplete(ctx context.Context, arg MarkOrphanAttemptIncompleteParams) error {
	_, err := q.db.Exec(ctx, markOrphanAttemptIncomplete, arg.ErrorCode, arg.RawError, arg.ID)
	return err
}

const markPendingAttemptCommitted = `-- name: MarkPendingAttemptCommitted :exec
UPDATE api_call_attempts
SET semantic_committed = true, ttft_milliseconds = $1,
	duration_milliseconds = $2, tokens_per_second_nano = NULLIF($3::bigint, 0::bigint)
WHERE id = $4 AND status = 'pending_delivery' AND NOT semantic_committed
`

type MarkPendingAttemptCommittedParams struct {
	TtftMilliseconds     *int64
	DurationMilliseconds *int64
	TokensPerSecondNano  int64
	ID                   string
}

func (q *Queries) MarkPendingAttemptCommitted(ctx context.Context, arg MarkPendingAttemptCommittedParams) error {
	_, err := q.db.Exec(ctx, markPendingAttemptCommitted,
		arg.TtftMilliseconds,
		arg.DurationMilliseconds,
		arg.TokensPerSecondNano,
		arg.ID,
	)
	return err
}

const markPendingAttemptIncomplete = `-- name: MarkPendingAttemptIncomplete :execrows
UPDATE api_call_attempts
SET status = 'incomplete', error_code = $1,
	raw_error = 'downstream delivery was not durably confirmed', raw_error_truncated = false,
	input_tokens = NULL, output_tokens = NULL, cache_write_tokens = NULL, cache_read_tokens = NULL,
	tokens_per_second_nano = NULL, completed_at = now()
WHERE call_id = $2 AND status = 'pending_delivery'
`

type MarkPendingAttemptIncompleteParams struct {
	ErrorCode string
	CallID    string
}

func (q *Queries) MarkPendingAttemptIncomplete(ctx context.Context, arg MarkPendingAttemptIncompleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPendingAttemptIncomplete, arg.ErrorCode, arg.CallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPendingCallIncomplete = `-- name: MarkPendingCallIncomplete :execrows
UPDATE api_calls
SET status = 'incomplete', decision_code = $1::text, completion_reason = $1::text,
	input_tokens = NULL, output_tokens = NULL, cache_write_tokens = NULL, cache_read_tokens = NULL,
	provider_charge_nano = 0, platform_fee_nano = 0,
	heartbeat_at = NULL, lease_expires_at = NULL, finalizer_payload_hash = $2, completed_at = now()
WHERE id = $3 AND status = 'pending_delivery' AND lease_generation = $4
`

type MarkPendingCallIncompleteParams struct {
	Reason               string
	FinalizerPayloadHash []byte
	ID                   string
	LeaseGeneration      int64
}

func (q *Queries) MarkPendingCallIncomplete(ctx context.Context, arg MarkPendingCallIncompleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPendingCallIncomplete,
		arg.Reason,
		arg.FinalizerPayloadHash,
		arg.ID,
		arg.LeaseGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameAPIKey = `-- name: RenameAPIKey :exec
UPDATE api_keys SET display_name = $1, version = version + 1, updated_at = now()
WHERE id = $2 AND owner_account_id = $3
`

type RenameAPIKeyParams struct {
	DisplayName    string
	ID             string
	OwnerAccountID string
}

func (q *Queries) RenameAPIKey(ctx context.Context, arg RenameAPIKeyParams) error {
	_, err := q.db.Exec(ctx, renameAPIKey, arg.DisplayName, arg.ID, arg.OwnerAccountID)
	return err
}

const rotateAPIKey = `-- name: RotateAPIKey :execrows
UPDATE api_keys
SET key_prefix = $1, key_hash = $2, generation = generation + 1,
	version = version + 1, updated_at = now()
WHERE id = $3 AND owner_account_id = $4 AND version = $5 AND status <> 'deleted'
`

type RotateAPIKeyParams struct {
	KeyPrefix       string
	KeyHash         []byte
	ID              string
	OwnerAccountID  string
	ExpectedVersion int64
}

func (q *Queries) RotateAPIKey(ctx context.Context, arg RotateAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateAPIKey,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.ID,
		arg.OwnerAccountID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotatedAPIKeyMatches = `-- name: RotatedAPIKeyMatches :one
SELECT EXISTS (
	SELECT 1 FROM api_keys
	WHERE id = $1 AND owner_account_id = $2 AND key_prefix = $3
		AND key_hash = $4 AND version = $5
		AND generation > 1 AND status <> 'deleted'
)::boolean
`

type RotatedAPIKeyMatchesParams struct {
	ID             string
	OwnerAccountID string
	KeyPrefix      string
	KeyHash        []byte
	NextVersion    int64
}

func (q *Queries) RotatedAPIKeyMatches(ctx context.Context, arg RotatedAPIKeyMatchesParams) (bool, error) {
	row := q.db.QueryRow(ctx, rotatedAPIKeyMatches,
		arg.ID,
		arg.OwnerAccountID,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.NextVersion,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setAPIKeyStatus = `-- name: SetAPIKeyStatus :execrows
UPDATE api_keys
SET status = $1::text, version = version + 1, updated_at = now(),
	deleted_at = CASE WHEN $1::text = 'deleted' THEN now() ELSE NULL END
WHERE id = $2 AND owner_account_id = $3 AND version = $4
`

type SetAPIKeyStatusParams struct {
	Status          string
	ID              string
	OwnerAccountID  string
	ExpectedVersion int64
}

func (q *Queries) SetAPIKeyStatus(ctx context.Context, arg SetAPIKeyStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAPIKeyStatus,
		arg.Status,
		arg.ID,
		arg.OwnerAccountID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
